import type { MetadataRoute } from "next";
import { SITE_URL, absoluteUrl } from "@/lib/seo/site";

/**
 * Crawl directives (Phase 3.9).
 *
 * Crawl budget genuinely matters at ~500 pages on a new `.jp` with no
 * authority, so the disallows are about eliminating waste rather than hiding
 * anything: auth surfaces have no value to a crawler, and `?chart=` parameter
 * URLs are infinite crawl space generated by a form.
 */
const DISALLOW = [
  "/api/",
  "/sign-in",
  "/sign-up",
  "/settings",
  "/account",
  "/dashboard",
  "/chart/saved",
  "/chart/recent",
  "/saved-charts",
  "/recent-charts",
  "/*?chart=",
];

/**
 * Answer-engine crawlers, allowed deliberately.
 *
 * These are the agents that read a page in order to cite it in an AI answer,
 * and being crawlable is the precondition for being cited. That matters more
 * here than for an English-language site: the Japanese-language Jyotish corpus
 * is thin, so becoming the cited source for questions like 「ナクシャトラとは」
 * takes far less authority than the equivalent English query would.
 *
 * They are listed separately from `*` rather than relying on it because an
 * explicit rule is the only way to signal intent to operators who look, and it
 * keeps this decision reviewable.
 */
const ANSWER_ENGINE_AGENTS = [
  "OAI-SearchBot",
  "ChatGPT-User",
  "PerplexityBot",
  "Perplexity-User",
  "ClaudeBot",
  "Claude-SearchBot",
  "Claude-User",
  "Google-Extended",
  "Applebot-Extended",
  "meta-externalagent",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: "*", allow: "/", disallow: DISALLOW },
      { userAgent: ANSWER_ENGINE_AGENTS, allow: "/", disallow: DISALLOW },
    ],
    sitemap: absoluteUrl("/sitemap.xml"),
    host: SITE_URL,
  };
}
