import type { MetadataRoute } from "next";
import { SITE_URL, absoluteUrl } from "@/lib/seo/site";

/**
 * Crawl directives (Phase 3.9).
 *
 * Crawl budget genuinely matters at ~500 pages on a new `.jp` with no
 * authority, so the disallows are about eliminating waste rather than hiding
 * anything: auth surfaces have no value to a crawler, and `?chart=` parameter
 * URLs are infinite crawl space generated by a form.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/sign-in",
          "/sign-up",
          "/settings",
          "/account",
          "/dashboard",
          "/chart/saved",
          "/chart/recent",
          "/saved-charts",
          "/recent-charts",
          "/*?chart=",
        ],
      },
    ],
    sitemap: absoluteUrl("/sitemap.xml"),
    host: SITE_URL,
  };
}
