import type { NakshatraEntry } from "./types";

export const nakshatrasIntro = {
  en: "The zodiac is divided into 27 Nakshatras of 13°20' each — one lunar day's travel of the Moon. Each mansion has a presiding deity, planetary lord, symbol, and temperament. Your Moon Nakshatra is among the most personal factors in Jyotish.",
  ja: "黄道は月の一日の移動距離である13°20'ずつ、27のナクシャトラに分かれます。各宿には守護神、支配星、象徴、気質があります。月のナクシャトラはジョーティッシュで最も個人的な要素のひとつです。",
};

export const nakshatras: NakshatraEntry[] = [
  {
    id: "ashwini",
    image: "/assets/ashwini.png",
    number: 1,
    name: { en: "Ashwini", ja: "アシュヴィニ" },
    sanskrit: { en: "Aśvinī", ja: "アシュヴィニー" },
    deity: { en: "Ashwini Kumaras (celestial physicians)", ja: "アシュヴィニ・クマーラ（天の医師）" },
    ruler: { en: "Ketu", ja: "ケートゥ" },
    symbol: { en: "Horse's head", ja: "馬の頭" },
    range: { en: "0°00' – 13°20' Aries", ja: "牡羊座 0°00' – 13°20'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Light / swift (Kshipra)", ja: "軽速（クシプラ）" },
    description: {
      en: "The first mansion inaugurates the zodiac with healing speed and new beginnings. Ashwini natives often move quickly, initiate projects boldly, and carry an instinct for restoration — medical, emotional, or spiritual.",
      ja: "最初の宿は癒しと速さ、新しい始まりで黄道を開きます。アシュヴィニの人は行動が速く、大胆にプロジェクトを始め、医療・感情・霊的な回復の本能を持つことが多いです。",
    },
    qualities: [
      { en: "Pioneering, athletic, impatient", ja: "先駆的、運動的、せっかち" },
      { en: "Affinity for medicine, horses, emergencies", ja: "医学、馬、緊急事態との縁" },
    ],
  },
  {
    id: "bharani",
    image: "/assets/bharani.png",
    number: 2,
    name: { en: "Bharani", ja: "バラニ" },
    sanskrit: { en: "Bharaṇī", ja: "バラニー" },
    deity: { en: "Yama (lord of death & dharma)", ja: "ヤマ（死とダルマの神）" },
    ruler: { en: "Venus", ja: "金星" },
    symbol: { en: "Yoni (womb)", ja: "ヨニ（子宮）" },
    range: { en: "13°20' – 26°40' Aries", ja: "牡羊座 13°20' – 26°40'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Fierce (Ugra)", ja: "激烈（ウグラ）" },
    description: {
      en: "Bharani holds the tension of birth and death — creativity through constraint. It governs bearing responsibility, sexual vitality, and moral choices. There is immense creative power when ethically directed.",
      ja: "バラニは生と死の緊張を抱え — 制約を通じた創造です。責任、性的活力、道徳的选择を司ります。倫理に沿って向けられると巨大な創造力があります。",
    },
    qualities: [
      { en: "Intense, sensual, transformative", ja: "強烈、官能的、変容的" },
      { en: "Tests around restraint and desire", ja: "抑制と欲望の試練" },
    ],
  },
  {
    id: "krittika",
    image: "/assets/krittika.png",
    number: 3,
    name: { en: "Krittika", ja: "クリッティカ" },
    sanskrit: { en: "Kṛttikā", ja: "クリッティカー" },
    deity: { en: "Agni (fire god)", ja: "アグニ（火の神）" },
    ruler: { en: "Sun", ja: "太陽" },
    symbol: { en: "Razor / flame", ja: "剃刀／炎" },
    range: { en: "26°40' Aries – 10°00' Taurus", ja: "牡羊座 26°40' – 牡牛座 10°00'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Mixed", ja: "混合" },
    description: {
      en: "Krittika purifies through fire — sharp criticism, cutting clarity, and nurturing warmth (like a cooking flame). It spans the aggressive end of Aries and stable Taurus, blending courage with sustenance.",
      ja: "クリッティカは火による浄化 — 鋭い批判、切断する明晰さ、そして育む温かさ（料理の炎のように）です。牡羊の攻撃性と牡牛の安定をまたぎ、勇気と養育を溶け合わせます。",
    },
    qualities: [
      { en: "Leadership, candor, protective", ja: "指導力、率直さ、保護的" },
      { en: "Careers in cooking, military, criticism", ja: "料理、軍事、批評の職" },
    ],
  },
  {
    id: "rohini",
    image: "/assets/rohini.png",
    number: 4,
    name: { en: "Rohini", ja: "ローヒニ" },
    sanskrit: { en: "Rohiṇī", ja: "ローヒニー" },
    deity: { en: "Brahma / Prajapati (creator)", ja: "ブラフマ／プラジャーパティ（創造神）" },
    ruler: { en: "Moon", ja: "月" },
    symbol: { en: "Chariot / ox cart", ja: "戦車／牛車" },
    range: { en: "10°00' – 23°20' Taurus", ja: "牡牛座 10°00' – 23°20'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Fixed (Dhruva)", ja: "固定（ドルヴァ）" },
    description: {
      en: "Rohini is the Moon's favorite mansion — beauty, fertility, growth, and sensual abundance. Krishna was born under Rohini. It signifies cultivation: arts, agriculture, charisma, and material blossoming.",
      ja: "ローヒニは月の最愛の宿 — 美、豊穣、成長、官能的な豊かさです。クリシュナはローヒニ生まれとされます。芸術、農業、カリスマ、物質的開花を象徴します。",
    },
    qualities: [
      { en: "Magnetic, artistic, luxurious", ja: "魅力的、芸術的、豪華" },
      { en: "Jealousy when possessiveness is unchecked", ja: "所有欲が過ぎると嫉妬" },
    ],
  },
  {
    id: "mrigashira",
    image: "/assets/mrigashira.png",
    number: 5,
    name: { en: "Mrigashira", ja: "ムリガシーラ" },
    sanskrit: { en: "Mṛgaśira", ja: "ムリガシーラ" },
    deity: { en: "Soma (Moon god)", ja: "ソーマ（月の神）" },
    ruler: { en: "Mars", ja: "火星" },
    symbol: { en: "Deer's head", ja: "鹿の頭" },
    range: { en: "23°20' Taurus – 6°40' Gemini", ja: "牡牛座 23°20' – 双子座 6°40'" },
    guna: { en: "Tamas", ja: "タマス" },
    nature: { en: "Soft (Mridu)", ja: "柔和（ムリドゥ）" },
    description: {
      en: "Mrigashira is the searching deer — gentle curiosity, wandering inquiry, and pursuit of ideal experience. It blends Taurean stability with Gemini restlessness, producing poets, researchers, and wanderers.",
      ja: "ムリガシーラは探求する鹿 — 穏やかな好奇心、放浪する問い、理想体験の追求です。牡牛の安定と双子の落ち着きのなさを溶かし、詩人、研究者、放浪者を生みます。",
    },
    qualities: [
      { en: "Inquisitive, romantic, elusive", ja: "好奇深い、ロマンチック、捉えどころのない" },
      { en: "Love of travel and subtle beauty", ja: "旅と繊細な美への愛" },
    ],
  },
  {
    id: "ardra",
    image: "/assets/ardra.png",
    number: 6,
    name: { en: "Ardra", ja: "アールドラ" },
    sanskrit: { en: "Ārdrā", ja: "アードラー" },
    deity: { en: "Rudra (storm form of Shiva)", ja: "ルドラ（シヴァの嵐の形）" },
    ruler: { en: "Rahu", ja: "ラーフ" },
    symbol: { en: "Teardrop / diamond", ja: "涙／ダイヤモンド" },
    range: { en: "6°40' – 20°00' Gemini", ja: "双子座 6°40' – 20°00'" },
    guna: { en: "Tamas", ja: "タマス" },
    nature: { en: "Sharp (Tikshna)", ja: "鋭利（ティクシュナ）" },
    description: {
      en: "Ardra brings storms that clear the air — destruction of the old, emotional catharsis, and intellectual breakthrough. Pain here often precedes renewal. Rudra's energy is wild but purifying.",
      ja: "アールドラは空気を澄ます嵐 — 古いものの破壊、感情の浄化、知的突破をもたらします。痛みの後に更新が来ることが多い、ルドラの荒々しくも浄化するエネルギーです。",
    },
    qualities: [
      { en: "Intense mind, reformer, stormy emotions", ja: "強い精神、改革者、嵐のような感情" },
      { en: "Skill in technology and analysis", ja: "技術と分析の才能" },
    ],
  },
  {
    id: "punarvasu",
    image: "/assets/punarvasu.png",
    number: 7,
    name: { en: "Punarvasu", ja: "プナルヴァス" },
    sanskrit: { en: "Punarvasu", ja: "プナルヴァス" },
    deity: { en: "Aditi (mother of gods)", ja: "アディティ（神々の母）" },
    ruler: { en: "Jupiter", ja: "木星" },
    symbol: { en: "Quiver of arrows / house", ja: "矢筒／家" },
    range: { en: "20°00' Gemini – 3°20' Cancer", ja: "双子座 20°00' – 蟹座 3°20'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Movable (Chara)", ja: "可動（チャラ）" },
    description: {
      en: "Punarvasu means \"good again\" — return, restoration, and optimistic renewal after loss. Aditi's boundless motherhood grants shelter and second chances. It favors teachers, repeat journeys, and recovery.",
      ja: "プナルヴァスは「再び良い」— 喪失後の回帰、回復、楽観的な更新です。アディティの限りない母性が庇護と二度目の機会を与えます。教師、再訪の旅、回復に縁があります。",
    },
    qualities: [
      { en: "Hopeful, forgiving, domestic", ja: "希望に満ち、許す、家庭的" },
      { en: "Cycles of departure and return", ja: "離れると戻るサイクル" },
    ],
  },
  {
    id: "pushya",
    image: "/assets/pushya.png",
    number: 8,
    name: { en: "Pushya", ja: "プシュヤ" },
    sanskrit: { en: "Puṣya", ja: "プシュヤ" },
    deity: { en: "Brihaspati (Jupiter as priest)", ja: "ブリハスパティ（祭司としての木星）" },
    ruler: { en: "Saturn", ja: "土星" },
    symbol: { en: "Flower / udder", ja: "花／乳房" },
    range: { en: "3°20' – 16°40' Cancer", ja: "蟹座 3°20' – 16°40'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Light / swift (Kshipra)", ja: "軽速（クシプラ）" },
    description: {
      en: "Pushya is among the most auspicious Nakshatras — nourishment, ritual correctness, and spiritual prosperity. Like milk from the cosmic udder, it feeds growth through discipline and care.",
      ja: "プシュヤは最も吉祥なナクシャトラのひとつ — 養育、儀礼の正しさ、霊的繁栄です。宇宙の乳房からの乳のように、規律とケアを通じて成長を育みます。",
    },
    qualities: [
      { en: "Devoted, nourishing, orthodox", ja: "献身的、養う、正統的" },
      { en: "Excellence in counseling and food", ja: "カウンセリングと食に優れる" },
    ],
  },
  {
    id: "ashlesha",
    image: "/assets/ashlesha.png",
    number: 9,
    name: { en: "Ashlesha", ja: "アシュレシャ" },
    sanskrit: { en: "Āśleṣā", ja: "アーシュレーシャー" },
    deity: { en: "Nagas (serpent deities)", ja: "ナーガ（蛇神）" },
    ruler: { en: "Mercury", ja: "水星" },
    symbol: { en: "Coiled serpent", ja: "巻きつく蛇" },
    range: { en: "16°40' – 30°00' Cancer", ja: "蟹座 16°40' – 30°00'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Sharp (Tikshna)", ja: "鋭利（ティクシュナ）" },
    description: {
      en: "Ashlesha entwines — hypnotic influence, psychological depth, and kundalini symbolism. Nagas guard hidden treasure. Mastery yields powerful healing; misuse slides into manipulation or venomous speech.",
      ja: "アシュレシャは絡みつく — 催眠的影響、心理の深さ、クンダリーニの象徴です。ナーガは隠された宝を守ります。熟達は強力な癒しをもたらし、誤用は操る言葉や毒へと滑ります。",
    },
    qualities: [
      { en: "Penetrating intellect, mystical", ja: "貫く知性、神秘的" },
      { en: "Boundaries around toxic entanglement", ja: "有毒な絡みへの境界" },
    ],
  },
  {
    id: "magha",
    image: "/assets/magha.png",
    number: 10,
    name: { en: "Magha", ja: "マガ" },
    sanskrit: { en: "Maghā", ja: "マガー" },
    deity: { en: "Pitris (ancestral fathers)", ja: "ピトリ（祖先の父）" },
    ruler: { en: "Ketu", ja: "ケートゥ" },
    symbol: { en: "Royal throne", ja: "王座" },
    range: { en: "0°00' – 13°20' Leo", ja: "獅子座 0°00' – 13°20'" },
    guna: { en: "Tamas", ja: "タマス" },
    nature: { en: "Fierce (Ugra)", ja: "激烈（ウグラ）" },
    description: {
      en: "Magha connects to lineage — ancestral pride, royal bearing, and duty toward those who came before. Ceremonies honoring ancestors resonate strongly. Ego must serve legacy, not vanity.",
      ja: "マガは血統につながる — 祖先の誇り、王の風格、先人への義務です。祖先を敬う儀式が強く響きます。エゴは虚栄ではなく遺産に仕える必要があります。",
    },
    qualities: [
      { en: "Regal, traditional, authoritative", ja: "王者の風格、伝統的、権威的" },
      { en: "Strong sense of ceremony", ja: "儀式への強い感覚" },
    ],
  },
  {
    id: "purva-phalguni",
    image: "/assets/purva-phalguni.png",
    number: 11,
    name: { en: "Purva Phalguni", ja: "プルヴァ・パールグニ" },
    sanskrit: { en: "Pūrva Phalgunī", ja: "プールヴァ・パールグニー" },
    deity: { en: "Bhaga (god of delight)", ja: "バガ（喜びの神）" },
    ruler: { en: "Venus", ja: "金星" },
    symbol: { en: "Hammock / front legs of bed", ja: "ハンモック／寝台の前脚" },
    range: { en: "13°20' – 26°40' Leo", ja: "獅子座 13°20' – 26°40'" },
    guna: { en: "Tamas", ja: "タマス" },
    nature: { en: "Fierce (Ugra)", ja: "激烈（ウグラ）" },
    description: {
      en: "Purva Phalguni celebrates union — romance, relaxation, creative play, and the spark before commitment. Bhaga blesses marital joy and leisure. Balance pleasure with purpose to avoid indulgence.",
      ja: "プルヴァ・パールグニは結合を祝う — ロマンス、休息、創造的遊び、誓いの前の火花です。バガは婚姻の喜びと余暇を祝福します。快楽と目的のバランスが大切です。",
    },
    qualities: [
      { en: "Charismatic, pleasure-loving, artistic", ja: "カリスマ、快楽を愛する、芸術的" },
      { en: "Creative performance and celebration", ja: "創造的な表現と祝祭" },
    ],
  },
  {
    id: "uttara-phalguni",
    image: "/assets/uttara-phalguni.png",
    number: 12,
    name: { en: "Uttara Phalguni", ja: "ウッタラ・パールグニ" },
    sanskrit: { en: "Uttara Phalgunī", ja: "ウッタラ・パールグニー" },
    deity: { en: "Aryaman (noble patron of contracts)", ja: "アリヤマン（契約の高貴な守護神）" },
    ruler: { en: "Sun", ja: "太陽" },
    symbol: { en: "Back legs of bed", ja: "寝台の後脚" },
    range: { en: "26°40' Leo – 10°00' Virgo", ja: "獅子座 26°40' – 乙女座 10°00'" },
    guna: { en: "Tamas", ja: "タマス" },
    nature: { en: "Fixed (Dhruva)", ja: "固定（ドルヴァ）" },
    description: {
      en: "Uttara Phalguni formalizes what Purva begins — marriage contracts, patronage, steady friendship, and lasting agreements. Aryaman governs social bonds backed by honor.",
      ja: "ウッタラ・パールグニはプルヴァが始めたことを形式化 — 結婚契約、後援、安定した友情、永続する合意です。アリヤマンは名誉に支えられた社会的絆を司ります。",
    },
    qualities: [
      { en: "Loyal, generous, organized", ja: "忠実、寛大、組織的" },
      { en: "Success through partnerships", ja: "パートナーシップによる成功" },
    ],
  },
  {
    id: "hasta",
    image: "/assets/hasta.png",
    number: 13,
    name: { en: "Hasta", ja: "ハスタ" },
    sanskrit: { en: "Hasta", ja: "ハスタ" },
    deity: { en: "Savitar (Sun as giver of life)", ja: "サヴィタール（生命を与える太陽）" },
    ruler: { en: "Moon", ja: "月" },
    symbol: { en: "Open hand / fist", ja: "開いた手／拳" },
    range: { en: "10°00' – 23°20' Virgo", ja: "乙女座 10°00' – 23°20'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Light / swift (Kshipra)", ja: "軽速（クシプラ）" },
    description: {
      en: "Hasta is the craftsman constellation — skillful hands, witty speech, and capacity to grasp opportunity literally and figuratively. Savitar's creative spark favors artisans, healers, and magicians of detail.",
      ja: "ハスタは職人の星座 — 巧みな手、機知に富む言葉、文字通り・比喩的に機会を掴む力です。サヴィタールの創造の火花は職人、癒し手、細部の魔術師を助けます。",
    },
    qualities: [
      { en: "Dexterous, humorous, service-minded", ja: "器用、ユーモラス、奉仕の心" },
      { en: "Mastery through practice", ja: "実践による熟達" },
    ],
  },
  {
    id: "chitra",
    image: "/assets/chitra.png",
    number: 14,
    name: { en: "Chitra", ja: "チトラ" },
    sanskrit: { en: "Citrā", ja: "チトラー" },
    deity: { en: "Vishvakarma (divine architect)", ja: "ヴィシュヴァカルマ（天の建築家）" },
    ruler: { en: "Mars", ja: "火星" },
    symbol: { en: "Bright jewel / pearl", ja: "輝く宝石／真珠" },
    range: { en: "23°20' Virgo – 6°40' Libra", ja: "乙女座 23°20' – 天秤座 6°40'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Soft (Mridu)", ja: "柔和（ムリドゥ）" },
    description: {
      en: "Chitra builds beauty with structure — design, architecture, fashion, and charisma that shines like a cut gem. Vishvakarma's influence demands both vision and technical precision.",
      ja: "チトラは構造で美を築く — デザイン、建築、ファッション、切り子のように輝くカリスマです。ヴィシュヴァカルマの影響はビジョンと技術的精密さの両方を求めます。",
    },
    qualities: [
      { en: "Elegant, ambitious, visually gifted", ja: "優雅、野心家、視覚的才能" },
      { en: "Attraction to glamour and order", ja: "華やかさと秩序への魅力" },
    ],
  },
  {
    id: "swati",
    image: "/assets/swati.png",
    number: 15,
    name: { en: "Swati", ja: "スワティ" },
    sanskrit: { en: "Svātī", ja: "スヴァーティー" },
    deity: { en: "Vayu (wind god)", ja: "ヴァーユ（風の神）" },
    ruler: { en: "Rahu", ja: "ラーフ" },
    symbol: { en: "Young sprout blown by wind", ja: "風に揺れる若芽" },
    range: { en: "6°40' – 20°00' Libra", ja: "天秤座 6°40' – 20°00'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Movable (Chara)", ja: "可動（チャラ）" },
    description: {
      en: "Swati is independent air — trade winds, self-reliance, and flexible intelligence. Like a sapling bending without breaking, natives adapt and often excel in commerce, diplomacy, or solitary paths.",
      ja: "スワティは独立した風 — 貿易風、自立、柔軟な知性です。折れずに曲がる若芽のように、適応し、商業・外交・ solitary な道で優れることが多いです。",
    },
    qualities: [
      { en: "Free-spirited, diplomatic, restless", ja: "自由な精神、外交的、落ち着きなし" },
      { en: "Success in business and negotiation", ja: "ビジネスと交渉での成功" },
    ],
  },
  {
    id: "vishakha",
    image: "/assets/vishakha.png",
    number: 16,
    name: { en: "Vishakha", ja: "ヴィシャーカ" },
    sanskrit: { en: "Viśākhā", ja: "ヴィシャーカー" },
    deity: { en: "Indra-Agni (king & fire)", ja: "インドラ＝アグニ（王と火）" },
    ruler: { en: "Jupiter", ja: "木星" },
    symbol: { en: "Triumphal arch / forked branch", ja: "凱旋門／分かれた枝" },
    range: { en: "20°00' Libra – 3°20' Scorpio", ja: "天秤座 20°00' – 蠍座 3°20'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Mixed", ja: "混合" },
    description: {
      en: "Vishakha is single-pointed ambition — goal fixation, competitive zeal, and celebration after victory. The forked branch symbolizes a path that must choose one direction to bear fruit.",
      ja: "ヴィシャーカは一点集中の野心 — 目標への固執、競争の熱、勝利後の祝いです。分かれた枝は実を結ぶために一つの方向を選ぶ道を象徴します。",
    },
    qualities: [
      { en: "Determined, goal-oriented, intense", ja: "決意、目標志向、強烈" },
      { en: "Jealous rivalry if unchecked", ja: "制御されなければ嫉妬の競争" },
    ],
  },
  {
    id: "anuradha",
    image: "/assets/anuradha.png",
    number: 17,
    name: { en: "Anuradha", ja: "アヌラーダ" },
    sanskrit: { en: "Anurādhā", ja: "アヌラーダー" },
    deity: { en: "Mitra (god of friendship)", ja: "ミトラ（友情の神）" },
    ruler: { en: "Saturn", ja: "土星" },
    symbol: { en: "Lotus / staff", ja: "蓮／杖" },
    range: { en: "3°20' – 16°40' Scorpio", ja: "蠍座 3°20' – 16°40'" },
    guna: { en: "Tamas", ja: "タマス" },
    nature: { en: "Soft (Mridu)", ja: "柔和（ムリドゥ）" },
    description: {
      en: "Anuradha blooms in unlikely soil — devotion, friendship across borders, and success through loyalty under Saturn's discipline. Mitra's covenant favors organizations, travel abroad, and spiritual groups.",
      ja: "アヌラーダはありえない土壌で開花 — 献身、国境を越える友情、土星の規律下での忠誠による成功です。ミトラの盟約は組織、海外旅行、霊的グループを助けます。",
    },
    qualities: [
      { en: "Devoted, cooperative, resilient", ja: "献身的、協力的、回復力" },
      { en: "Lotus-like grace under pressure", ja: "圧力下での蓮のような優雅さ" },
    ],
  },
  {
    id: "jyeshtha",
    image: "/assets/jyeshtha.png",
    number: 18,
    name: { en: "Jyeshtha", ja: "ジェーシュタ" },
    sanskrit: { en: "Jyeṣṭhā", ja: "ジェーシュター" },
    deity: { en: "Indra (king of gods)", ja: "インドラ（神々の王）" },
    ruler: { en: "Mercury", ja: "水星" },
    symbol: { en: "Earring / umbrella", ja: "耳飾り／傘" },
    range: { en: "16°40' – 30°00' Scorpio", ja: "蠍座 16°40' – 30°00'" },
    guna: { en: "Tamas", ja: "タマス" },
    nature: { en: "Sharp (Tikshna)", ja: "鋭利（ティクシュナ）" },
    description: {
      en: "Jyeshtha is the elder — seniority, protection of family, and the weight of authority. Indra's umbrella shields but also isolates at the top. Themes of jealousy among siblings and guarding reputation arise.",
      ja: "ジェーシュタは長老 — 序列、家族の保護、権威の重さです。インドラの傘は守るが頂点では孤立も生む。兄弟間の嫉妬や評判を守るテーマが浮上します。",
    },
    qualities: [
      { en: "Protective, proud, responsible", ja: "保護的、誇り高い、責任感" },
      { en: "Occult depth of Scorpio", ja: "蠍座のオカルト的深さ" },
    ],
  },
  {
    id: "mula",
    image: "/assets/mula.png",
    number: 19,
    name: { en: "Mula", ja: "ムーラ" },
    sanskrit: { en: "Mūla", ja: "ムーラ" },
    deity: { en: "Nirriti (goddess of dissolution)", ja: "ニッリティ（解散の女神）" },
    ruler: { en: "Ketu", ja: "ケートゥ" },
    symbol: { en: "Bundled roots", ja: "束ねた根" },
    range: { en: "0°00' – 13°20' Sagittarius", ja: "射手座 0°00' – 13°20'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Sharp (Tikshna)", ja: "鋭利（ティクシュナ）" },
    description: {
      en: "Mula uproots — investigation to the core, destruction of false foundations, and philosophical reset. Ketu's influence seeks origin stories and liberation from what no longer nourishes.",
      ja: "ムーラは根こそぎ — 核心への探究、誤った基盤の破壊、哲学的リセットです。ケートゥの影響は起源の物語と、もはや養わないものからの解放を求めます。",
    },
    qualities: [
      { en: "Researcher, blunt, transformative", ja: "研究者、率直、変容的" },
      { en: "Interest in herbs, roots, hidden causes", ja: "薬草、根、隠れた原因への関心" },
    ],
  },
  {
    id: "purva-ashadha",
    image: "/assets/purva-ashadha.png",
    number: 20,
    name: { en: "Purva Ashadha", ja: "プルヴァ・アシャーダ" },
    sanskrit: { en: "Pūrva Aṣāḍhā", ja: "プールヴァ・アーシャーダー" },
    deity: { en: "Apas (cosmic waters)", ja: "アパス（宇宙の水）" },
    ruler: { en: "Venus", ja: "金星" },
    symbol: { en: "Fan / winnowing basket", ja: "扇／箕" },
    range: { en: "13°20' – 26°40' Sagittarius", ja: "射手座 13°20' – 26°40'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Fierce (Ugra)", ja: "激烈（ウグラ）" },
    description: {
      en: "Purva Ashadha is invincible conviction — preaching truth, purifying waters, and refusal to admit defeat prematurely. Apas cleanses; the fan separates grain from chaff in belief and relationship.",
      ja: "プルヴァ・アシャーダは不敗の確信 — 真理を説く、水による浄化、早急な敗北を認めない姿勢です。アパスは清め、扇は信念と関係から穀と糠を分けます。",
    },
    qualities: [
      { en: "Persuasive, idealistic, proud", ja: "説得力、理想主義、誇り" },
      { en: "Affinity for water and declamation", ja: "水と弁論への縁" },
    ],
  },
  {
    id: "uttara-ashadha",
    image: "/assets/uttara-ashadha.png",
    number: 21,
    name: { en: "Uttara Ashadha", ja: "ウッタラ・アシャーダ" },
    sanskrit: { en: "Uttara Aṣāḍhā", ja: "ウッタラ・アーシャーダー" },
    deity: { en: "Vishvadevas (universal gods)", ja: "ヴィシュヴァデーヴァ（普遍の神々）" },
    ruler: { en: "Sun", ja: "太陽" },
    symbol: { en: "Elephant tusk / planks of bed", ja: "象牙／寝台の板" },
    range: { en: "26°40' Sagittarius – 10°00' Capricorn", ja: "射手座 26°40' – 山羊座 10°00'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Fixed (Dhruva)", ja: "固定（ドルヴァ）" },
    description: {
      en: "Uttara Ashadha finalizes victory — enduring leadership, ethical permanence, and marriage to purpose. The elephant tusk symbolizes unbreakable commitment after the battle is won.",
      ja: "ウッタラ・アシャーダは勝利を完成 — 永続する指導、倫理の不変、目的との結婚です。象牙は戦いの後の壊れない誓いを象徴します。",
    },
    qualities: [
      { en: "Honorable, patient, statesmanlike", ja: "高潔、忍耐、政治家風" },
      { en: "Late but lasting success", ja: "遅れて来るが長続きする成功" },
    ],
  },
  {
    id: "shravana",
    image: "/assets/shravana.png",
    number: 22,
    name: { en: "Shravana", ja: "シュラヴァナ" },
    sanskrit: { en: "Śravaṇa", ja: "シュラヴァナ" },
    deity: { en: "Vishnu (preserver)", ja: "ヴィシュヌ（維持者）" },
    ruler: { en: "Moon", ja: "月" },
    symbol: { en: "Ear / three footprints", ja: "耳／三つの足跡" },
    range: { en: "10°00' – 23°20' Capricorn", ja: "山羊座 10°00' – 23°20'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Movable (Chara)", ja: "可動（チャラ）" },
    description: {
      en: "Shravana listens — oral tradition, learning by hearing, and dissemination of sacred knowledge. Vishnu's three steps measure the cosmos; natives often connect people through teaching, media, or travel.",
      ja: "シュラヴァナは聴く — 口承伝統、聞いて学ぶこと、聖なる知識の普及です。ヴィシュヌの三つの歩みは宇宙を測り、教え・メディア・旅で人をつなぐことが多いです。",
    },
    qualities: [
      { en: "Attentive, scholarly, well-traveled", ja: "注意深い、学究的、旅慣れ" },
      { en: "Fame through word and recording", ja: "言葉と記録による名声" },
    ],
  },
  {
    id: "dhanishta",
    image: "/assets/dhanishta.png",
    number: 23,
    name: { en: "Dhanishta", ja: "ダニシュタ" },
    sanskrit: { en: "Dhaniṣṭhā", ja: "ダニーシュター" },
    deity: { en: "Vasus (eight elemental gods)", ja: "ヴァス（八つの元素神）" },
    ruler: { en: "Mars", ja: "火星" },
    symbol: { en: "Drum / flute", ja: "太鼓／笛" },
    range: { en: "23°20' Capricorn – 6°40' Aquarius", ja: "山羊座 23°20' – 水瓶座 6°40'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Movable (Chara)", ja: "可動（チャラ）" },
    description: {
      en: "Dhanishta is wealth through rhythm — music, percussion, prosperity, and sometimes fame that arrives suddenly. The Vasus link material abundance with ethical use of resources.",
      ja: "ダニシュタはリズムによる富 — 音楽、打楽器、繁栄、時に突然の名声です。ヴァスは物質的豊かさと資源の倫理的使用を結びます。",
    },
    qualities: [
      { en: "Rhythmic, wealthy, sociable", ja: "リズミカル、裕福、社交的" },
      { en: "Adaptability in groups", ja: "集団での適応力" },
    ],
  },
  {
    id: "shatabhisha",
    image: "/assets/shatabhisha.png",
    number: 24,
    name: { en: "Shatabhisha", ja: "シャタビシャ" },
    sanskrit: { en: "Śatabhiṣā", ja: "シャタビシャー" },
    deity: { en: "Varuna (god of cosmic waters & law)", ja: "ヴァルナ（宇宙の水と法の神）" },
    ruler: { en: "Rahu", ja: "ラーフ" },
    symbol: { en: "Empty circle / hundred physicians", ja: "空の円／百の医師" },
    range: { en: "6°40' – 20°00' Aquarius", ja: "水瓶座 6°40' – 20°00'" },
    guna: { en: "Rajas", ja: "ラジャス" },
    nature: { en: "Movable (Chara)", ja: "可動（チャラ）" },
    description: {
      en: "Shatabhisha heals in solitude — alternative medicine, astronomy, and guarded secrets. Varuna sees all; natives may be reformers working at night or behind screens, restoring what conventional paths miss.",
      ja: "シャタビシャは孤独で癒す — 代替医学、天文学、守られた秘密です。ヴァルナはすべてを見通し、夜や画面の向こうで働き、常道が見逃すものを回復する改革者となり得ます。",
    },
    qualities: [
      { en: "Secretive, scientific, rebellious", ja: "秘密主義、科学的、反抗的" },
      { en: "Hundred cures through unconventional means", ja: "非伝統的手段による百の治療" },
    ],
  },
  {
    id: "purva-bhadrapada",
    image: "/assets/purva-bhadrapada.png",
    number: 25,
    name: { en: "Purva Bhadrapada", ja: "プルヴァ・バドラパダ" },
    sanskrit: { en: "Pūrva Bhādrapadā", ja: "プールヴァ・バードラパダー" },
    deity: { en: "Aja Ekapada (one-footed goat of fire)", ja: "アジャ・エーカパーダ（一足の火の山羊）" },
    ruler: { en: "Jupiter", ja: "木星" },
    symbol: { en: "Sword / two front legs of funeral cot", ja: "剣／葬儀台の前脚" },
    range: { en: "20°00' Aquarius – 3°20' Pisces", ja: "水瓶座 20°00' – 魚座 3°20'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Fierce (Ugra)", ja: "激烈（ウグラ）" },
    description: {
      en: "Purva Bhadrapada walks the edge — austere spirituality, fierce ideals, and transformation through fire. The funeral cot's front legs face the pyre; this mansion confronts mortality to extract higher meaning.",
      ja: "プルヴァ・バドラパダは境界を歩く — 厳しい霊性、激しい理想、火による変容です。葬儀台の前脚は火葬場に向き、この宿は死と向き合い高次の意味を抽出します。",
    },
    qualities: [
      { en: "Intense, mystical, austere", ja: "強烈、神秘的、禁欲的" },
      { en: "Paradoxical blend of zeal and calm", ja: "熱意と静けさの逆説的融合" },
    ],
  },
  {
    id: "uttara-bhadrapada",
    image: "/assets/uttara-bhadrapada.png",
    number: 26,
    name: { en: "Uttara Bhadrapada", ja: "ウッタラ・バドラパダ" },
    sanskrit: { en: "Uttara Bhādrapadā", ja: "ウッタラ・バードラパダー" },
    deity: { en: "Ahir Budhnya (serpent of the deep)", ja: "アヒル・ブドゥニャ（深淵の蛇）" },
    ruler: { en: "Saturn", ja: "土星" },
    symbol: { en: "Back legs of funeral cot / twins", ja: "葬儀台の後脚／双子" },
    range: { en: "3°20' – 16°40' Pisces", ja: "魚座 3°20' – 16°40'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Fixed (Dhruva)", ja: "固定（ドルヴァ）" },
    description: {
      en: "Uttara Bhadrapada stabilizes the mystical — wisdom after ordeal, counseling, and depth meditation. Ahir Budhnya guards cosmic ocean beds; natives often become anchors for others in crisis.",
      ja: "ウッタラ・バドラパダは神秘を安定 — 試練後の智慧、カウンセリング、深い瞑想です。アヒル・ブドゥニャは宇宙の海床を守り、危機で他者の錨となることが多いです。",
    },
    qualities: [
      { en: "Wise, calm, charitable", ja: "賢明、穏やか、慈善的" },
      { en: "Kundalini and dream depth", ja: "クンダリーニと夢の深さ" },
    ],
  },
  {
    id: "revati",
    image: "/assets/revati.png",
    number: 27,
    name: { en: "Revati", ja: "レヴァティ" },
    sanskrit: { en: "Revatī", ja: "レヴァティー" },
    deity: { en: "Pushan (nourisher, guide of souls)", ja: "プーシャン（養育者、魂の案内人）" },
    ruler: { en: "Mercury", ja: "水星" },
    symbol: { en: "Fish / drum for journey's end", ja: "魚／旅の終わりの太鼓" },
    range: { en: "16°40' – 30°00' Pisces", ja: "魚座 16°40' – 30°00'" },
    guna: { en: "Sattva", ja: "サットヴァ" },
    nature: { en: "Soft (Mridu)", ja: "柔和（ムリドゥ）" },
    description: {
      en: "Revati closes the Nakshatra cycle — safe travel, compassion, and escort to the next destination. Pushan protects flocks and roads; this mansion blesses endings that are also beginnings, especially journeys and animal care.",
      ja: "レヴァティはナクシャトラの輪を閉じる — 安全な旅、慈悲、次の目的地への案内です。プーシャンは群れと道を守り、この宿は終わりであり始まりでもある旅と動物のケアを祝福します。",
    },
    qualities: [
      { en: "Nurturing, imaginative, otherworldly", ja: "養育的、想像力豊か、この世離れ" },
      { en: "Prosperity through protection of the vulnerable", ja: "弱い者を守ることによる繁栄" },
    ],
  },
];
