import type { NakshatraEntry } from "./types";

export const nakshatrasIntro = {
  en: "The zodiac is divided into 27 Nakshatras of 13°20' each — one lunar day's travel of the Moon. Each mansion has a presiding deity, planetary lord, symbol, and temperament. Your Moon Nakshatra is among the most personal factors in Jyotish.", hi: "राशि चक्र को 13°20' के 27 नक्षत्रों में विभाजित किया गया है - चंद्रमा की एक चंद्र दिवस की यात्रा। प्रत्येक हवेली का एक इष्टदेव, ग्रह स्वामी, प्रतीक और स्वभाव होता है। आपका चंद्र नक्षत्र ज्योतिष में सबसे व्यक्तिगत कारकों में से एक है।", ja: "黄道は月の一日の移動距離である13°20'ずつ、27のナクシャトラに分かれます。各宿には守護神、支配星、象徴、気質があります。月のナクシャトラはジョーティッシュで最も個人的な要素のひとつです。", ko: "황도대는 각각 13°20'의 27개의 나크샤트라(달의 하루 이동 거리)로 나뉩니다. 각 저택에는 주재하는 신, 행성 영주, 상징, 기질이 있습니다. 귀하의 Moon Nakshatra는 Jyotish에서 가장 개인적인 요소 중 하나입니다.",
};

export const nakshatras: NakshatraEntry[] = [
  {
    id: "ashwini",
    number: 1,
    name: { en: "Ashwini", hi: "अश्विनी", ja: "アシュヴィニ", ko: "아쉬위니",},
    sanskrit: { en: "Aśvinī", hi: "अश्विनी", ja: "アシュヴィニー", ko: "아스비니",},
    deity: { en: "Ashwini Kumaras (celestial physicians)", hi: "अश्विनी कुमार (आकाशीय चिकित्सक)", ja: "アシュヴィニ・クマーラ（天の医師）", ko: "Ashwini Kumaras (천상의 의사)",},
    ruler: { en: "Ketu", hi: "केतु", ja: "ケートゥ", ko: "케투",},
    symbol: { en: "Horse's head", hi: "घोड़े का सिर", ja: "馬の頭", ko: "말의 머리",},
    range: { en: "0°00' – 13°20' Aries", hi: "0°00' - 13°20' मेष", ja: "牡羊座 0°00' – 13°20'", ko: "0°00' – 13°20' 양자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Light / swift (Kshipra)", hi: "प्रकाश/तेज़ (क्षिप्रा)", ja: "軽速（クシプラ）", ko: "경/스위프트(Kshipra)",},
    description: {
      en: "The first mansion inaugurates the zodiac with healing speed and new beginnings. Ashwini natives often move quickly, initiate projects boldly, and carry an instinct for restoration — medical, emotional, or spiritual.", hi: "पहला हवेली उपचार की गति और नई शुरुआत के साथ राशि चक्र का उद्घाटन करता है। अश्विनी मूल निवासी अक्सर तेजी से आगे बढ़ते हैं, साहसपूर्वक परियोजनाएं शुरू करते हैं, और चिकित्सा, भावनात्मक या आध्यात्मिक - बहाली की प्रवृत्ति रखते हैं।", ja: "最初の宿は癒しと速さ、新しい始まりで黄道を開きます。アシュヴィニの人は行動が速く、大胆にプロジェクトを始め、医療・感情・霊的な回復の本能を持つことが多いです。", ko: "첫 번째 저택은 치유 속도와 새로운 시작으로 황도대를 시작합니다. Ashwini 원주민은 종종 빠르게 움직이고, 대담하게 프로젝트를 시작하며, 의학적, 감정적, 영적인 회복 본능을 갖고 있습니다.",
    },
    qualities: [
      { en: "Pioneering, athletic, impatient", hi: "अग्रणी, पुष्ट, अधीर", ja: "先駆的、運動的、せっかち", ko: "선구적, 운동능력이 뛰어나고 참을성이 없음",},
      { en: "Affinity for medicine, horses, emergencies", hi: "चिकित्सा, घोड़ों, आपात्कालीन स्थितियों के प्रति आकर्षण", ja: "医学、馬、緊急事態との縁", ko: "약, 말, 응급 상황에 대한 친화력",},
    ],
  },
  {
    id: "bharani",
    number: 2,
    name: { en: "Bharani", hi: "भरनी", ja: "バラニ", ko: "바라니어",},
    sanskrit: { en: "Bharaṇī", hi: "भरनी", ja: "バラニー", ko: "바라니",},
    deity: { en: "Yama (lord of death & dharma)", hi: "यम (मृत्यु और धर्म के स्वामी)", ja: "ヤマ（死とダルマの神）", ko: "야마(죽음과 달마의 신)",},
    ruler: { en: "Venus", hi: "शुक्र", ja: "金星", ko: "금성",},
    symbol: { en: "Yoni (womb)", hi: "योनि (गर्भ)", ja: "ヨニ（子宮）", ko: "요니(자궁)",},
    range: { en: "13°20' – 26°40' Aries", hi: "13°20' - 26°40' मेष", ja: "牡羊座 13°20' – 26°40'", ko: "13°20' – ​​26°40' 양자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Fierce (Ugra)", hi: "भयंकर (उग्रा)", ja: "激烈（ウグラ）", ko: "맹렬한 (우그라)",},
    description: {
      en: "Bharani holds the tension of birth and death — creativity through constraint. It governs bearing responsibility, sexual vitality, and moral choices. There is immense creative power when ethically directed.", hi: "भरणी जन्म और मृत्यु के तनाव को मानती है - रचनात्मकता को बाधा के माध्यम से। यह जिम्मेदारी वहन करने, यौन जीवन शक्ति और नैतिक विकल्पों को नियंत्रित करता है। नैतिक रूप से निर्देशित होने पर अपार रचनात्मक शक्ति होती है।", ja: "バラニは生と死の緊張を抱え — 制約を通じた創造です。責任、性的活力、道徳的选择を司ります。倫理に沿って向けられると巨大な創造力があります。", ko: "Bharani는 탄생과 죽음의 긴장, 즉 제약을 통한 창의성을 유지합니다. 이는 책임감, 성적 활력, 도덕적 선택을 관장합니다. 윤리적으로 지도할 때 엄청난 창의력이 발휘됩니다.",
    },
    qualities: [
      { en: "Intense, sensual, transformative", hi: "तीव्र, कामुक, परिवर्तनकारी", ja: "強烈、官能的、変容的", ko: "강렬함, 감각적, 변형적",},
      { en: "Tests around restraint and desire", hi: "संयम और इच्छा के आसपास परीक्षण", ja: "抑制と欲望の試練", ko: "구속과 욕망에 대한 테스트",},
    ],
  },
  {
    id: "krittika",
    number: 3,
    name: { en: "Krittika", hi: "कृत्तिका", ja: "クリッティカ", ko: "크리티카",},
    sanskrit: { en: "Kṛttikā", hi: "कृत्तिका", ja: "クリッティカー", ko: "크리티카",},
    deity: { en: "Agni (fire god)", hi: "अग्नि (अग्नि देवता)", ja: "アグニ（火の神）", ko: "아그니(불의 신)",},
    ruler: { en: "Sun", hi: "सूरज", ja: "太陽", ko: "해",},
    symbol: { en: "Razor / flame", hi: "उस्तरा/लौ", ja: "剃刀／炎", ko: "면도기/불꽃",},
    range: { en: "26°40' Aries – 10°00' Taurus", hi: "26°40' मेष - 10°00' वृषभ", ja: "牡羊座 26°40' – 牡牛座 10°00'", ko: "26°40' 양자리 – 10°00' 황소자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Mixed", hi: "मिश्रित", ja: "混合", ko: "혼합",},
    description: {
      en: "Krittika purifies through fire — sharp criticism, cutting clarity, and nurturing warmth (like a cooking flame). It spans the aggressive end of Aries and stable Taurus, blending courage with sustenance.", hi: "कृत्तिका आग के माध्यम से शुद्ध करती है - तीखी आलोचना, स्पष्टता में कटौती, और गर्मी का पोषण (खाना पकाने की लौ की तरह)। यह मेष और स्थिर वृषभ के आक्रामक अंत तक फैला है, जिसमें जीविका के साथ साहस का मिश्रण है।", ja: "クリッティカは火による浄化 — 鋭い批判、切断する明晰さ、そして育む温かさ（料理の炎のように）です。牡羊の攻撃性と牡牛の安定をまたぎ、勇気と養育を溶け合わせます。", ko: "Krittika는 불을 통해 정화합니다. 예리한 비판, 날카로운 명확성, 따뜻함(요리용 불꽃처럼)을 키워줍니다. 그것은 양자리의 공격적인 끝과 안정된 황소자리에 걸쳐 용기와 생계를 혼합합니다.",
    },
    qualities: [
      { en: "Leadership, candor, protective", hi: "नेतृत्व, स्पष्टवादिता, सुरक्षात्मक", ja: "指導力、率直さ、保護的", ko: "리더십, 솔직함, 보호",},
      { en: "Careers in cooking, military, criticism", hi: "खाना पकाने, सेना, आलोचना में करियर", ja: "料理、軍事、批評の職", ko: "요리, 군사, 비평 분야의 경력",},
    ],
  },
  {
    id: "rohini",
    number: 4,
    name: { en: "Rohini", hi: "रोहिणी", ja: "ローヒニ", ko: "로히니",},
    sanskrit: { en: "Rohiṇī", hi: "रोहिणी", ja: "ローヒニー", ko: "로히니",},
    deity: { en: "Brahma / Prajapati (creator)", hi: "ब्रह्मा/प्रजापति (निर्माता)", ja: "ブラフマ／プラジャーパティ（創造神）", ko: "브라흐마/프라자파티(창조자)",},
    ruler: { en: "Moon", hi: "चंद्रमा", ja: "月", ko: "달",},
    symbol: { en: "Chariot / ox cart", hi: "रथ/बैलगाड़ी", ja: "戦車／牛車", ko: "마차/소 수레",},
    range: { en: "10°00' – 23°20' Taurus", hi: "10°00' - 23°20' वृषभ", ja: "牡牛座 10°00' – 23°20'", ko: "10°00' – 23°20' 황소자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Fixed (Dhruva)", hi: "स्थिर (ध्रुव)", ja: "固定（ドルヴァ）", ko: "고정 (드루바)",},
    description: {
      en: "Rohini is the Moon's favorite mansion — beauty, fertility, growth, and sensual abundance. Krishna was born under Rohini. It signifies cultivation: arts, agriculture, charisma, and material blossoming.", hi: "रोहिणी चंद्रमा की पसंदीदा हवेली है - सुंदरता, उर्वरता, विकास और कामुक प्रचुरता। कृष्ण का जन्म रोहिणी के अंतर्गत हुआ था। यह खेती का प्रतीक है: कला, कृषि, करिश्मा, और सामग्री का खिलना।", ja: "ローヒニは月の最愛の宿 — 美、豊穣、成長、官能的な豊かさです。クリシュナはローヒニ生まれとされます。芸術、農業、カリスマ、物質的開花を象徴します。", ko: "Rohini는 달이 가장 좋아하는 저택입니다. 아름다움, 다산, 성장, 관능적인 풍요로움이 그것입니다. 크리슈나는 로히니 밑에서 태어났다. 이는 예술, 농업, 카리스마, 물질의 꽃피움 등 재배를 의미합니다.",
    },
    qualities: [
      { en: "Magnetic, artistic, luxurious", hi: "चुंबकीय, कलात्मक, विलासितापूर्ण", ja: "魅力的、芸術的、豪華", ko: "자기적이고 예술적이며 고급스러운",},
      { en: "Jealousy when possessiveness is unchecked", hi: "ईर्ष्या जब अधिकारिता अनियंत्रित होती है", ja: "所有欲が過ぎると嫉妬", ko: "소유욕이 확인되지 않을 때의 질투",},
    ],
  },
  {
    id: "mrigashira",
    number: 5,
    name: { en: "Mrigashira", hi: "मृगशिरा", ja: "ムリガシーラ", ko: "므리가시라",},
    sanskrit: { en: "Mṛgaśira", hi: "मृगशिरा", ja: "ムリガシーラ", ko: "음가시라",},
    deity: { en: "Soma (Moon god)", hi: "सोम (चन्द्र देवता)", ja: "ソーマ（月の神）", ko: "소마(달의 신)",},
    ruler: { en: "Mars", hi: "मंगल ग्रह", ja: "火星", ko: "화성",},
    symbol: { en: "Deer's head", hi: "हिरण का सिर", ja: "鹿の頭", ko: "사슴의 머리",},
    range: { en: "23°20' Taurus – 6°40' Gemini", hi: "23°20' वृषभ - 6°40' मिथुन", ja: "牡牛座 23°20' – 双子座 6°40'", ko: "23°20' 황소자리 – 6°40' 쌍둥이자리",},
    guna: { en: "Tamas", hi: "तमस्", ja: "タマス", ko: "타마스",},
    nature: { en: "Soft (Mridu)", hi: "शीतल (मृदु)", ja: "柔和（ムリドゥ）", ko: "소프트 (Mridu)",},
    description: {
      en: "Mrigashira is the searching deer — gentle curiosity, wandering inquiry, and pursuit of ideal experience. It blends Taurean stability with Gemini restlessness, producing poets, researchers, and wanderers.", hi: "मृगशिरा खोजी हिरण है - कोमल जिज्ञासा, भटकती जिज्ञासा और आदर्श अनुभव की खोज। यह वृषभ राशि की स्थिरता को मिथुन राशि की बेचैनी के साथ मिश्रित करता है, जिससे कवि, शोधकर्ता और घुमक्कड़ पैदा होते हैं।", ja: "ムリガシーラは探求する鹿 — 穏やかな好奇心、放浪する問い、理想体験の追求です。牡牛の安定と双子の落ち着きのなさを溶かし、詩人、研究者、放浪者を生みます。", ko: "Mrigashira는 부드러운 호기심, 방황하는 탐구, 이상적인 경험 추구를 추구하는 사슴입니다. 황소자리의 안정감과 쌍둥이자리의 불안함을 혼합하여 시인, 연구자, 방랑자를 배출합니다.",
    },
    qualities: [
      { en: "Inquisitive, romantic, elusive", hi: "जिज्ञासु, रोमांटिक, मायावी", ja: "好奇深い、ロマンチック、捉えどころのない", ko: "호기심 많고, 낭만적이고, 이해하기 어려운",},
      { en: "Love of travel and subtle beauty", hi: "यात्रा और सूक्ष्म सौंदर्य का प्यार", ja: "旅と繊細な美への愛", ko: "여행에 대한 사랑과 미묘한 아름다움",},
    ],
  },
  {
    id: "ardra",
    number: 6,
    name: { en: "Ardra", hi: "आर्द्रा", ja: "アールドラ", ko: "아르드라",},
    sanskrit: { en: "Ārdrā", hi: "आर्द्रा", ja: "アードラー", ko: "아르드라",},
    deity: { en: "Rudra (storm form of Shiva)", hi: "रुद्र (शिव का तूफान रूप)", ja: "ルドラ（シヴァの嵐の形）", ko: "루드라(시바의 폭풍형)",},
    ruler: { en: "Rahu", hi: "राहु", ja: "ラーフ", ko: "라후",},
    symbol: { en: "Teardrop / diamond", hi: "अश्रु/हीरा", ja: "涙／ダイヤモンド", ko: "티어드롭/다이아몬드",},
    range: { en: "6°40' – 20°00' Gemini", hi: "6°40' - 20°00' मिथुन", ja: "双子座 6°40' – 20°00'", ko: "6°40' – 20°00' 쌍둥이자리",},
    guna: { en: "Tamas", hi: "तमस्", ja: "タマス", ko: "타마스",},
    nature: { en: "Sharp (Tikshna)", hi: "तीक्ष्ण (तीक्ष्ण)", ja: "鋭利（ティクシュナ）", ko: "샤프(티크슈나)",},
    description: {
      en: "Ardra brings storms that clear the air — destruction of the old, emotional catharsis, and intellectual breakthrough. Pain here often precedes renewal. Rudra's energy is wild but purifying.", hi: "आर्द्रा तूफान लाता है जो हवा को साफ़ कर देता है - पुरानी, ​​भावनात्मक रेचन और बौद्धिक सफलता का विनाश। यहां दर्द अक्सर नवीनीकरण से पहले होता है। रुद्र की ऊर्जा जंगली लेकिन शुद्ध करने वाली है।", ja: "アールドラは空気を澄ます嵐 — 古いものの破壊、感情の浄化、知的突破をもたらします。痛みの後に更新が来ることが多い、ルドラの荒々しくも浄化するエネルギーです。", ko: "Ardra는 공기를 맑게 하는 폭풍을 가져옵니다. 즉, 오래된 정서적 카타르시스를 파괴하고 지적 돌파구를 마련합니다. 여기서 고통은 종종 갱신에 앞서 발생합니다. 루드라의 에너지는 거칠지만 정화적입니다.",
    },
    qualities: [
      { en: "Intense mind, reformer, stormy emotions", hi: "तीव्र बुद्धि, सुधारक, तूफ़ानी भावनाएँ", ja: "強い精神、改革者、嵐のような感情", ko: "강렬한 마음, 개혁가, 폭풍우가 치는 감정",},
      { en: "Skill in technology and analysis", hi: "प्रौद्योगिकी और विश्लेषण में कौशल", ja: "技術と分析の才能", ko: "기술 및 분석 능력",},
    ],
  },
  {
    id: "punarvasu",
    number: 7,
    name: { en: "Punarvasu", hi: "पुनर्वसु", ja: "プナルヴァス", ko: "푸나르바수",},
    sanskrit: { en: "Punarvasu", hi: "पुनर्वसु", ja: "プナルヴァス", ko: "푸나르바수",},
    deity: { en: "Aditi (mother of gods)", hi: "अदिति (देवताओं की माता)", ja: "アディティ（神々の母）", ko: "아디티(신들의 어머니)",},
    ruler: { en: "Jupiter", hi: "बृहस्पति", ja: "木星", ko: "목성",},
    symbol: { en: "Quiver of arrows / house", hi: "बाणों का तरकश/घर", ja: "矢筒／家", ko: "화살통 / 집",},
    range: { en: "20°00' Gemini – 3°20' Cancer", hi: "20°00' मिथुन - 3°20' कर्क", ja: "双子座 20°00' – 蟹座 3°20'", ko: "20°00' 쌍둥이자리 – 3°20' 게자리",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Movable (Chara)", hi: "चल (चर)", ja: "可動（チャラ）", ko: "이동식(차라)",},
    description: {
      en: "Punarvasu means \"good again\" — return, restoration, and optimistic renewal after loss. Aditi's boundless motherhood grants shelter and second chances. It favors teachers, repeat journeys, and recovery.", hi: "पुनर्वसु का अर्थ है \"फिर से अच्छा\" - हानि के बाद वापसी, पुनर्स्थापन और आशावादी नवीनीकरण। अदिति का असीम मातृत्व आश्रय और दूसरा मौका देता है। यह शिक्षकों, बार-बार यात्रा करने और पुनर्प्राप्ति का पक्ष लेता है।", ja: "プナルヴァスは「再び良い」— 喪失後の回帰、回復、楽観的な更新です。アディティの限りない母性が庇護と二度目の機会を与えます。教師、再訪の旅、回復に縁があります。", ko: "푸나르바수(Punarvasu)는 \"다시 좋은 것\"을 의미합니다. 즉, 손실 후 반환, 복원 및 낙관적인 갱신을 의미합니다. 아디티의 무한한 모성애는 피난처와 두 번째 기회를 제공합니다. 교사, 반복 여행 및 회복에 유리합니다.",
    },
    qualities: [
      { en: "Hopeful, forgiving, domestic", hi: "आशावान, क्षमाशील, घरेलू", ja: "希望に満ち、許す、家庭的", ko: "희망적이고 용서하며 가정적인",},
      { en: "Cycles of departure and return", hi: "प्रस्थान और वापसी का चक्र", ja: "離れると戻るサイクル", ko: "출발과 귀국의 주기",},
    ],
  },
  {
    id: "pushya",
    number: 8,
    name: { en: "Pushya", hi: "पुष्य", ja: "プシュヤ", ko: "푸샤",},
    sanskrit: { en: "Puṣya", hi: "पुष्य", ja: "プシュヤ", ko: "푸샤",},
    deity: { en: "Brihaspati (Jupiter as priest)", hi: "बृहस्पति (पुजारी के रूप में बृहस्पति)", ja: "ブリハスパティ（祭司としての木星）", ko: "브리하스파티(신부로서의 목성)",},
    ruler: { en: "Saturn", hi: "शनि ग्रह", ja: "土星", ko: "토성",},
    symbol: { en: "Flower / udder", hi: "फूल / थन", ja: "花／乳房", ko: "꽃 / 젖통",},
    range: { en: "3°20' – 16°40' Cancer", hi: "3°20' - 16°40' कर्क", ja: "蟹座 3°20' – 16°40'", ko: "3°20' – ​​16°40' 암",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Light / swift (Kshipra)", hi: "प्रकाश/तेज़ (क्षिप्रा)", ja: "軽速（クシプラ）", ko: "경/스위프트(Kshipra)",},
    description: {
      en: "Pushya is among the most auspicious Nakshatras — nourishment, ritual correctness, and spiritual prosperity. Like milk from the cosmic udder, it feeds growth through discipline and care.", hi: "पुष्य सबसे शुभ नक्षत्रों में से एक है - पोषण, अनुष्ठान शुद्धता और आध्यात्मिक समृद्धि। ब्रह्मांडीय थन से निकले दूध की तरह, यह अनुशासन और देखभाल के माध्यम से विकास को बढ़ावा देता है।", ja: "プシュヤは最も吉祥なナクシャトラのひとつ — 養育、儀礼の正しさ、霊的繁栄です。宇宙の乳房からの乳のように、規律とケアを通じて成長を育みます。", ko: "푸샤(Pushya)는 가장 상서로운 나크샤트라(자양분, 의식의 정확성, 영적 번영) 중 하나입니다. 우주 젖통에서 나오는 우유처럼 규율과 보살핌을 통해 성장을 촉진합니다.",
    },
    qualities: [
      { en: "Devoted, nourishing, orthodox", hi: "समर्पित, पोषक, रूढ़िवादी", ja: "献身的、養う、正統的", ko: "헌신적이고 영양이 풍부하며 정통적입니다.",},
      { en: "Excellence in counseling and food", hi: "परामर्श एवं भोजन में उत्कृष्टता", ja: "カウンセリングと食に優れる", ko: "상담과 음식의 우수성",},
    ],
  },
  {
    id: "ashlesha",
    number: 9,
    name: { en: "Ashlesha", hi: "आश्लेषा", ja: "アシュレシャ", ko: "아슬레샤",},
    sanskrit: { en: "Āśleṣā", hi: "आश्लेषा", ja: "アーシュレーシャー", ko: "아슬레샤",},
    deity: { en: "Nagas (serpent deities)", hi: "नागा (नाग देवता)", ja: "ナーガ（蛇神）", ko: "나가(뱀의 신)",},
    ruler: { en: "Mercury", hi: "बुध", ja: "水星", ko: "수성",},
    symbol: { en: "Coiled serpent", hi: "कुंडलित सर्प", ja: "巻きつく蛇", ko: "똬리를 튼 뱀",},
    range: { en: "16°40' – 30°00' Cancer", hi: "16°40' – 30°00' कर्क", ja: "蟹座 16°40' – 30°00'", ko: "16°40' – 30°00' 암",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Sharp (Tikshna)", hi: "तीक्ष्ण (तीक्ष्ण)", ja: "鋭利（ティクシュナ）", ko: "샤프(티크슈나)",},
    description: {
      en: "Ashlesha entwines — hypnotic influence, psychological depth, and kundalini symbolism. Nagas guard hidden treasure. Mastery yields powerful healing; misuse slides into manipulation or venomous speech.", hi: "आश्लेषा सम्मोहक प्रभाव, मनोवैज्ञानिक गहराई और कुंडलिनी प्रतीकवाद को जोड़ती है। नागा छिपे हुए खजाने की रक्षा करते हैं। महारत से शक्तिशाली उपचार मिलता है; दुरुपयोग हेरफेर या ज़हरीले भाषण में बदल जाता है।", ja: "アシュレシャは絡みつく — 催眠的影響、心理の深さ、クンダリーニの象徴です。ナーガは隠された宝を守ります。熟達は強力な癒しをもたらし、誤用は操る言葉や毒へと滑ります。", ko: "Ashlesha는 최면 영향, 심리적 깊이 및 쿤달리니 상징을 엮습니다. Nagas는 숨겨진 보물을 보호합니다. 숙달은 강력한 치유를 가져옵니다. 오용은 조작이나 악의적인 말로 이어집니다.",
    },
    qualities: [
      { en: "Penetrating intellect, mystical", hi: "मर्मज्ञ बुद्धि, रहस्यमय", ja: "貫く知性、神秘的", ko: "관통하는 지성, 신비로운",},
      { en: "Boundaries around toxic entanglement", hi: "विषैले उलझाव के चारों ओर की सीमाएँ", ja: "有毒な絡みへの境界", ko: "독성 얽힘 주변의 경계",},
    ],
  },
  {
    id: "magha",
    number: 10,
    name: { en: "Magha", hi: "माघ", ja: "マガ", ko: "마가",},
    sanskrit: { en: "Maghā", hi: "माघ", ja: "マガー", ko: "마가",},
    deity: { en: "Pitris (ancestral fathers)", hi: "पितृ (पूर्वज पिता)", ja: "ピトリ（祖先の父）", ko: "피트리스(조상)",},
    ruler: { en: "Ketu", hi: "केतु", ja: "ケートゥ", ko: "케투",},
    symbol: { en: "Royal throne", hi: "शाही सिंहासन", ja: "王座", ko: "왕실 왕좌",},
    range: { en: "0°00' – 13°20' Leo", hi: "0°00' - 13°20' सिंह", ja: "獅子座 0°00' – 13°20'", ko: "0°00' – 13°20' 사자자리",},
    guna: { en: "Tamas", hi: "तमस्", ja: "タマス", ko: "타마스",},
    nature: { en: "Fierce (Ugra)", hi: "भयंकर (उग्रा)", ja: "激烈（ウグラ）", ko: "맹렬한 (우그라)",},
    description: {
      en: "Magha connects to lineage — ancestral pride, royal bearing, and duty toward those who came before. Ceremonies honoring ancestors resonate strongly. Ego must serve legacy, not vanity.", hi: "माघ वंश से जुड़ता है - पैतृक गौरव, शाही व्यवहार और जो पहले आए थे उनके प्रति कर्तव्य। पूर्वजों का सम्मान करने वाले समारोह दृढ़ता से गूंजते हैं। अहंकार को विरासत की सेवा करनी चाहिए, घमंड की नहीं।", ja: "マガは血統につながる — 祖先の誇り、王の風格、先人への義務です。祖先を敬う儀式が強く響きます。エゴは虚栄ではなく遺産に仕える必要があります。", ko: "마가는 조상의 자부심, 왕족의 태도, 이전에 온 사람들에 대한 의무 등 혈통과 연결됩니다. 조상을 기리는 의식은 강한 울림을 줍니다. 자아는 허영이 아닌 유산을 섬겨야 합니다.",
    },
    qualities: [
      { en: "Regal, traditional, authoritative", hi: "राजसी, पारंपरिक, आधिकारिक", ja: "王者の風格、伝統的、権威的", ko: "당당함, 전통적, 권위적",},
      { en: "Strong sense of ceremony", hi: "समारोह की प्रबल भावना", ja: "儀式への強い感覚", ko: "행사의 느낌이 강하다",},
    ],
  },
  {
    id: "purva-phalguni",
    number: 11,
    name: { en: "Purva Phalguni", hi: "पूर्वा फाल्गुनी", ja: "プルヴァ・パールグニ", ko: "푸르바 팔구니",},
    sanskrit: { en: "Pūrva Phalgunī", hi: "पूर्वा फाल्गुनी", ja: "プールヴァ・パールグニー", ko: "푸르바 팔구니",},
    deity: { en: "Bhaga (god of delight)", hi: "भग (प्रसन्नता के देवता)", ja: "バガ（喜びの神）", ko: "바가(기쁨의 신)",},
    ruler: { en: "Venus", hi: "शुक्र", ja: "金星", ko: "금성",},
    symbol: { en: "Hammock / front legs of bed", hi: "झूला/बिस्तर के अगले पैर", ja: "ハンモック／寝台の前脚", ko: "해먹/침대 앞다리",},
    range: { en: "13°20' – 26°40' Leo", hi: "13°20' - 26°40' सिंह", ja: "獅子座 13°20' – 26°40'", ko: "13°20' – ​​26°40' 레오",},
    guna: { en: "Tamas", hi: "तमस्", ja: "タマス", ko: "타마스",},
    nature: { en: "Fierce (Ugra)", hi: "भयंकर (उग्रा)", ja: "激烈（ウグラ）", ko: "맹렬한 (우그라)",},
    description: {
      en: "Purva Phalguni celebrates union — romance, relaxation, creative play, and the spark before commitment. Bhaga blesses marital joy and leisure. Balance pleasure with purpose to avoid indulgence.", hi: "पूर्वा फाल्गुनी मिलन का जश्न मनाती है - रोमांस, विश्राम, रचनात्मक खेल और प्रतिबद्धता से पहले की चिंगारी। भागा वैवाहिक आनंद और आराम का आशीर्वाद देता है। भोग से बचने के उद्देश्य से आनंद को संतुलित करें।", ja: "プルヴァ・パールグニは結合を祝う — ロマンス、休息、創造的遊び、誓いの前の火花です。バガは婚姻の喜びと余暇を祝福します。快楽と目的のバランスが大切です。", ko: "Purva Phalguni는 로맨스, 휴식, 창의적인 놀이, 약속 전의 불꽃 등 결합을 기념합니다. Bhaga는 결혼 생활의 기쁨과 여가를 축복합니다. 방종을 피하기 위해 목적과 즐거움의 균형을 맞추십시오.",
    },
    qualities: [
      { en: "Charismatic, pleasure-loving, artistic", hi: "करिश्माई, आनंद-प्रेमी, कलात्मक", ja: "カリスマ、快楽を愛する、芸術的", ko: "카리스마 있고 즐거움을 좋아하며 예술적입니다.",},
      { en: "Creative performance and celebration", hi: "रचनात्मक प्रदर्शन और उत्सव", ja: "創造的な表現と祝祭", ko: "창의적인 공연과 축하",},
    ],
  },
  {
    id: "uttara-phalguni",
    number: 12,
    name: { en: "Uttara Phalguni", hi: "उत्तरा फाल्गुनी", ja: "ウッタラ・パールグニ", ko: "우타라 팔구니",},
    sanskrit: { en: "Uttara Phalgunī", hi: "उत्तरा फाल्गुनी", ja: "ウッタラ・パールグニー", ko: "우타라 팔구니",},
    deity: { en: "Aryaman (noble patron of contracts)", hi: "आर्यमन (अनुबंधों के महान संरक्षक)", ja: "アリヤマン（契約の高貴な守護神）", ko: "Aryaman (계약의 고귀한 후원자)",},
    ruler: { en: "Sun", hi: "सूरज", ja: "太陽", ko: "해",},
    symbol: { en: "Back legs of bed", hi: "बिस्तर के पिछले पैर", ja: "寝台の後脚", ko: "침대 뒷다리",},
    range: { en: "26°40' Leo – 10°00' Virgo", hi: "26°40' सिंह - 10°00' कन्या", ja: "獅子座 26°40' – 乙女座 10°00'", ko: "26°40' 사자자리 – 10°00' 처녀자리",},
    guna: { en: "Tamas", hi: "तमस्", ja: "タマス", ko: "타마스",},
    nature: { en: "Fixed (Dhruva)", hi: "स्थिर (ध्रुव)", ja: "固定（ドルヴァ）", ko: "고정 (드루바)",},
    description: {
      en: "Uttara Phalguni formalizes what Purva begins — marriage contracts, patronage, steady friendship, and lasting agreements. Aryaman governs social bonds backed by honor.", hi: "उत्तरा फाल्गुनी ने पूर्वा की शुरुआत को औपचारिक रूप दिया - विवाह अनुबंध, संरक्षण, स्थिर मित्रता और स्थायी समझौते। आर्यमन सम्मान द्वारा समर्थित सामाजिक बंधनों को नियंत्रित करता है।", ja: "ウッタラ・パールグニはプルヴァが始めたことを形式化 — 結婚契約、後援、安定した友情、永続する合意です。アリヤマンは名誉に支えられた社会的絆を司ります。", ko: "Uttara Phalguni는 Purva가 시작하는 것, 즉 결혼 계약, 후원, 꾸준한 우정, 지속적인 계약을 공식화합니다. Aryaman은 명예로 뒷받침되는 사회적 유대를 관리합니다.",
    },
    qualities: [
      { en: "Loyal, generous, organized", hi: "वफादार, उदार, संगठित", ja: "忠実、寛大、組織的", ko: "충성스럽고 관대하며 조직적입니다.",},
      { en: "Success through partnerships", hi: "साझेदारी से सफलता", ja: "パートナーシップによる成功", ko: "파트너십을 통한 성공",},
    ],
  },
  {
    id: "hasta",
    number: 13,
    name: { en: "Hasta", hi: "हस्त", ja: "ハスタ", ko: "하스타",},
    sanskrit: { en: "Hasta", hi: "हस्त", ja: "ハスタ", ko: "하스타",},
    deity: { en: "Savitar (Sun as giver of life)", hi: "सवितार (सूर्य जीवन दाता के रूप में)", ja: "サヴィタール（生命を与える太陽）", ko: "사비타(생명을 주는 태양)",},
    ruler: { en: "Moon", hi: "चंद्रमा", ja: "月", ko: "달",},
    symbol: { en: "Open hand / fist", hi: "खुला हाथ/मुट्ठी", ja: "開いた手／拳", ko: "열린 손 / 주먹",},
    range: { en: "10°00' – 23°20' Virgo", hi: "10°00' – 23°20' कन्या", ja: "乙女座 10°00' – 23°20'", ko: "10°00' – 23°20' 처녀자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Light / swift (Kshipra)", hi: "प्रकाश/तेज़ (क्षिप्रा)", ja: "軽速（クシプラ）", ko: "경/스위프트(Kshipra)",},
    description: {
      en: "Hasta is the craftsman constellation — skillful hands, witty speech, and capacity to grasp opportunity literally and figuratively. Savitar's creative spark favors artisans, healers, and magicians of detail.", hi: "हस्त शिल्पकार नक्षत्र है - कुशल हाथ, मजाकिया भाषण, और अवसर को शाब्दिक और आलंकारिक रूप से समझने की क्षमता। सवितार की रचनात्मक चिंगारी कारीगरों, चिकित्सकों और विस्तार के जादूगरों का पक्ष लेती है।", ja: "ハスタは職人の星座 — 巧みな手、機知に富む言葉、文字通り・比喩的に機会を掴む力です。サヴィタールの創造の火花は職人、癒し手、細部の魔術師を助けます。", ko: "Hasta는 숙련된 손, 재치 있는 말, 문자 그대로나 비유적으로 기회를 파악하는 능력을 갖춘 장인 별자리입니다. Savitar의 창의적인 불꽃은 장인, 치료사, 세부 마술사를 선호합니다.",
    },
    qualities: [
      { en: "Dexterous, humorous, service-minded", hi: "निपुण, विनोदी, सेवाभावी", ja: "器用、ユーモラス、奉仕の心", ko: "능숙하고 유머러스하며 서비스 정신이 뛰어남",},
      { en: "Mastery through practice", hi: "अभ्यास के माध्यम से निपुणता", ja: "実践による熟達", ko: "연습을 통한 숙달",},
    ],
  },
  {
    id: "chitra",
    number: 14,
    name: { en: "Chitra", hi: "चित्रा", ja: "チトラ", ko: "치트라",},
    sanskrit: { en: "Citrā", hi: "सिट्रा", ja: "チトラー", ko: "시트라",},
    deity: { en: "Vishvakarma (divine architect)", hi: "विश्वकर्मा (दिव्य वास्तुकार)", ja: "ヴィシュヴァカルマ（天の建築家）", ko: "비슈바카르마(신성한 건축가)",},
    ruler: { en: "Mars", hi: "मंगल ग्रह", ja: "火星", ko: "화성",},
    symbol: { en: "Bright jewel / pearl", hi: "चमकीला गहना/मोती", ja: "輝く宝石／真珠", ko: "빛나는 보석/진주",},
    range: { en: "23°20' Virgo – 6°40' Libra", hi: "23°20' कन्या - 6°40' तुला", ja: "乙女座 23°20' – 天秤座 6°40'", ko: "23°20' 처녀자리 – 6°40' 천칭자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Soft (Mridu)", hi: "शीतल (मृदु)", ja: "柔和（ムリドゥ）", ko: "소프트 (Mridu)",},
    description: {
      en: "Chitra builds beauty with structure — design, architecture, fashion, and charisma that shines like a cut gem. Vishvakarma's influence demands both vision and technical precision.", hi: "चित्रा संरचना - डिज़ाइन, वास्तुकला, फैशन और करिश्मा के साथ सुंदरता का निर्माण करती है जो कटे हुए रत्न की तरह चमकती है। विश्वकर्मा का प्रभाव दृष्टि और तकनीकी सटीकता दोनों की मांग करता है।", ja: "チトラは構造で美を築く — デザイン、建築、ファッション、切り子のように輝くカリスマです。ヴィシュヴァカルマの影響はビジョンと技術的精密さの両方を求めます。", ko: "Chitra는 디자인, 건축, 패션, 보석처럼 빛나는 카리스마 등 구조를 통해 아름다움을 구축합니다. Vishvakarma의 영향력은 비전과 기술적 정확성을 모두 요구합니다.",
    },
    qualities: [
      { en: "Elegant, ambitious, visually gifted", hi: "सुंदर, महत्वाकांक्षी, देखने में प्रतिभाशाली", ja: "優雅、野心家、視覚的才能", ko: "우아함, 야망, 시각적 재능",},
      { en: "Attraction to glamour and order", hi: "ग्लैमर और व्यवस्था के प्रति आकर्षण", ja: "華やかさと秩序への魅力", ko: "화려함과 질서에 대한 매력",},
    ],
  },
  {
    id: "swati",
    number: 15,
    name: { en: "Swati", hi: "स्वाति", ja: "スワティ", ko: "스와티어",},
    sanskrit: { en: "Svātī", hi: "स्वाति", ja: "スヴァーティー", ko: "스바티",},
    deity: { en: "Vayu (wind god)", hi: "वायु (पवन देवता)", ja: "ヴァーユ（風の神）", ko: "바유(바람의 신)",},
    ruler: { en: "Rahu", hi: "राहु", ja: "ラーフ", ko: "라후",},
    symbol: { en: "Young sprout blown by wind", hi: "युवा अंकुर हवा से उड़ गया", ja: "風に揺れる若芽", ko: "바람에 날린 어린 새싹",},
    range: { en: "6°40' – 20°00' Libra", hi: "6°40' – 20°00' तुला", ja: "天秤座 6°40' – 20°00'", ko: "6°40' – 20°00' 천칭자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Movable (Chara)", hi: "चल (चर)", ja: "可動（チャラ）", ko: "이동식(차라)",},
    description: {
      en: "Swati is independent air — trade winds, self-reliance, and flexible intelligence. Like a sapling bending without breaking, natives adapt and often excel in commerce, diplomacy, or solitary paths.", hi: "स्वाति स्वतंत्र हवा है - व्यापारिक हवाएं, आत्मनिर्भरता और लचीली बुद्धि। बिना टूटे झुके हुए पौधे की तरह, जातक अनुकूलन करते हैं और अक्सर वाणिज्य, कूटनीति या एकान्त पथ में उत्कृष्टता प्राप्त करते हैं।", ja: "スワティは独立した風 — 貿易風、自立、柔軟な知性です。折れずに曲がる若芽のように、適応し、商業・外交・ solitary な道で優れることが多いです。", ko: "Swati는 무역풍, 자립, 유연한 정보 등 독립적인 공기입니다. 부러지지 않고 구부러지는 묘목처럼 원주민들은 상업, 외교 또는 고독한 길에 적응하고 종종 탁월합니다.",
    },
    qualities: [
      { en: "Free-spirited, diplomatic, restless", hi: "स्वतंत्र-उत्साही, कूटनीतिक, बेचैन", ja: "自由な精神、外交的、落ち着きなし", ko: "자유분방함, 외교적, 불안함",},
      { en: "Success in business and negotiation", hi: "व्यापार और बातचीत में सफलता", ja: "ビジネスと交渉での成功", ko: "사업과 협상의 성공",},
    ],
  },
  {
    id: "vishakha",
    number: 16,
    name: { en: "Vishakha", hi: "विशाखा", ja: "ヴィシャーカ", ko: "비샤카",},
    sanskrit: { en: "Viśākhā", hi: "विशाखा", ja: "ヴィシャーカー", ko: "비샤카",},
    deity: { en: "Indra-Agni (king & fire)", hi: "इंद्र-अग्नि (राजा और आग)", ja: "インドラ＝アグニ（王と火）", ko: "인드라-아그니(왕과 불)",},
    ruler: { en: "Jupiter", hi: "बृहस्पति", ja: "木星", ko: "목성",},
    symbol: { en: "Triumphal arch / forked branch", hi: "विजयी मेहराब / द्विभाजित शाखा", ja: "凱旋門／分かれた枝", ko: "개선문/갈래 가지",},
    range: { en: "20°00' Libra – 3°20' Scorpio", hi: "20°00' तुला - 3°20' वृश्चिक", ja: "天秤座 20°00' – 蠍座 3°20'", ko: "20°00' 천칭자리 – 3°20' 전갈자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Mixed", hi: "मिश्रित", ja: "混合", ko: "혼합",},
    description: {
      en: "Vishakha is single-pointed ambition — goal fixation, competitive zeal, and celebration after victory. The forked branch symbolizes a path that must choose one direction to bear fruit.", hi: "विशाखा की एकमात्र महत्वाकांक्षा है - लक्ष्य निर्धारण, प्रतिस्पर्धी उत्साह और जीत के बाद जश्न। कांटेदार शाखा उस पथ का प्रतीक है जिसे फल उत्पन्न करने के लिए एक दिशा चुननी होगी।", ja: "ヴィシャーカは一点集中の野心 — 目標への固執、競争の熱、勝利後の祝いです。分かれた枝は実を結ぶために一つの方向を選ぶ道を象徴します。", ko: "Vishakha는 목표 고정, 경쟁적 열정, 승리 후 축하 등 한 가지 야망을 나타냅니다. 갈라진 가지는 열매를 맺기 위해 한 방향을 선택해야 하는 길을 상징합니다.",
    },
    qualities: [
      { en: "Determined, goal-oriented, intense", hi: "दृढ़ निश्चयी, लक्ष्य-उन्मुख, प्रखर", ja: "決意、目標志向、強烈", ko: "결단력 있는, 목표 지향적인, 강렬한",},
      { en: "Jealous rivalry if unchecked", hi: "अनियंत्रित होने पर ईर्ष्यालु प्रतिद्वंद्विता", ja: "制御されなければ嫉妬の競争", ko: "확인하지 않으면 질투심 많은 경쟁",},
    ],
  },
  {
    id: "anuradha",
    number: 17,
    name: { en: "Anuradha", hi: "अनुराधा", ja: "アヌラーダ", ko: "아누라다",},
    sanskrit: { en: "Anurādhā", hi: "अनुराधा", ja: "アヌラーダー", ko: "아누라다",},
    deity: { en: "Mitra (god of friendship)", hi: "मित्र (मित्रता के देवता)", ja: "ミトラ（友情の神）", ko: "미트라(우정의 신)",},
    ruler: { en: "Saturn", hi: "शनि ग्रह", ja: "土星", ko: "토성",},
    symbol: { en: "Lotus / staff", hi: "कमल/कर्मचारी", ja: "蓮／杖", ko: "로터스 / 직원",},
    range: { en: "3°20' – 16°40' Scorpio", hi: "3°20' - 16°40' वृश्चिक", ja: "蠍座 3°20' – 16°40'", ko: "3°20' – ​​16°40' 전갈자리",},
    guna: { en: "Tamas", hi: "तमस्", ja: "タマス", ko: "타마스",},
    nature: { en: "Soft (Mridu)", hi: "शीतल (मृदु)", ja: "柔和（ムリドゥ）", ko: "소프트 (Mridu)",},
    description: {
      en: "Anuradha blooms in unlikely soil — devotion, friendship across borders, and success through loyalty under Saturn's discipline. Mitra's covenant favors organizations, travel abroad, and spiritual groups.", hi: "अनुराधा अप्रत्याशित मिट्टी में खिलती है - भक्ति, सीमाओं के पार दोस्ती, और शनि के अनुशासन के तहत वफादारी के माध्यम से सफलता। मित्रा की वाचा संगठनों, विदेश यात्रा और आध्यात्मिक समूहों का पक्ष लेती है।", ja: "アヌラーダはありえない土壌で開花 — 献身、国境を越える友情、土星の規律下での忠誠による成功です。ミトラの盟約は組織、海外旅行、霊的グループを助けます。", ko: "Anuradha는 예상치 못한 토양에서 꽃을 피웁니다. 헌신, 국경을 초월한 우정, 토성의 규율에 따른 충성심을 통한 성공입니다. 미트라의 언약은 조직, 해외 여행, 영적 단체를 선호합니다.",
    },
    qualities: [
      { en: "Devoted, cooperative, resilient", hi: "समर्पित, सहयोगी, लचीला", ja: "献身的、協力的、回復力", ko: "헌신적, 협력적, 탄력성",},
      { en: "Lotus-like grace under pressure", hi: "दबाव में कमल जैसी कृपा", ja: "圧力下での蓮のような優雅さ", ko: "압력을 받는 연꽃 같은 은혜",},
    ],
  },
  {
    id: "jyeshtha",
    number: 18,
    name: { en: "Jyeshtha", hi: "ज्येष्ठ", ja: "ジェーシュタ", ko: "제슈타",},
    sanskrit: { en: "Jyeṣṭhā", hi: "ज्येष्ठा", ja: "ジェーシュター", ko: "Jyeṣṭha",},
    deity: { en: "Indra (king of gods)", hi: "इंद्र (देवताओं के राजा)", ja: "インドラ（神々の王）", ko: "인드라(신들의 왕)",},
    ruler: { en: "Mercury", hi: "बुध", ja: "水星", ko: "수성",},
    symbol: { en: "Earring / umbrella", hi: "कान की बाली/छतरी", ja: "耳飾り／傘", ko: "귀걸이 / 우산",},
    range: { en: "16°40' – 30°00' Scorpio", hi: "16°40' - 30°00' वृश्चिक", ja: "蠍座 16°40' – 30°00'", ko: "16°40' – 30°00' 전갈자리",},
    guna: { en: "Tamas", hi: "तमस्", ja: "タマス", ko: "타마스",},
    nature: { en: "Sharp (Tikshna)", hi: "तीक्ष्ण (तीक्ष्ण)", ja: "鋭利（ティクシュナ）", ko: "샤프(티크슈나)",},
    description: {
      en: "Jyeshtha is the elder — seniority, protection of family, and the weight of authority. Indra's umbrella shields but also isolates at the top. Themes of jealousy among siblings and guarding reputation arise.", hi: "ज्येष्ठा ज्येष्ठ है - वरिष्ठता, परिवार की सुरक्षा, और अधिकार का भार। इंद्र की छत्रछाया ढालती है लेकिन शीर्ष पर अलग भी हो जाती है। भाई-बहनों के बीच ईर्ष्या और प्रतिष्ठा की रक्षा के प्रसंग उत्पन्न होते हैं।", ja: "ジェーシュタは長老 — 序列、家族の保護、権威の重さです。インドラの傘は守るが頂点では孤立も生む。兄弟間の嫉妬や評判を守るテーマが浮上します。", ko: "Jyeshtha는 연공서열, 가족 보호, 권위의 무게를 지닌 장로입니다. 인드라의 우산은 보호막 역할을 할 뿐만 아니라 상단에서도 분리됩니다. 형제자매 간의 질투와 명예를 지키는 주제가 등장합니다.",
    },
    qualities: [
      { en: "Protective, proud, responsible", hi: "सुरक्षात्मक, गौरवान्वित, जिम्मेदार", ja: "保護的、誇り高い、責任感", ko: "보호적이고, 자랑스럽고, 책임감이 있습니다.",},
      { en: "Occult depth of Scorpio", hi: "वृश्चिक राशि की गुप्त गहराई", ja: "蠍座のオカルト的深さ", ko: "전갈자리의 신비로운 깊이",},
    ],
  },
  {
    id: "mula",
    number: 19,
    name: { en: "Mula", hi: "मुला", ja: "ムーラ", ko: "물라",},
    sanskrit: { en: "Mūla", hi: "मुला", ja: "ムーラ", ko: "물라",},
    deity: { en: "Nirriti (goddess of dissolution)", hi: "निर्ऋति (विघटन की देवी)", ja: "ニッリティ（解散の女神）", ko: "니리티(해체의 여신)",},
    ruler: { en: "Ketu", hi: "केतु", ja: "ケートゥ", ko: "케투",},
    symbol: { en: "Bundled roots", hi: "बंडल जड़ें", ja: "束ねた根", ko: "묶음뿌리",},
    range: { en: "0°00' – 13°20' Sagittarius", hi: "0°00' - 13°20' धनु", ja: "射手座 0°00' – 13°20'", ko: "0°00' – 13°20' 궁수자리",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Sharp (Tikshna)", hi: "तीक्ष्ण (तीक्ष्ण)", ja: "鋭利（ティクシュナ）", ko: "샤프(티크슈나)",},
    description: {
      en: "Mula uproots — investigation to the core, destruction of false foundations, and philosophical reset. Ketu's influence seeks origin stories and liberation from what no longer nourishes.", hi: "मूला को उखाड़ फेंकता है - मूल तक जांच, झूठी नींव का विनाश, और दार्शनिक रीसेट। केतु का प्रभाव मूल कहानियों और उस चीज़ से मुक्ति चाहता है जो अब पोषण नहीं देती है।", ja: "ムーラは根こそぎ — 核心への探究、誤った基盤の破壊、哲学的リセットです。ケートゥの影響は起源の物語と、もはや養わないものからの解放を求めます。", ko: "Mula 뿌리 뽑기 - 핵심에 대한 조사, 잘못된 기반 파괴 및 철학적 재설정. Ketu의 영향력은 더 이상 영양을 공급하지 않는 것으로부터의 기원 이야기와 해방을 추구합니다.",
    },
    qualities: [
      { en: "Researcher, blunt, transformative", hi: "शोधकर्ता, कुंद, परिवर्तनकारी", ja: "研究者、率直、変容的", ko: "연구원, 무뚝뚝하고 변혁적인 사람",},
      { en: "Interest in herbs, roots, hidden causes", hi: "जड़ी-बूटियों, जड़ों, छिपे कारणों में रुचि", ja: "薬草、根、隠れた原因への関心", ko: "허브, 뿌리, 숨겨진 원인에 대한 관심",},
    ],
  },
  {
    id: "purva-ashadha",
    number: 20,
    name: { en: "Purva Ashadha", hi: "पूर्वा आषाढ़", ja: "プルヴァ・アシャーダ", ko: "푸르바 아샤다",},
    sanskrit: { en: "Pūrva Aṣāḍhā", hi: "पूर्व आषाढ़", ja: "プールヴァ・アーシャーダー", ko: "Pūrva Aṣāḍhā",},
    deity: { en: "Apas (cosmic waters)", hi: "अपास (ब्रह्मांडीय जल)", ja: "アパス（宇宙の水）", ko: "아파스(우주수)",},
    ruler: { en: "Venus", hi: "शुक्र", ja: "金星", ko: "금성",},
    symbol: { en: "Fan / winnowing basket", hi: "पंखा / विनोइंग टोकरी", ja: "扇／箕", ko: "부채 / 키질 바구니",},
    range: { en: "13°20' – 26°40' Sagittarius", hi: "13°20' - 26°40' धनु", ja: "射手座 13°20' – 26°40'", ko: "13°20' – ​​26°40' 궁수자리",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Fierce (Ugra)", hi: "भयंकर (उग्रा)", ja: "激烈（ウグラ）", ko: "맹렬한 (우그라)",},
    description: {
      en: "Purva Ashadha is invincible conviction — preaching truth, purifying waters, and refusal to admit defeat prematurely. Apas cleanses; the fan separates grain from chaff in belief and relationship.", hi: "पूर्वा आषाढ़ अजेय दृढ़ विश्वास है - सत्य का उपदेश देना, जल को शुद्ध करना और समय से पहले हार स्वीकार करने से इनकार करना। अपास शुद्ध करता है; विश्वास और रिश्ते में पंखा अनाज को भूसी से अलग करता है।", ja: "プルヴァ・アシャーダは不敗の確信 — 真理を説く、水による浄化、早急な敗北を認めない姿勢です。アパスは清め、扇は信念と関係から穀と糠を分けます。", ko: "Purva Ashadha는 진리를 전파하고, 물을 정화하며, 조기에 패배를 인정하지 않는 무적의 신념입니다. Apas는 정화합니다. 부채는 믿음과 관계에서 곡식과 왕겨를 분리합니다.",
    },
    qualities: [
      { en: "Persuasive, idealistic, proud", hi: "प्रेरक, आदर्शवादी, गौरवान्वित", ja: "説得力、理想主義、誇り", ko: "설득력 있는, 이상주의적인, 자랑스러운",},
      { en: "Affinity for water and declamation", hi: "पानी और विस्मयादिबोधक के प्रति आकर्षण", ja: "水と弁論への縁", ko: "물과 선언에 대한 친화력",},
    ],
  },
  {
    id: "uttara-ashadha",
    number: 21,
    name: { en: "Uttara Ashadha", hi: "उत्तरा आषाढ़", ja: "ウッタラ・アシャーダ", ko: "우타라 아샤다",},
    sanskrit: { en: "Uttara Aṣāḍhā", hi: "उत्तरा आषाढ़", ja: "ウッタラ・アーシャーダー", ko: "웃타라 아샤다(Uttara Aṣāḍhā)",},
    deity: { en: "Vishvadevas (universal gods)", hi: "विश्वदेव (सार्वभौमिक देवता)", ja: "ヴィシュヴァデーヴァ（普遍の神々）", ko: "비슈바데바(보편적 신)",},
    ruler: { en: "Sun", hi: "सूरज", ja: "太陽", ko: "해",},
    symbol: { en: "Elephant tusk / planks of bed", hi: "हाथी का दाँत/बिस्तर के तख्ते", ja: "象牙／寝台の板", ko: "코끼리 엄니 / 침대 판자",},
    range: { en: "26°40' Sagittarius – 10°00' Capricorn", hi: "26°40' धनु - 10°00' मकर", ja: "射手座 26°40' – 山羊座 10°00'", ko: "26°40' 궁수자리 – 10°00' 염소자리",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Fixed (Dhruva)", hi: "स्थिर (ध्रुव)", ja: "固定（ドルヴァ）", ko: "고정 (드루바)",},
    description: {
      en: "Uttara Ashadha finalizes victory — enduring leadership, ethical permanence, and marriage to purpose. The elephant tusk symbolizes unbreakable commitment after the battle is won.", hi: "उत्तरा आषाढ़ विजय को अंतिम रूप देता है - स्थायी नेतृत्व, नैतिक स्थायित्व और उद्देश्य के प्रति विवाह। हाथी का दांत युद्ध जीतने के बाद अटूट प्रतिबद्धता का प्रतीक है।", ja: "ウッタラ・アシャーダは勝利を完成 — 永続する指導、倫理の不変、目的との結婚です。象牙は戦いの後の壊れない誓いを象徴します。", ko: "Uttara Ashadha는 지속적인 리더십, 윤리적 영속성 및 목적에 따른 결혼으로 승리를 확정합니다. 코끼리 엄니는 전투에서 승리한 후에도 깨지지 않는 헌신을 상징합니다.",
    },
    qualities: [
      { en: "Honorable, patient, statesmanlike", hi: "माननीय, धैर्यवान, राजनेता जैसा", ja: "高潔、忍耐、政治家風", ko: "명예롭고, 인내심이 강하며, 정치가다운",},
      { en: "Late but lasting success", hi: "देर से ही सही लेकिन स्थाई सफलता", ja: "遅れて来るが長続きする成功", ko: "늦었지만 지속적인 성공",},
    ],
  },
  {
    id: "shravana",
    number: 22,
    name: { en: "Shravana", hi: "श्रावण", ja: "シュラヴァナ", ko: "슈라바나",},
    sanskrit: { en: "Śravaṇa", hi: "श्रवण", ja: "シュラヴァナ", ko: "스라바나",},
    deity: { en: "Vishnu (preserver)", hi: "विष्णु (रक्षक)", ja: "ヴィシュヌ（維持者）", ko: "비슈누(보존자)",},
    ruler: { en: "Moon", hi: "चंद्रमा", ja: "月", ko: "달",},
    symbol: { en: "Ear / three footprints", hi: "कान / तीन पैरों के निशान", ja: "耳／三つの足跡", ko: "귀 / 발자국 3개",},
    range: { en: "10°00' – 23°20' Capricorn", hi: "10°00' - 23°20' मकर", ja: "山羊座 10°00' – 23°20'", ko: "10°00' – 23°20' 염소자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Movable (Chara)", hi: "चल (चर)", ja: "可動（チャラ）", ko: "이동식(차라)",},
    description: {
      en: "Shravana listens — oral tradition, learning by hearing, and dissemination of sacred knowledge. Vishnu's three steps measure the cosmos; natives often connect people through teaching, media, or travel.", hi: "श्रवण सुनता है - मौखिक परंपरा, सुनकर सीखना, और पवित्र ज्ञान का प्रसार। विष्णु के तीन चरण ब्रह्मांड को मापते हैं; मूल निवासी अक्सर शिक्षण, मीडिया या यात्रा के माध्यम से लोगों से जुड़ते हैं।", ja: "シュラヴァナは聴く — 口承伝統、聞いて学ぶこと、聖なる知識の普及です。ヴィシュヌの三つの歩みは宇宙を測り、教え・メディア・旅で人をつなぐことが多いです。", ko: "Shravana는 구전 전통, 청각 학습, 신성한 지식 전파를 듣습니다. 비슈누의 세 단계는 우주를 측정합니다. 원주민들은 종종 교육, 미디어, 여행을 통해 사람들을 연결합니다.",
    },
    qualities: [
      { en: "Attentive, scholarly, well-traveled", hi: "चौकस, विद्वान, अच्छी तरह से यात्रा करने वाला", ja: "注意深い、学究的、旅慣れ", ko: "세심함, 학문적, 여행 경험이 많음",},
      { en: "Fame through word and recording", hi: "शब्द और रिकॉर्डिंग के माध्यम से प्रसिद्धि", ja: "言葉と記録による名声", ko: "말과 녹음을 통한 명성",},
    ],
  },
  {
    id: "dhanishta",
    number: 23,
    name: { en: "Dhanishta", hi: "धनिष्ठा", ja: "ダニシュタ", ko: "다니슈타",},
    sanskrit: { en: "Dhaniṣṭhā", hi: "धनिष्ठा", ja: "ダニーシュター", ko: "다니쉬타",},
    deity: { en: "Vasus (eight elemental gods)", hi: "वसुस (आठ मौलिक देवता)", ja: "ヴァス（八つの元素神）", ko: "바수스(8명의 원소 ​​신)",},
    ruler: { en: "Mars", hi: "मंगल ग्रह", ja: "火星", ko: "화성",},
    symbol: { en: "Drum / flute", hi: "ढोल/बाँसुरी", ja: "太鼓／笛", ko: "드럼/플루트",},
    range: { en: "23°20' Capricorn – 6°40' Aquarius", hi: "23°20' मकर - 6°40' कुम्भ", ja: "山羊座 23°20' – 水瓶座 6°40'", ko: "23°20' 염소자리 – 6°40' 물병자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Movable (Chara)", hi: "चल (चर)", ja: "可動（チャラ）", ko: "이동식(차라)",},
    description: {
      en: "Dhanishta is wealth through rhythm — music, percussion, prosperity, and sometimes fame that arrives suddenly. The Vasus link material abundance with ethical use of resources.", hi: "धनिष्ठा लय के माध्यम से धन है - संगीत, ताल, समृद्धि, और कभी-कभी अचानक आने वाली प्रसिद्धि। वसु भौतिक प्रचुरता को संसाधनों के नैतिक उपयोग से जोड़ते हैं।", ja: "ダニシュタはリズムによる富 — 音楽、打楽器、繁栄、時に突然の名声です。ヴァスは物質的豊かさと資源の倫理的使用を結びます。", ko: "Dhanishta는 음악, 타악기, 번영, 때로는 갑자기 찾아오는 명성 등 리듬을 통한 부입니다. Vasus는 물질적 풍요와 자원의 윤리적 사용을 연결합니다.",
    },
    qualities: [
      { en: "Rhythmic, wealthy, sociable", hi: "लयबद्ध, धनी, मिलनसार", ja: "リズミカル、裕福、社交的", ko: "리드미컬하고 부유하며 사교적입니다.",},
      { en: "Adaptability in groups", hi: "समूहों में अनुकूलनशीलता", ja: "集団での適応力", ko: "그룹의 적응성",},
    ],
  },
  {
    id: "shatabhisha",
    number: 24,
    name: { en: "Shatabhisha", hi: "शतभिषा", ja: "シャタビシャ", ko: "샤타비샤",},
    sanskrit: { en: "Śatabhiṣā", hi: "शतभिषा", ja: "シャタビシャー", ko: "샤타비샤",},
    deity: { en: "Varuna (god of cosmic waters & law)", hi: "वरुण (ब्रह्मांडीय जल और कानून के देवता)", ja: "ヴァルナ（宇宙の水と法の神）", ko: "바루나 (우주의 물과 법의 신)",},
    ruler: { en: "Rahu", hi: "राहु", ja: "ラーフ", ko: "라후",},
    symbol: { en: "Empty circle / hundred physicians", hi: "खाली घेरा / सौ वैद्य", ja: "空の円／百の医師", ko: "빈 원 / 의사 100명",},
    range: { en: "6°40' – 20°00' Aquarius", hi: "6°40' – 20°00' कुंभ राशि", ja: "水瓶座 6°40' – 20°00'", ko: "6°40' – 20°00' 물병자리",},
    guna: { en: "Rajas", hi: "राजाओं", ja: "ラジャス", ko: "라자스",},
    nature: { en: "Movable (Chara)", hi: "चल (चर)", ja: "可動（チャラ）", ko: "이동식(차라)",},
    description: {
      en: "Shatabhisha heals in solitude — alternative medicine, astronomy, and guarded secrets. Varuna sees all; natives may be reformers working at night or behind screens, restoring what conventional paths miss.", hi: "शतभिषा एकांत में उपचार करती है - वैकल्पिक चिकित्सा, खगोल विज्ञान, और संरक्षित रहस्य। वरुण सब देखता है; मूल निवासी रात में या स्क्रीन के पीछे काम करने वाले सुधारक हो सकते हैं, जो पारंपरिक रास्ते चूक गए हैं उन्हें बहाल कर रहे हैं।", ja: "シャタビシャは孤独で癒す — 代替医学、天文学、守られた秘密です。ヴァルナはすべてを見通し、夜や画面の向こうで働き、常道が見逃すものを回復する改革者となり得ます。", ko: "Shatabhisha는 대체 의학, 천문학, 비밀을 지키는 고독 속에서 치유됩니다. Varuna는 모든 것을 봅니다. 원주민은 밤이나 스크린 뒤에서 일하는 개혁가일 수 있으며 기존 경로에서 놓친 것을 복원할 수 있습니다.",
    },
    qualities: [
      { en: "Secretive, scientific, rebellious", hi: "गुप्त, वैज्ञानिक, विद्रोही", ja: "秘密主義、科学的、反抗的", ko: "비밀스럽고 과학적이며 반항적입니다.",},
      { en: "Hundred cures through unconventional means", hi: "अपरंपरागत तरीकों से सैकड़ों इलाज", ja: "非伝統的手段による百の治療", ko: "색다른 방법으로 수백 가지 치료",},
    ],
  },
  {
    id: "purva-bhadrapada",
    number: 25,
    name: { en: "Purva Bhadrapada", hi: "पूर्व भाद्रपद", ja: "プルヴァ・バドラパダ", ko: "푸르바 바드라파다",},
    sanskrit: { en: "Pūrva Bhādrapadā", hi: "पूर्व भाद्रपद", ja: "プールヴァ・バードラパダー", ko: "푸르바 바드라파다",},
    deity: { en: "Aja Ekapada (one-footed goat of fire)", hi: "अजा एकपाड़ा (एक पैर वाली आग वाली बकरी)", ja: "アジャ・エーカパーダ（一足の火の山羊）", ko: "아자 에카파다(한발 달린 불의 염소)",},
    ruler: { en: "Jupiter", hi: "बृहस्पति", ja: "木星", ko: "목성",},
    symbol: { en: "Sword / two front legs of funeral cot", hi: "तलवार/अंतिम संस्कार खाट के सामने के दो पैर", ja: "剣／葬儀台の前脚", ko: "검 / 장의용 앞다리 2개",},
    range: { en: "20°00' Aquarius – 3°20' Pisces", hi: "20°00' कुंभ - 3°20' मीन", ja: "水瓶座 20°00' – 魚座 3°20'", ko: "20°00' 물병자리 – 3°20' 물고기자리",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Fierce (Ugra)", hi: "भयंकर (उग्रा)", ja: "激烈（ウグラ）", ko: "맹렬한 (우그라)",},
    description: {
      en: "Purva Bhadrapada walks the edge — austere spirituality, fierce ideals, and transformation through fire. The funeral cot's front legs face the pyre; this mansion confronts mortality to extract higher meaning.", hi: "पूर्वा भाद्रपद किनारे पर चलता है - कठोर आध्यात्मिकता, उग्र आदर्श, और अग्नि के माध्यम से परिवर्तन। अंतिम संस्कार की खाट के अगले पैर चिता की ओर हैं; यह हवेली उच्च अर्थ निकालने के लिए मृत्यु दर का सामना करती है।", ja: "プルヴァ・バドラパダは境界を歩く — 厳しい霊性、激しい理想、火による変容です。葬儀台の前脚は火葬場に向き、この宿は死と向き合い高次の意味を抽出します。", ko: "Purva Bhadrapada는 엄격한 영성, 치열한 이상, 불을 통한 변화의 가장자리를 걷습니다. 장례식용 침대의 앞다리는 장작더미를 향하고 있습니다. 이 저택은 더 높은 의미를 추출하기 위해 죽음에 직면합니다.",
    },
    qualities: [
      { en: "Intense, mystical, austere", hi: "तीव्र, रहस्यमय, कठोर", ja: "強烈、神秘的、禁欲的", ko: "강렬하고, 신비롭고, 엄숙하다",},
      { en: "Paradoxical blend of zeal and calm", hi: "उत्साह और शांति का विरोधाभासी मिश्रण", ja: "熱意と静けさの逆説的融合", ko: "열정과 차분함의 역설적인 조화",},
    ],
  },
  {
    id: "uttara-bhadrapada",
    number: 26,
    name: { en: "Uttara Bhadrapada", hi: "उत्तरा भाद्रपद", ja: "ウッタラ・バドラパダ", ko: "우타라 바드라파다",},
    sanskrit: { en: "Uttara Bhādrapadā", hi: "उत्तरा भाद्रपद", ja: "ウッタラ・バードラパダー", ko: "웃타라 바드라파다",},
    deity: { en: "Ahir Budhnya (serpent of the deep)", hi: "अहीर बुधन्या (गहरे सांप)", ja: "アヒル・ブドゥニャ（深淵の蛇）", ko: "Ahir Budhnya (깊은 뱀)",},
    ruler: { en: "Saturn", hi: "शनि ग्रह", ja: "土星", ko: "토성",},
    symbol: { en: "Back legs of funeral cot / twins", hi: "अंतिम संस्कार खाट/जुड़वाँ के पिछले पैर", ja: "葬儀台の後脚／双子", ko: "장례식장 뒷다리 / 쌍둥이",},
    range: { en: "3°20' – 16°40' Pisces", hi: "3°20' - 16°40' मीन", ja: "魚座 3°20' – 16°40'", ko: "3°20' – ​​16°40' 물고기자리",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Fixed (Dhruva)", hi: "स्थिर (ध्रुव)", ja: "固定（ドルヴァ）", ko: "고정 (드루바)",},
    description: {
      en: "Uttara Bhadrapada stabilizes the mystical — wisdom after ordeal, counseling, and depth meditation. Ahir Budhnya guards cosmic ocean beds; natives often become anchors for others in crisis.", hi: "उत्तरा भाद्रपदा कठिन परीक्षा, परामर्श और गहन ध्यान के बाद रहस्यमय - ज्ञान को स्थिर करता है। अहीर बुधन्या ब्रह्मांडीय महासागर तल की रक्षा करता है; जातक अक्सर संकट में दूसरों के लिए सहारा बनते हैं।", ja: "ウッタラ・バドラパダは神秘を安定 — 試練後の智慧、カウンセリング、深い瞑想です。アヒル・ブドゥニャは宇宙の海床を守り、危機で他者の錨となることが多いです。", ko: "Uttara Bhadrapada는 시련, 상담 및 깊이 명상 이후의 지혜와 같은 신비로운 것을 안정시킵니다. Ahir Budhnya는 우주 해저를 보호합니다. 원주민은 종종 위기에 처한 다른 사람들의 닻이 됩니다.",
    },
    qualities: [
      { en: "Wise, calm, charitable", hi: "बुद्धिमान, शांत, परोपकारी", ja: "賢明、穏やか、慈善的", ko: "현명함, 침착함, 자애로움",},
      { en: "Kundalini and dream depth", hi: "कुंडलिनी और स्वप्न की गहराई", ja: "クンダリーニと夢の深さ", ko: "쿤달리니와 꿈의 깊이",},
    ],
  },
  {
    id: "revati",
    number: 27,
    name: { en: "Revati", hi: "रेवती", ja: "レヴァティ", ko: "레바티",},
    sanskrit: { en: "Revatī", hi: "रेवती", ja: "レヴァティー", ko: "레바티",},
    deity: { en: "Pushan (nourisher, guide of souls)", hi: "पूषन (पोषक, आत्माओं का मार्गदर्शक)", ja: "プーシャン（養育者、魂の案内人）", ko: "푸샨(영혼의 영양가, 인도자)",},
    ruler: { en: "Mercury", hi: "बुध", ja: "水星", ko: "수성",},
    symbol: { en: "Fish / drum for journey's end", hi: "यात्रा समाप्ति के लिए मछली/ड्रम", ja: "魚／旅の終わりの太鼓", ko: "여행의 마지막을 위한 물고기/북",},
    range: { en: "16°40' – 30°00' Pisces", hi: "16°40' – 30°00' मीन", ja: "魚座 16°40' – 30°00'", ko: "16°40' – 30°00' 물고기자리",},
    guna: { en: "Sattva", hi: "सत्व", ja: "サットヴァ", ko: "사트바",},
    nature: { en: "Soft (Mridu)", hi: "शीतल (मृदु)", ja: "柔和（ムリドゥ）", ko: "소프트 (Mridu)",},
    description: {
      en: "Revati closes the Nakshatra cycle — safe travel, compassion, and escort to the next destination. Pushan protects flocks and roads; this mansion blesses endings that are also beginnings, especially journeys and animal care.", hi: "रेवती ने नक्षत्र चक्र को बंद कर दिया - सुरक्षित यात्रा, करुणा और अगले गंतव्य तक ले जाना। पूषन झुंडों और सड़कों की रक्षा करता है; यह हवेली उन अंतों को आशीर्वाद देती है जो शुरुआत भी हैं, विशेष रूप से यात्राएं और जानवरों की देखभाल।", ja: "レヴァティはナクシャトラの輪を閉じる — 安全な旅、慈悲、次の目的地への案内です。プーシャンは群れと道を守り、この宿は終わりであり始まりでもある旅と動物のケアを祝福します。", ko: "Revati는 안전한 여행, 연민, 다음 목적지로의 호위 등 Nakshatra 주기를 종료합니다. 푸샨은 양떼와 도로를 보호합니다. 이 저택은 시작이기도 한 결말, 특히 여행과 동물 보호를 축복합니다.",
    },
    qualities: [
      { en: "Nurturing, imaginative, otherworldly", hi: "पालन-पोषण करने वाला, कल्पनाशील, अलौकिक", ja: "養育的、想像力豊か、この世離れ", ko: "육성, 상상력, 초자연적",},
      { en: "Prosperity through protection of the vulnerable", hi: "कमजोरों की सुरक्षा के माध्यम से समृद्धि", ja: "弱い者を守ることによる繁栄", ko: "취약계층 보호를 통한 번영",},
    ],
  },
];
