import type { WisdomArticle } from "./types";
import { educationImages, eduImage } from "./education-images";

/** Articles sourced verbatim from temp-content/p4.txt (link-scrubbed, headings normalized) */
export const p4Articles: WisdomArticle[] = [
  {
    id: "planetary-strengths",
    section: "planets",
    title: { en: `Planetary Strengths or Powers`, ja: `惑星の強みまたは力` },
    related: ["natural-benefics-malefics","planetary-aspects","twelve-houses"],
    blocks: [
      { type: "heading", level: 2, text: { en: `Planetary Strengths or Powers`, ja: `惑星の強みまたは力` } },
      { type: "paragraph", text: { en: `Summary: This article covers one of the most important aspects of chart interpretation—assessing the "strength," "power," or "status" of a planet based on its sign placement in a birth chart. It also explains the principles of sign ownership (rulership), the concepts of planetary "friends" and "enemies," and examines how retrograde motion, combustion, Vargottama status, divisional charts, and planetary war influence planetary strength.`, ja: `概要: この記事では、出生図における星座の配置に基づいて惑星の「強さ」、「パワー」、または「ステータス」を評価するという、チャート解釈の最も重要な側面の 1 つについて説明します。また、記号の所有権 (支配者) の原則、惑星の「友人」と「敵」の概念も説明し、逆行、燃焼、ヴァルゴッタマのステータス、分割図、惑星戦争が惑星の強さにどのように影響するかを考察します。` } },
      { type: "heading", level: 3, text: { en: `Sign ‘Ownership’ or ‘Rulership’ Principles`, ja: `「所有権」または「支配者」の原則に署名する` } },
      { type: "paragraph", text: { en: `The Vedic seers assigned each sign of the zodiac to a particular planet.`, ja: `ヴェーダの予言者たちは、黄道帯の各星座を特定の惑星に割り当てました。` } },
      { type: "heading", level: 3, text: { en: `Sign Ownership or Rulership by Planets in Jyotish`, ja: `ジョーティッシュの惑星による所有権または支配権に署名します` } },
      { type: "paragraph", text: { en: `For example, from the chart above we can see that the Sun is associated with the sign Leo. Therefore, the Sun is said to be the Owner or Ruler of Leo (sidereal).`, ja: `たとえば、上のチャートから、太陽が獅子座に関連付けられていることがわかります。したがって、太陽は獅子座（恒星）の所有者または支配者であると言われています。` } },
      { type: "paragraph", text: { en: `Notice that the Sun and Moon each rule only one sign, whereas the remaining visible planets—Mars, Mercury, Jupiter, Venus, and Saturn—each rule two signs. Thus, Jupiter rules Sagittarius and Pisces, Mercury rules Gemini and Virgo, and so on.`, ja: `太陽と月はそれぞれ 1 つの星座のみを支配しますが、残りの目に見える惑星 (火星、水星、木星、金星、土星) はそれぞれ 2 つの星座を支配していることに注目してください。したがって、木星は射手座と魚座を支配し、水星は双子座と乙女座を支配します。` } },
      { type: "paragraph", text: { en: `It is important to note that Rahu and Ketu do not own or rule any zodiac sign.`, ja: `ラーフとケートゥはどの星座も所有または支配していないことに注意することが重要です。` } },
      { type: "heading", level: 3, text: { en: `Planetary ‘Strengths’ or ‘Powers’ – by Sign Placement`, ja: `惑星の「強み」または「力」 – 星座の配置による` } },
      { type: "paragraph", text: { en: `In Jyotish, evaluating the strength or power of a planet is a fundamental part of chart interpretation.`, ja: `ジョーティッシュでは、惑星の強さやパワーを評価することがチャート解釈の基本的な部分です。` } },
      { type: "paragraph", text: { en: `A planet regarded as strong tends to produce benefits and indicates positive returning karma. In general terms, a strong planet is usually considered a beneficial planet.`, ja: `強いとみなされる惑星は恩恵を生み出す傾向があり、ポジティブなカルマが戻ってくることを示しています。一般的に、強い惑星は通常、有益な惑星であると考えられます。` } },
      { type: "paragraph", text: { en: `There are two primary ways in which a strong planet produces positive results:`, ja: `強い惑星がポジティブな結果を生み出す主な方法は 2 つあります。` } },
      { type: "heading", level: 3, text: { en: `1. Benefits Through the Planet’s Natural Indications`, ja: `1. 地球の自然の兆候による恩恵` } },
      { type: "paragraph", text: { en: `A strong planet supports the life areas represented by its natural associations or Karakas.`, ja: `強力な惑星は、自然の関連性またはカラカに代表される生命領域をサポートします。` } },
      { type: "paragraph", text: { en: `For example, the Sun naturally signifies health, vitality, self-esteem, authority, power, and the relationship with one's father. Therefore, when the Sun is strong in a chart, we generally expect positive outcomes in these areas.`, ja: `たとえば、太陽は当然、健康、活力、自尊心、権威、力、そして父親との関係を意味します。したがって、チャートで太陽が強い場合、一般的にこれらの分野でプラスの結果が期待されます。` } },
      { type: "paragraph", text: { en: `Similarly, the Moon naturally represents the mind, emotions, memory, and mental well-being. A strong Moon would therefore support emotional balance, memory, and mental stability.`, ja: `同様に、月は自然に心、感情、記憶、精神的な幸福を表します。したがって、強い月は感情的なバランス、記憶力、精神的な安定をサポートします。` } },
      { type: "heading", level: 3, text: { en: `2. Benefits Through the Houses the Planet Rules`, ja: `2. 惑星が支配する家を通じて得られる恩恵` } },
      { type: "paragraph", text: { en: `A strong planet also supports the houses associated with the signs that it owns or rules.`, ja: `強い惑星は、それが所有または支配する星座に関連するハウスもサポートします。` } },
      { type: "paragraph", text: { en: `In Jyotish, each house encompasses an entire zodiac sign. Consequently, every house is connected to a particular sign and therefore to a ruling planet. When constructing a horoscope, the Ascendant sign becomes the first house.`, ja: `ジョーティッシュでは、各ハウスが星座全体を囲みます。その結果、すべてのハウスは特定のサインに接続され、したがって支配惑星に接続されます。ホロスコープを作成する場合、アセンダントサインが最初のハウスになります。` } },
      { type: "paragraph", text: { en: `For example, if a person has Aries rising, Aries becomes the first house. To examine matters relating to children, we look to the 5th house. Counting clockwise from Aries, Leo becomes the 5th house. Since the Sun rules Leo, a strong Sun would positively influence the affairs of the 5th house, including children, education, intelligence, and creativity.`, ja: `たとえば、牡羊座が上昇している人は、牡羊座が最初の家になります。子供に関する問題を調べるには、5 ハウスに注目します。牡羊座から時計回りに数えると、獅子座は５室になります。太陽が獅子座を支配しているため、強い太陽は子供、教育、知性、創造性など、5室の事柄にプラスの影響を与えるでしょう。` } },
      { type: "paragraph", text: { en: `This support would come in addition to the Sun's natural indications such as health, confidence, and authority.`, ja: `このサポートは、健康、自信、権威といった太陽の自然な兆候に加えて与えられるでしょう。` } },
      { type: "paragraph", text: { en: `To summarise, when a planet is strong, both its natural indications and the houses it rules receive support and benefit.`, ja: `要約すると、惑星が強いとき、その自然の兆候とそれが支配するハウスの両方がサポートと恩恵を受けます。` } },
      { type: "heading", level: 3, text: { en: `Assessing Planetary Strength from Sign Placement`, ja: `標識の配置から惑星の強さを評価する` } },
      { type: "paragraph", text: { en: `Although planetary strength can be measured in numerous ways, one of the most important methods is by examining the zodiac sign in which the planet is placed.`, ja: `惑星の強さはさまざまな方法で測定できますが、最も重要な方法の 1 つは、惑星が配置されている星座を調べることです。` } },
      { type: "paragraph", text: { en: `In some cases, the specific degree within a sign can also affect the level of strength.`, ja: `場合によっては、サイン内の特定の程度も強さのレベルに影響を与える可能性があります。` } },
      { type: "paragraph", text: { en: `Vedic Astrology teaches that certain signs empower a planet and enable it to produce beneficial results, while other signs weaken it and may indicate challenges or more difficult returning karmas. Therefore, a planet's sign placement plays a major role in determining its strength.`, ja: `ヴェーダ占星術は、特定の兆候が惑星に力を与え、有益な結果を生み出すことを可能にする一方で、他の兆候がそれを弱め、課題やより困難なカルマの帰還を示す可能性があると教えています。したがって、惑星の星座の配置は、その強さを決定する上で大きな役割を果たします。` } },
      { type: "paragraph", text: { en: `When first learning astrology, a useful approach is to identify whether each planet falls into one of four principal categories of strength.`, ja: `初めて占星術を学ぶ場合、各惑星が強さの 4 つの主要なカテゴリーのいずれかに該当するかどうかを確認するのが便利なアプローチです。` } },
      { type: "paragraph", text: { en: `These are:`, ja: `これらは：` } },
      { type: "paragraph", text: { en: `• Exalted`, ja: `• 高揚した` } },
      { type: "paragraph", text: { en: `• Moolatrikona`, ja: `• ムーラトリコーナ` } },
      { type: "paragraph", text: { en: `• Own Sign`, ja: `• 自分のサイン` } },
      { type: "paragraph", text: { en: `• Debilitated (or Fallen)`, ja: `• 衰弱した（または倒れた）` } },
      { type: "paragraph", text: { en: `Exalted is the strongest condition, while Debilitated is the weakest. A planet placed in its Own Sign is generally considered strong and supportive.`, ja: `Exalted は最も強い状態であり、Debilitated は最も弱い状態です。自分の星座に位置する惑星は、一般的に強くて協力的であると考えられています。` } },
      { type: "paragraph", text: { en: `The state known as Moolatrikona has no direct English equivalent but is regarded as stronger than Own Sign and slightly below Exaltation.`, ja: `ムーラトリコーナとして知られる状態には、英語で直接的に相当するものはありませんが、オウンサインよりも強く、高揚よりわずかに下であると見なされています。` } },
      { type: "paragraph", text: { en: `The sign of debilitation is always located exactly 180 degrees opposite the sign of exaltation.`, ja: `衰弱の兆候は常に高揚の兆候のちょうど 180 度反対に位置します。` } },
      { type: "paragraph", text: { en: `For example, Venus is naturally benefic. When Venus occupies Pisces, its sign of exaltation, it can produce significant benefits through both its natural indications and the houses associated with Taurus and Libra, the signs it rules.`, ja: `たとえば、金星はもともと恩恵を受けます。金星が高揚のサインである魚座を占めると、その自然の兆候と、金星が支配するサインであるおうし座と天秤座に関連するハウスの両方を通じて、大きな利益を生み出すことができます。` } },
      { type: "paragraph", text: { en: `However, when Venus occupies Virgo, its sign of debilitation, its ability to provide positive results is greatly reduced.`, ja: `しかし、金星が衰弱の兆候である乙女座を占めると、前向きな結果をもたらす能力は大幅に低下します。` } },
      { type: "paragraph", text: { en: `A planet's capacity to produce beneficial outcomes therefore varies according to its strength, and its strength depends largely upon the sign in which it is placed.`, ja: `したがって、惑星が有益な結果を生み出す能力はその強さに応じて変化し、その強さは主にそれが配置されている星座に依存します。` } },
      { type: "paragraph", text: { en: `The following sections provide the traditional strength classifications.`, ja: `次のセクションでは、従来の強度分類について説明します。` } },
      { type: "heading", level: 3, text: { en: `Planetary Strengths or Powers by Sign Placement`, ja: `星座の配置による惑星の強さまたはパワー` } },
      { type: "heading", level: 3, text: { en: `Sun (Surya)`, ja: `太陽（スーリヤ）` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Aries (maximum strength at 10° Aries)`, ja: `• 高貴な星座: 牡羊座 (牡羊座 10° で最大の力)` } },
      { type: "paragraph", text: { en: `• Moolatrikona Sign: Leo 0°–20°`, ja: `• ムーラトリコーナ星座: 獅子座 0°–20°` } },
      { type: "paragraph", text: { en: `• Own Sign: Leo 20°–30°`, ja: `• 自分の星座: 獅子座 20°–30°` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Libra (maximum weakness at 10° Libra)`, ja: `• 衰弱した星座：天秤座（天秤座10度で最大の弱さ）` } },
      { type: "heading", level: 3, text: { en: `Moon (Chandra)`, ja: `ムーン（チャンドラ）` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Taurus 0°–3°`, ja: `• 高貴な星座: おうし座 0°–3°` } },
      { type: "paragraph", text: { en: `• Moolatrikona Sign: Taurus 3°–30°`, ja: `• ムーラトリコーナ星座: おうし座 3°–30°` } },
      { type: "paragraph", text: { en: `• Own Sign: Cancer`, ja: `• 自分の星座：蟹座` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Scorpio (maximum weakness at 3° Scorpio)`, ja: `• 衰弱した星座: 蠍座 (蠍座 3° で最大の衰弱)` } },
      { type: "heading", level: 3, text: { en: `Mars (Mangala)`, ja: `火星 (マンガラ)` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Capricorn (maximum strength at 28° Capricorn)`, ja: `• 高貴な星座: 山羊座 (山羊座 28° で最大の力)` } },
      { type: "paragraph", text: { en: `• Moolatrikona Sign: Aries 0°–12°`, ja: `• ムーラトリコーナ星座: 牡羊座 0°–12°` } },
      { type: "paragraph", text: { en: `• Own Signs: Aries 12°–30° and Scorpio`, ja: `• 自分の星座: 牡羊座 12°–30° と蠍座` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Cancer (maximum weakness at 28° Cancer)`, ja: `• 衰弱の兆候: がん (がん 28° で最大の衰弱)` } },
      { type: "heading", level: 3, text: { en: `Mercury (Buddha)`, ja: `水星（仏陀）` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Virgo 0°–15° (maximum strength at 15° Virgo)`, ja: `• 高貴な星座: 乙女座 0°–15° (乙女座 15° で最大の力)` } },
      { type: "paragraph", text: { en: `• Moolatrikona Sign: Virgo 16°–20°`, ja: `• ムーラトリコーナ星座: おとめ座 16°–20°` } },
      { type: "paragraph", text: { en: `• Own Signs: Virgo 20°–30° and Gemini`, ja: `• 自分の星座: 乙女座 20°～30° と双子座` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Pisces (maximum weakness at 15° Pisces)`, ja: `• 衰弱した星座：魚座（魚座15°で最大の衰弱）` } },
      { type: "heading", level: 3, text: { en: `Jupiter (Guru)`, ja: `ジュピター (教祖)` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Cancer (maximum strength at 5° Cancer)`, ja: `• 高貴な星座：蟹座（蟹座5°で最大強度）` } },
      { type: "paragraph", text: { en: `• Moolatrikona Sign: Sagittarius 0°–10°`, ja: `• ムーラトリコーナ星座: 射手座 0°–10°` } },
      { type: "paragraph", text: { en: `• Own Signs: Sagittarius 10°–30° and Pisces`, ja: `• 自分の星座: 射手座 10°～30° と魚座` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Capricorn (maximum weakness at 5° Capricorn)`, ja: `• 衰弱した星座: 山羊座 (山羊座 5° で最大の弱さ)` } },
      { type: "heading", level: 3, text: { en: `Venus (Shukra)`, ja: `ヴィーナス（シュクラ）` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Pisces (maximum strength at 27° Pisces)`, ja: `• 高貴な星座: 魚座 (魚座 27° で最大の力)` } },
      { type: "paragraph", text: { en: `• Moolatrikona Sign: Libra 0°–15° and Taurus`, ja: `• ムーラトリコーナ星座: 天秤座 0°–15° およびおうし座` } },
      { type: "paragraph", text: { en: `• Own Signs: Taurus 15°–30° and Libra`, ja: `• 自分の星座: おうし座 15°–30° と天秤座` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Virgo (maximum weakness at 27° Virgo)`, ja: `• 衰弱した星座: 乙女座 (乙女座 27° で最大の衰弱)` } },
      { type: "heading", level: 3, text: { en: `Saturn (Shani)`, ja: `サターン（シャニ）` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Libra (maximum strength at 20° Libra)`, ja: `• 高貴な星座: 天秤座 (天秤座 20°で最大の力)` } },
      { type: "paragraph", text: { en: `• Moolatrikona Sign: Aquarius 0°–15°`, ja: `• ムーラトリコーナ星座: 水瓶座 0°–15°` } },
      { type: "paragraph", text: { en: `• Own Signs: Aquarius 15°–30° and Capricorn`, ja: `• 自分の星座: 水瓶座 15°～30° と山羊座` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Aries (maximum weakness at 20° Aries)`, ja: `• 衰弱した星座: 牡羊座 (牡羊座 20° で最大の衰弱)` } },
      { type: "heading", level: 3, text: { en: `Rahu`, ja: `ラーフ` } },
      { type: "paragraph", text: { en: `There is considerable variation among the ancient authorities regarding the signs where Rahu and Ketu are strongest or weakest. The following placements are based on the most reliable sources available.`, ja: `ラーフとケートゥが最も強いまたは最も弱い兆候に関しては、古代の権威の間でかなりのばらつきがあります。以下の配置は、入手可能な最も信頼できる情報源に基づいています。` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Taurus`, ja: `• 高貴な星座：おうし座` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Scorpio`, ja: `• 衰弱した星座：蠍座` } },
      { type: "heading", level: 3, text: { en: `Ketu`, ja: `ケートゥ` } },
      { type: "paragraph", text: { en: `• Exalted Sign: Scorpio`, ja: `• 高貴な星座：蠍座` } },
      { type: "paragraph", text: { en: `• Debilitated Sign: Taurus`, ja: `• 衰弱した星座：おうし座` } },
      { type: "heading", level: 3, text: { en: `Additional Measures of Strength – ‘Friends’ and ‘Enemies’`, ja: `強さの追加の尺度 - 「友達」と「敵」` } },
      { type: "paragraph", text: { en: `Experienced astrologers use additional categories that lie between the states of Own Sign and Debilitation. These provide a more refined assessment of planetary condition.`, ja: `経験豊富な占星術師は、自分の星座と衰弱の状態の間にある追加のカテゴリーを使用します。これらは、惑星の状態のより洗練された評価を提供します。` } },
      { type: "paragraph", text: { en: `Three important intermediate categories are:`, ja: `3 つの重要な中間カテゴリは次のとおりです。` } },
      { type: "paragraph", text: { en: `• Friend`, ja: `• 友達` } },
      { type: "paragraph", text: { en: `• Neutral`, ja: `• ニュートラル` } },
      { type: "paragraph", text: { en: `• Enemy`, ja: `• 敵` } },
      { type: "paragraph", text: { en: `A planet placed in a sign ruled by a friendly planet tends to function well, whereas a planet occupying the sign of an enemy is weakened.`, ja: `友好的な惑星が支配する星座に位置する惑星はうまく機能する傾向にありますが、敵の星座にある惑星は弱体化します。` } },
      { type: "paragraph", text: { en: `Of course, planets do not literally have friends or enemies. These terms simply indicate that certain planetary environments are more supportive than others. For example, Venus is considered less comfortable and therefore less productive when placed in a sign ruled by an enemy such as the Sun.`, ja: `もちろん、惑星には文字通り友人や敵がいるわけではありません。これらの用語は、特定の惑星環境が他の惑星環境よりも支援的であることを単に示しています。たとえば、金星が太陽などの敵に支配される星座に配置されると、快適性が低下し、生産性が低下すると考えられます。` } },
      { type: "paragraph", text: { en: `In addition to these permanent friendship categories, Jyotish also recognises temporary friendships based upon the relative positions of planets within a chart. These create two additional classifications:`, ja: `これらの永続的な友情カテゴリーに加えて、ジョーティッシュは、チャート内の惑星の相対的な位置に基づいて一時的な友情も認識します。これらにより、次の 2 つの追加の分類が作成されます。` } },
      { type: "paragraph", text: { en: `• Great Friend`, ja: `• 素晴らしい友達` } },
      { type: "paragraph", text: { en: `• Great Enemy`, ja: `• 大きな敵` } },
      { type: "paragraph", text: { en: `Although charts and rules exist to determine these relationships, they can be challenging for beginners to memorise. Fortunately, most good Vedic Astrology software calculates these conditions automatically.`, ja: `これらの関係を判断するための図表やルールは存在しますが、初心者にとってそれらを覚えるのは難しい場合があります。幸いなことに、優れたヴェーダ占星術ソフトウェアのほとんどは、これらの条件を自動的に計算します。` } },
      { type: "paragraph", text: { en: `Together with the categories of Exalted, Moolatrikona, Own Sign, and Debilitated, these friendship classifications form the primary planetary states or Avasthas used in chart interpretation.`, ja: `これらの友情の分類は、高揚、ムーラトリコーナ、オウンサイン、衰弱のカテゴリーとともに、チャートの解釈に使用される主要な惑星国家またはアヴァスタを形成します。` } },
      { type: "paragraph", text: { en: `For a complete analysis, all nine categories should be considered. However, beginners can gain surprisingly accurate insights simply by focusing on the four major states: Exalted, Moolatrikona, Own Sign, and Debilitated.`, ja: `完全な分析を行うには、9 つ​​のカテゴリすべてを考慮する必要があります。ただし、初心者は、高揚、ムーラトリコーナ、オウンサイン、衰弱の 4 つの主要な状態に焦点を当てるだけで、驚くほど正確な洞察を得ることができます。` } },
      { type: "paragraph", text: { en: `The sage Parashara quantified the relative benefits of these states as follows:`, ja: `賢者パラシャラは、これらの州の相対的な利点を次のように定量化しました。` } },
      { type: "paragraph", text: { en: `• Exalted: 100%`, ja: `• 高揚: 100%` } },
      { type: "paragraph", text: { en: `• Moolatrikona: 75%`, ja: `• ムーラトリコーナ: 75%` } },
      { type: "paragraph", text: { en: `• Own Sign: 50%`, ja: `• 自分のサイン: 50%` } },
      { type: "paragraph", text: { en: `• Friendly Sign: 25%`, ja: `• フレンドリーサイン: 25%` } },
      { type: "paragraph", text: { en: `• Neutral Sign: 12%`, ja: `• ニュートラルサイン: 12%` } },
      { type: "paragraph", text: { en: `• Fallen/Enemy Sign: 0%`, ja: `• フォールン/敵のサイン: 0%` } },
      { type: "paragraph", text: { en: `These figures should not be interpreted too literally, but they provide a useful illustration of how planetary condition influences its ability to produce positive results.`, ja: `これらの数字はあまり文字通りに解釈すべきではありませんが、惑星の状態がポジティブな結果を生み出す能力にどのような影響を与えるかを示す有益な図を提供します。` } },
      { type: "paragraph", text: { en: `The chart below summarises these relationships.`, ja: `以下の図は、これらの関係をまとめたものです。` } },
      { type: "paragraph", text: { en: `Please remember that the categories of Great Friend and Great Enemy depend upon temporary planetary relationships within a particular chart and are therefore not fixed.`, ja: `偉大な友人と偉大な敵のカテゴリーは、特定のチャート内の一時的な惑星の関係に依存するため、固定されていないことに注意してください。` } },
      { type: "heading", level: 3, text: { en: `Planetary Strengths by Sign Placement – Nine Categories or States in Jyotish`, ja: `星座の配置による惑星の強さ – ジョーティッシュの 9 つのカテゴリーまたは州` } },
      { type: "paragraph", text: { en: `A table showing the relationship between sign placement (Exalted, Own Sign, etc.) and resulting planetary strength in Jyotish Astrology.`, ja: `ジョーティッシュ占星術におけるサインの配置 (Exalted、Own Sign など) とその結果として生じる惑星の強さの関係を示す表。` } },
      { type: "heading", level: 3, text: { en: `Other Factors Which Influence Planetary Strength`, ja: `惑星の強度に影響を与えるその他の要因` } },
      { type: "paragraph", text: { en: `Several additional factors can modify planetary strength.`, ja: `いくつかの追加要因が惑星の強度を変更する可能性があります。` } },
      { type: "paragraph", text: { en: `These include:`, ja: `これらには次のものが含まれます。` } },
      { type: "paragraph", text: { en: `• Retrograde motion`, ja: `• 逆行運動` } },
      { type: "paragraph", text: { en: `• Combustion`, ja: `• 燃焼` } },
      { type: "paragraph", text: { en: `• Planetary War`, ja: `• 惑星戦争` } },
      { type: "paragraph", text: { en: `• Position in divisional charts`, ja: `• 部門別チャートでの位置` } },
      { type: "paragraph", text: { en: `If you are completely new to Jyotish, you may wish to skip this section initially and return to it later.`, ja: `Jotish をまったく初めて使用する場合は、最初はこのセクションをスキップして、後で戻ってくることをお勧めします。` } },
      { type: "heading", level: 3, text: { en: `Effects of Aspects on Planetary Strength`, ja: `惑星の強さに対するアスペクトの影響` } },
      { type: "paragraph", text: { en: `Planets receiving aspects from benefic planets such as Jupiter, Venus, Mercury, and the Moon gain strength. Consequently, both their natural indications and the houses they rule are enhanced.`, ja: `木星、金星、水星、月などの吉星からアスペクトを受けている惑星は力を増します。その結果、彼らの自然な兆候と彼らが統治する家の両方が強化されます。` } },
      { type: "paragraph", text: { en: `Aspects in Jyotish are more sophisticated than those used in Western Astrology.`, ja: `ジョーティッシュのアスペクトは西洋占星術で使用されるアスペクトよりも洗練されています。` } },
      { type: "paragraph", text: { en: `Planets receiving aspects from malefics such as Mars and Saturn become weakened. As a result, their indications and the houses they govern may experience challenges.`, ja: `火星や土星など凶星からのアスペクトを受けている惑星は弱まってしまいます。その結果、彼らの兆候と彼らが統治する家は困難に直面する可能性があります。` } },
      { type: "paragraph", text: { en: `Note: Rahu and Ketu do not cast aspects.`, ja: `注: ラーフとケートゥはアスペクトをキャストしません。` } },
      { type: "heading", level: 3, text: { en: `Effect of Combust Planets in Vedic Astrology`, ja: `ヴェーダ占星術における燃焼惑星の影響` } },
      { type: "paragraph", text: { en: `When a planet comes too close to the Sun, it can become combust, meaning its ability to produce positive results is reduced.`, ja: `惑星が太陽に近づきすぎると、惑星が燃焼する可能性があり、肯定的な結果を生み出す能力が低下することを意味します。` } },
      { type: "paragraph", text: { en: `This negatively affects both its natural indications and the houses it rules.`, ja: `これは、その自然の兆候とそれが統治する家の両方に悪影響を及ぼします。` } },
      { type: "paragraph", text: { en: `Mercury frequently becomes combust because it always remains relatively close to the Sun. Venus also commonly experiences combustion. When Venus appears as the Morning Star before sunrise, it is necessarily positioned fairly close to the Sun.`, ja: `水星は常に太陽に比較的近い位置にあるため、頻繁に燃焼します。金星もよく燃焼を経験します。金星が日の出前に明けの明星として現れるとき、それは必然的に太陽のかなり近くに位置します。` } },
      { type: "paragraph", text: { en: `Generally, combustion occurs when a planet is within approximately 10 to 15 degrees of the Sun. However, the precise range varies according to the planet involved and whether it is moving direct or retrograde.`, ja: `一般に、燃焼は惑星が太陽から約 10 ～ 15 度以内にあるときに発生します。ただし、正確な範囲は、関係する惑星と、それが順行しているか逆行しているかによって異なります。` } },
      { type: "paragraph", text: { en: `Rahu and Ketu never become combust.`, ja: `ラーフとケートゥは決して燃焼しません。` } },
      { type: "paragraph", text: { en: `Therefore, whenever a planet lies very close to the Sun, combustion should be investigated further.`, ja: `したがって、惑星が太陽のすぐ近くにある場合には、燃焼をさらに詳しく調査する必要があります。` } },
      { type: "heading", level: 3, text: { en: `Effect of Retrograde Planets in Jyotish`, ja: `ジョーティッシュにおける逆行惑星の影響` } },
      { type: "paragraph", text: { en: `Another important factor influencing planetary status is retrograde motion.`, ja: `惑星の状態に影響を与えるもう 1 つの重要な要素は、逆行運動です。` } },
      { type: "paragraph", text: { en: `No physical planet actually reverses its orbit around the Sun. However, due to the relative motions of Earth and the planets, they may appear to move backwards against the background of the fixed stars and constellations. This apparent reversal is known as retrograde motion.`, ja: `実際に太陽の周りの軌道を反転する物理的な惑星はありません。ただし、地球と惑星の相対運動により、恒星や星座を背景にそれらが逆に動いているように見える場合があります。この見かけの逆転は、逆行運動として知られています。` } },
      { type: "paragraph", text: { en: `Although astrologers differ somewhat in their interpretations, the general consensus is that retrograde planets gain strength. Since strength is usually regarded as beneficial in Jyotish, retrogression is often viewed positively.`, ja: `占星術師によって解釈が多少異なりますが、逆行する惑星が力を増すというのが一般的な見解です。ジョーティッシュでは通常、強さは有益であると考えられているため、退行はしばしば肯定的に見られます。` } },
      { type: "paragraph", text: { en: `This view is supported by the observation that retrograde planets generally need to move closer to the Sun before combustion occurs.`, ja: `この見解は、逆行惑星は一般に燃焼が起こる前に太陽に近づく必要があるという観察によって裏付けられています。` } },
      { type: "heading", level: 3, text: { en: `Planets with Vargottama Status`, ja: `ヴァルゴッタマステータスを持つ惑星` } },
      { type: "paragraph", text: { en: `Vargottama is another factor that modifies planetary condition.`, ja: `ヴァルゴッタマは惑星の状態を変えるもう一つの要因です。` } },
      { type: "paragraph", text: { en: `Beginners are often advised not to focus heavily on the divisional charts or Vargas. Nevertheless, the Navamsha chart (the ninth divisional chart) is especially important, not only for marriage and partnerships but also for assessing planetary strength.`, ja: `初心者は、部門チャートやバルガスにあまり集中しないようによくアドバイスされます。それにもかかわらず、ナヴァムシャ チャート (9 番目の区分チャート) は、結婚やパートナーシップだけでなく、惑星の強さを評価するためにも特に重要です。` } },
      { type: "paragraph", text: { en: `A planet occupying the same sign in both the main birth chart and the Navamsha chart is said to be Vargottama.`, ja: `メイン出生図とナヴァムシャ図の両方で同じ星座を占める惑星はヴァルゴッタマであると言われています。` } },
      { type: "paragraph", text: { en: `This condition strengthens the planet considerably and is generally regarded as being at least equivalent to Own Sign status.`, ja: `この状態は惑星を大幅に強化し、一般に少なくとも自分の星座のステータスと同等であると見なされます。` } },
      { type: "paragraph", text: { en: `If a planet occupies its exaltation sign or own sign in both charts, its beneficial influence becomes even more powerful.`, ja: `惑星が両方のチャートでその高揚サインまたは独自のサインを占める場合、その有益な影響はさらに強力になります。` } },
      { type: "heading", level: 3, text: { en: `Planetary War in Jyotish`, ja: `ジョーティッシュの惑星戦争` } },
      { type: "paragraph", text: { en: `Planetary War occurs when two or more planets come into extremely close conjunction, usually within approximately one degree of each other.`, ja: `惑星戦争は、2 つ以上の惑星が通常互いに約 1 度以内で非常に接近して結合するときに発生します。` } },
      { type: "paragraph", text: { en: `Most Jyotish texts state that the planet at the lower degree wins the war, while the planet at the higher degree loses some of its ability to produce positive results.`, ja: `ジョーティッシュのテキストのほとんどは、低次数の惑星が戦争に勝つ一方、高次数の惑星は肯定的な結果を生み出す能力の一部を失うと述べています。` } },
      { type: "paragraph", text: { en: `There is little doubt that planets positioned this closely together create significant effects. However, there remains considerable scholarly debate regarding the exact conditions required for Planetary War and the precise outcomes experienced by the planets involved.`, ja: `この近くに位置する惑星が重大な影響を生み出すことにほとんど疑いの余地はありません。しかし、惑星戦争に必要な正確な条件や、関与した惑星が経験した正確な結果については、学術的な議論がまだ残っています。` } },
      { type: "paragraph", text: { en: `Note: The Sun, Moon, Rahu, and Ketu do not participate in Planetary War.`, ja: `注: 太陽、月、ラーフ、ケートゥは惑星戦争には参加しません。` } },
    ],
  },
  {
    id: "chart-formats",
    section: "houses",
    title: { en: `Chart Formats in Jyotish Astrology`, ja: `ジョーティッシュ占星術のチャート形式` },
    related: ["twelve-houses","good-bad-houses","sidereal-zodiac-p3"],
    blocks: [
      { type: "heading", level: 2, text: { en: `Chart Formats in Jyotish Astrology`, ja: `ジョーティッシュ占星術のチャート形式` } },
      { type: "paragraph", text: { en: `Summary: A comparison of the two primary birth-chart formats used in Jyotish Astrology—the North Indian and South Indian systems—along with suggested adaptations for students learning Jyotish. This overview is particularly useful for beginners seeking to understand and interpret Vedic astrology charts.`, ja: `概要: ジョーティッシュ占星術で使用される 2 つの主要な出生図形式、北インド式と南インド式の比較と、ジョーティッシュを学習する学生向けに提案された適応方法。この概要は、ヴェーダ占星術のチャートを理解して解釈しようとしている初心者にとって特に役立ちます。` } },
      { type: "heading", level: 3, text: { en: `North Indian and South Indian Chart Formats Compared`, ja: `北インドと南インドのチャート形式の比較` } },
      { type: "paragraph", text: { en: `Most Western astrologers use a circular horoscope format, but this style of chart is not commonly used in Jyotish.`, ja: `ほとんどの西洋占星術師は円形ホロスコープ形式を使用しますが、この形式のチャートはジョーティッシュでは一般的に使用されません。` } },
      { type: "paragraph", text: { en: `In Vedic Astrology, there are two main chart formats: the North Indian system and the South Indian system. For newcomers to the subject, this can initially be confusing because the charts appear very different from one another. However, both formats display exactly the same astrological information—they simply present it in different ways.`, ja: `ヴェーダ占星術には、北インド システムと南インド システムという 2 つの主要なチャート形式があります。このテーマの初心者にとって、グラフは互いに大きく異なって見えるため、最初は混乱する可能性があります。ただし、どちらの形式でもまったく同じ占星術情報が表示され、単に異なる方法で表示されます。` } },
      { type: "paragraph", text: { en: `The diamond-shaped grid is predominantly used in North India, while the rectangular grid is more commonly used in South India. Both charts shown in the illustration below contain identical astrological data.`, ja: `ダイヤモンド型グリッドは主に北インドで使用され、長方形グリッドは南インドでより一般的に使用されます。以下の図に示されている両方のチャートには、同一の占星術データが含まれています。` } },
      { type: "paragraph", text: { en: `In the North Indian format, the Ascendant is always placed in the upper diamond-shaped section, and the zodiac signs are often numbered from 1 to 12, corresponding to Aries through Pisces. In the example horoscope shown, the Ascendant is in Pisces, the 12th sign, with both Jupiter and Venus positioned in the Ascendant. Rahu is located in Cancer, the 4th sign, which corresponds to the 5th house in this particular chart, and so on.`, ja: `北インドの形式では、アセンダントは常に上部のひし形のセクションに配置され、星座には多くの場合、牡羊座から魚座に対応する 1 から 12 までの番号が付けられます。示されているホロスコープの例では、アセンダントは 12 番目の星座である魚座にあり、木星と金星の両方がアセンダントに位置しています。ラーフは、この特定のチャートでは 5 番目の家に対応する 4 番目の星座である蟹座に位置しています。` } },
      { type: "heading", level: 3, text: { en: `Comparison between North and South Indian Jyotish Chart Formats`, ja: `北インドと南インドのジョーティッシュ チャート形式の比較` } },
      eduImage(educationImages.chartFormatsComparison, {
        en: "Comparison between North Indian and South Indian chart formats",
        ja: "北インド式と南インド式チャート形式の比較",
      }),
      { type: "paragraph", text: { en: `The zodiac signs used in Jyotish have the same names as those found in Western Astrology, such as Aries, Taurus, Gemini, and so forth. However, their actual positions in the sky differ from those used in Western astrology.`, ja: `ジョーティッシュで使用される星座は、牡羊座、おうし座、双子座など、西洋占星術で見られるものと同じ名前です。ただし、実際の空の位置は西洋占星術で使用されるものとは異なります。` } },
      { type: "paragraph", text: { en: `This difference arises because Vedic Astrology references the zodiac signs against the background of the fixed stars and therefore uses the Sidereal Zodiac, whereas Western Astrology generally uses the Tropical Zodiac.`, ja: `この違いは、ヴェーダ占星術では恒星を背景に星座を参照するため恒星黄道帯を使用するのに対し、西洋占星術では一般的に熱帯黄道帯を使用するために生じます。` } },
      { type: "paragraph", text: { en: `At present, there is approximately a 24-degree difference between these two systems. The Tropical Zodiac takes the Spring Equinox as the zero-degree reference point for Aries, but this reference gradually shifts against the fixed stars due to the phenomenon known as the precession of the equinoxes.`, ja: `現在、これら 2 つのシステムの間には約 24 度の差があります。熱帯黄道帯は、春分点を牡羊座の 0 度の基準点としますが、この基準点は、春分点の歳差運動として知られる現象により、恒星に対して徐々に移動します。` } },
      { type: "paragraph", text: { en: `For those beginning their study of Jyotish, I believe a slightly modified version of the South Indian rectangular chart format is generally easier for Western students to understand and work with (see the diagram at the end of this article).`, ja: `ジョーティッシュの学習を始める人にとって、南インドの長方形チャート形式を少し修正したバージョンの方が、西洋の学生にとっては理解しやすく、扱いやすいと私は考えています (この記事の最後にある図を参照)。` } },
      { type: "heading", level: 3, text: { en: `South Indian Jyotish Birth-chart Format`, ja: `南インドのジョーティッシュ出生図形式` } },
      { type: "paragraph", text: { en: `In the South Indian chart system, each zodiac sign always occupies the same fixed position within the chart. For example, Pisces remains in the upper-left box, while Virgo always occupies the lower-right box.`, ja: `南インドのチャート システムでは、各星座は常にチャート内の同じ固定位置を占めます。たとえば、魚座は左上のボックスに残りますが、乙女座は常に右下のボックスを占めます。` } },
      { type: "paragraph", text: { en: `The zodiac signs are counted in a clockwise direction around the rectangular chart: Aries (1), Taurus (2), Gemini (3), Cancer (4), Leo (5), and so on.`, ja: `黄道十二宮は、長方形のチャートを中心に時計回りに数えられます。牡羊座 (1)、おうし座 (2)、双子座 (3)、蟹座 (4)、獅子座 (5) などです。` } },
      { type: "paragraph", text: { en: `The Ascendant is indicated by a single diagonal line placed within the relevant sign. This remains the same regardless of the exact Ascendant degree. For example, an Ascendant at 1° Leo and an Ascendant at 29° Leo are both represented identically.`, ja: `アセンダントは、関連するサイン内に配置された単一の対角線によって示されます。これは、正確なアセンダントの度数に関係なく同じままです。たとえば、獅子座 1 度のアセンダントと獅子座 29 度のアセンダントはどちらも同じように表されます。` } },
      { type: "paragraph", text: { en: `In this system, houses correspond exactly to signs and are counted clockwise from the Ascendant. Thus, if the Ascendant is in Leo—whether at 1 degree or 29 degrees—the entire sign of Leo becomes the 1st house, the whole sign of Virgo becomes the 2nd house, Libra becomes the 3rd house, and so forth.`, ja: `このシステムでは、ハウスはサインに正確に対応し、アセンダントから時計回りに数えられます。したがって、アセンダントが獅子座にある場合、1度でも29度でも、獅子座全体が第1室となり、乙女座全体が第2室、天秤座が第3室、というようになります。` } },
      { type: "heading", level: 3, text: { en: `South Indian Vedic Astrology Chart Format`, ja: `南インドのヴェーダ占星術チャートの形式` } },
      eduImage(educationImages.southIndianChart, {
        en: "South Indian Vedic chart format",
        ja: "南インド式ヴェーダチャート形式",
      }),
    ],
  },
  {
    id: "twelve-houses",
    section: "houses",
    title: { en: `The Twelve Houses and Their Indications`, ja: `12ハウスとその暗示` },
    related: ["good-bad-houses","planetary-strengths","chart-formats"],
    blocks: [
      { type: "heading", level: 2, text: { en: `The Twelve Houses and Their Indications`, ja: `12ハウスとその暗示` } },
      { type: "paragraph", text: { en: `Summary: Covers the primary indications of each of the Twelve Houses in Vedic Astrology, together with explanatory notes and House Classifications.`, ja: `概要: ヴェーダ占星術の各 12 ハウスの主な兆候を、説明メモとハウス分類とともに取り上げます。` } },
      { type: "paragraph", text: { en: `This section is essential reading for students of Jyotish, as it outlines the principal areas of life governed by each of the twelve houses.`, ja: `このセクションは、12 ハウスのそれぞれが支配する生活の主な分野について概説しているため、ジョーティッシュの学生にとって必読の書です。` } },
      { type: "paragraph", text: { en: `Jyotish divides the 360 degrees of the sky into twelve equal sections, each measuring 30 degrees. These divisions create the twelve houses used in Vedic Astrology. Jyotish always employs the Sidereal Zodiac.`, ja: `ジョーティッシュは、空の 360 度を 30 度ずつ 12 等分に分割します。これらの区分は、ヴェーダ占星術で使用される 12 ハウスを作成します。ジョーティッシュは常に恒星黄道帯を採用します。` } },
      { type: "paragraph", text: { en: `Each house governs specific areas of life. Further details regarding the primary significations of the houses can be found in the article The Twelve Houses. Most chart interpretations in Jyotish are based upon a house-by-house examination.`, ja: `各ハウスは生活の特定の領域を統治します。ハウスの主な意味に関する詳細については、「The Twelve Houses」の記事を参照してください。ジョーティッシュにおけるほとんどのチャート解釈は、ハウスごとの検査に基づいています。` } },
      { type: "image", src: "/assets/001.jpeg", alt: { en: `Equal House diagram in Jyotish`, ja: `ジョーティッシュのイコールハウス図` } },
      { type: "paragraph", text: { en: `Most chart interpretations are conducted on a house-by-house basis, making a sound understanding of the houses and their indications absolutely essential.`, ja: `チャートの解釈のほとんどはハウスごとに行われるため、ハウスとその指標をしっかりと理解することが不可欠です。` } },
      { type: "paragraph", text: { en: `Traditional Jyotish texts often provide extensive lists of matters associated with each house. However, in this article, I have attempted to remain concise and focus on the most important indications.`, ja: `伝統的なジョーティッシュのテキストには、各家に関連する事項の広範なリストが記載されていることがよくあります。ただし、この記事では簡潔さを保ち、最も重要な兆候に焦点を当てるように努めました。` } },
      { type: "heading", level: 3, text: { en: `First House – ‘House of Body’`, ja: `最初の家 – 「身体の家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Birth and early childhood`, ja: `• 誕生と幼少期` } },
      { type: "paragraph", text: { en: `• Health, physical body, and vitality`, ja: `・健康、肉体、活力` } },
      { type: "paragraph", text: { en: `• Personality and temperament`, ja: `• 性格と気質` } },
      { type: "paragraph", text: { en: `• Self-confidence and self-esteem`, ja: `• 自信と自尊心` } },
      { type: "paragraph", text: { en: `• Prosperity and fame`, ja: `• 繁栄と名声` } },
      { type: "paragraph", text: { en: `• Dharma – actions and activities that promote spiritual evolution`, ja: `• ダルマ – 霊的進化を促進する行動と活動` } },
      { type: "paragraph", text: { en: `The 1st house governs several key areas of life, and a strong [1] first house tends to improve the overall quality of the horoscope.`, ja: `第 1 ハウスは人生のいくつかの重要な領域を支配しており、強い [1] の第 1 ハウスはホロスコープ全体の質を向上させる傾向があります。` } },
      { type: "paragraph", text: { en: `It represents the self and all matters connected with our identity. The ruler of the 1st house plays a major role in shaping our personality, behaviour, and natural tendencies.`, ja: `それは自己と、私たちのアイデンティティに関連するすべての事項を表します。第 1 ハウスの支配者は、私たちの性格、行動、自然な傾向の形成に大きな役割を果たします。` } },
      { type: "paragraph", text: { en: `House Classification: Kendra / Dharma (Angular House / Action)`, ja: `ハウス分類: ケンドラ / ダーマ (角のあるハウス / アクション)` } },
      { type: "paragraph", text: { en: `House Indicator [2]: Sun`, ja: `ハウスインジケーター [2]: 太陽` } },
      { type: "heading", level: 3, text: { en: `Second House – ‘House of Wealth’`, ja: `セカンドハウス – 「富の家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Accumulated wealth and finances`, ja: `• 蓄積された富と財政` } },
      { type: "paragraph", text: { en: `• Speech and verbal communication`, ja: `• スピーチと口頭コミュニケーション` } },
      { type: "paragraph", text: { en: `• Family life`, ja: `• 家族生活` } },
      { type: "paragraph", text: { en: `The 2nd house is the principal indicator of the wealth and financial resources we accumulate throughout life.`, ja: `2ハウスは、私たちが生涯を通じて蓄積する富と財源の主な指標です。` } },
      { type: "paragraph", text: { en: `It is also closely associated with speech and verbal expression, making it important in matters relating to education and communication.`, ja: `また、スピーチや言語表現とも密接に関連しているため、教育やコミュニケーションに関連する問題において重要です。` } },
      { type: "paragraph", text: { en: `House Classification: Artha (Wealth)`, ja: `ハウス分類: Artha (富裕層)` } },
      { type: "paragraph", text: { en: `House Indicator: Jupiter`, ja: `ハウスインジケーター: 木星` } },
      { type: "heading", level: 3, text: { en: `Third House – ‘House of Brothers, Sisters and Desires’`, ja: `第三の家 – 「兄弟、姉妹、そして欲望の家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Brothers and sisters`, ja: `• 兄弟姉妹` } },
      { type: "paragraph", text: { en: `• Desires and ambitions`, ja: `• 願望と野心` } },
      { type: "paragraph", text: { en: `• Courage`, ja: `• 勇気` } },
      { type: "paragraph", text: { en: `• Personal effort and initiative`, ja: `• 個人の努力と自発性` } },
      { type: "paragraph", text: { en: `• Communication`, ja: `• コミュニケーション` } },
      { type: "paragraph", text: { en: `A favourable 3rd house brings happiness through brothers and sisters. Siblings may be supportive and beneficial, and relationships with them are often harmonious. Some astrologers restrict the indications of the 3rd house specifically to younger siblings.`, ja: `有利な3ハウスは兄弟姉妹を通じて幸福をもたらします。兄弟姉妹は協力的で有益な場合があり、兄弟関係はしばしば調和が取れています。一部の占星術師は、3 ハウスの表示を特に若い兄弟に限定しています。` } },
      { type: "paragraph", text: { en: `The 3rd is an Upachaya, or "growing" house, where malefic planets [4] generally perform well unless debilitated or otherwise weakened.`, ja: `3 番目はウパチャヤ、または「成長する」ハウスで、ここでは凶星 [4] が衰弱したり弱体化したりしない限り、一般に良好なパフォーマンスを示します。` } },
      { type: "paragraph", text: { en: `House Classification: Upachaya / Kama (Growing House / Desire)`, ja: `ハウス分類: ウパチャヤ / カマ (成長する家 / 欲望)` } },
      { type: "paragraph", text: { en: `House Indicator: Mars`, ja: `ハウスインジケーター: 火星` } },
      { type: "heading", level: 3, text: { en: `Fourth House – ‘House of Happiness and Comforts’`, ja: `第 4 の家 – 「幸福と安らぎの家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Happiness and comforts`, ja: `• 幸福と快適さ` } },
      { type: "paragraph", text: { en: `• The affairs, well-being, and relationship with our mother`, ja: `• 事情、幸福、そして母親との関係` } },
      { type: "paragraph", text: { en: `• Fixed assets such as property, land, and buildings`, ja: `• 不動産、土地、建物などの固定資産` } },
      { type: "paragraph", text: { en: `• Friends and relatives`, ja: `• 友人や親戚` } },
      { type: "paragraph", text: { en: `The 4th house governs the home environment and our mother. The condition of the Moon also provides important information regarding the mother's well-being.`, ja: `4ハウスは家庭環境と母親を支配します。月の状態は、母親の健康に関する重要な情報も提供します。` } },
      { type: "paragraph", text: { en: `This house reflects our overall level of happiness, contentment, and satisfaction in life, whether physical, emotional, spiritual, or financial.`, ja: `この家は、身体的、感情的、精神的、経済的など、人生における幸福、満足感、満足度の全体的なレベルを反映しています。` } },
      { type: "paragraph", text: { en: `House Classification: Kendra / Moksha (Angular / Liberation)`, ja: `ハウス分類: ケンドラ / モクシャ (角度 / 解放)` } },
      { type: "paragraph", text: { en: `House Indicator: Moon`, ja: `ハウスインジケーター: 月` } },
      { type: "heading", level: 3, text: { en: `Fifth House – ‘House of Children’`, ja: `フィフスハウス – 「子どもの家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Children, intelligence, education, and the mind`, ja: `• 子供、知性、教育、そして精神` } },
      { type: "paragraph", text: { en: `• Spiritual practices and religious knowledge`, ja: `• 精神的な実践と宗教的知識` } },
      { type: "paragraph", text: { en: `• Past-life credit (positive returning karmas)`, ja: `• 過去生のクレジット（ポジティブに戻ってくるカルマ）` } },
      { type: "paragraph", text: { en: `• Investment and speculation`, ja: `• 投資と投機` } },
      { type: "paragraph", text: { en: `The 5th house rules children and provides information regarding offspring, their number, and the happiness they bring into our lives.`, ja: `5室は子供を支配し、子孫、その数、そして彼らが私たちの生活にもたらす幸福に関する情報を提供します。` } },
      { type: "paragraph", text: { en: `It also governs intelligence, common sense, learning ability, and education.`, ja: `また、知性、常識、学習能力、教育も司ります。` } },
      { type: "paragraph", text: { en: `A strong 5th house is frequently found in the charts of virtuous individuals who have made significant spiritual or personal progress.`, ja: `強力な 5 ハウスは、精神的または個人的に重要な進歩を遂げた高潔な個人のチャートによく見られます。` } },
      { type: "paragraph", text: { en: `The 5th is considered a highly auspicious house, and planets occupying it generally benefit from the placement.`, ja: `5 番目は非常に縁起の良いハウスと考えられており、そこに位置する惑星は一般にその配置から恩恵を受けます。` } },
      { type: "paragraph", text: { en: `House Classification: Trikona / Dharma (Trinal / Action)`, ja: `ハウス分類: トリコナ / ダルマ (トリナル / アクション)` } },
      { type: "paragraph", text: { en: `House Indicator: Jupiter`, ja: `ハウスインジケーター: 木星` } },
      { type: "heading", level: 3, text: { en: `Sixth House – ‘House of Enemies’`, ja: `第 6 ハウス – 「敵の家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Enemies, competitors, jealous individuals, work subordinates, and obstacles`, ja: `• 敵、競争相手、嫉妬深い人、仕事の部下、障害物` } },
      { type: "paragraph", text: { en: `• Illness and disease`, ja: `• 病気と疾病` } },
      { type: "paragraph", text: { en: `• Worries and anxieties`, ja: `• 心配や不安` } },
      { type: "paragraph", text: { en: `In this context, "enemies" can include competitors or people who may rise to a higher status than us within an organisation.`, ja: `この文脈での「敵」には、競合他社や、組織内で私たちよりも高い地位に昇進する可能性のある人々が含まれる場合があります。` } },
      { type: "paragraph", text: { en: `A powerful 6th house often enables a person to excel and reach the top of their chosen profession.`, ja: `強力な6ハウスは、多くの場合、人が優れた能力を発揮し、選択した職業のトップに到達することを可能にします。` } },
      { type: "paragraph", text: { en: `The 6th is another Upachaya or growing house, meaning that the problems it indicates can improve with time. For example, a health issue shown by the 6th house may be present during childhood but disappear later in life.`, ja: `6番目は、別のウパチャヤまたは成長する家であり、それが示す問題は時間の経過とともに改善される可能性があることを意味します。たとえば、6 ハウスによって示される健康上の問題は、幼少期に存在する可能性がありますが、人生の後半には消失します。` } },
      { type: "paragraph", text: { en: `Malefic planets and their natural significations generally function reasonably well in the 6th house.`, ja: `凶星とその自然の意味は、一般的に 6 室で適度に機能します。` } },
      { type: "paragraph", text: { en: `However, the houses ruled by planets occupying the 6th are often disturbed to some extent.`, ja: `ただし、6番目に位置する惑星が支配するハウスは、ある程度乱れることがよくあります。` } },
      { type: "paragraph", text: { en: `House Classification: Dusthana / Upachaya / Artha (Negative / Growing / Wealth)`, ja: `ハウス分類: ダスターナ / ウパチャヤ / アルタ (ネガティブ / 成長 / 富)` } },
      { type: "paragraph", text: { en: `House Indicator: Mars`, ja: `ハウスインジケーター: 火星` } },
      { type: "heading", level: 3, text: { en: `Seventh House – ‘House of Marriage and Partnerships’`, ja: `7番目の家 – 「結婚とパートナーシップの家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Marriage and married life`, ja: `• 結婚と結婚生活` } },
      { type: "paragraph", text: { en: `• Spouse or partner`, ja: `• 配偶者またはパートナー` } },
      { type: "paragraph", text: { en: `• Sexual passions`, ja: `• 性的情熱` } },
      { type: "paragraph", text: { en: `• Partnerships of all kinds, including business partnerships`, ja: `• ビジネスパートナーシップを含むあらゆる種類のパートナーシップ` } },
      { type: "paragraph", text: { en: `The 7th house reveals the quality of married life and the well-being of one's partner.`, ja: `7 ハウスは、結婚生活の質とパートナーの幸福を示します。` } },
      { type: "paragraph", text: { en: `Additional insights regarding marriage can be obtained by treating the Moon's sign as the Ascendant and examining the planets located in the 7th house from the Moon.`, ja: `結婚に関するさらなる洞察は、月の星座をアセンダントとして扱い、月から7番目の家に位置する惑星を調べることによって得ることができます。` } },
      { type: "paragraph", text: { en: `A strong Navamsa chart [5] is highly beneficial for relationships and marriage.`, ja: `強力なナヴァムサ チャート [5] は、恋愛や結婚に非常に有益です。` } },
      { type: "paragraph", text: { en: `The 7th house also governs certain aspects of travel.`, ja: `7 ハウスは旅行の特定の側面も支配します。` } },
      { type: "paragraph", text: { en: `House Classification: Kendra / Kama (Angular / Desire)`, ja: `ハウス分類: ケンドラ / カマ (角度 / 欲望)` } },
      { type: "paragraph", text: { en: `House Indicator: Venus`, ja: `ハウスインジケーター: 金星` } },
      { type: "heading", level: 3, text: { en: `Eighth House – ‘House of Transformation’`, ja: `第8ハウス – 「変革の家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Life, longevity, and death`, ja: `• 生命、長寿、そして死` } },
      { type: "paragraph", text: { en: `• Wills, inheritances, and legacies`, ja: `• 遺言、相続、遺産` } },
      { type: "paragraph", text: { en: `• Intuition, occult studies, and hidden knowledge`, ja: `• 直感、オカルト研究、隠された知識` } },
      { type: "paragraph", text: { en: `• Secret and esoteric subjects`, ja: `• 秘密および難解な主題` } },
      { type: "paragraph", text: { en: `The 8th house is often referred to as the "House of Death" because it governs the nature and circumstances surrounding death.`, ja: `8 ハウスは、死を取り巻く性質や状況を支配するため、「死の家」と呼ばれることがあります。` } },
      { type: "paragraph", text: { en: `However, a strong 8th house, particularly when supported by a well-placed Saturn, can indicate a long, active, and energetic life.`, ja: `しかし、強い 8 ハウスは、特に適切な位置にある土星にサポートされている場合、長く、活動的で、エネルギッシュな人生を示す可能性があります。` } },
      { type: "paragraph", text: { en: `The 8th is also a Moksha house and often stimulates interest in personal transformation and spiritual growth.`, ja: `8 番目はモクシャハウスでもあり、個人の変革と精神的な成長への関心を刺激することがよくあります。` } },
      { type: "paragraph", text: { en: `According to some astrologers, it additionally governs chronic illnesses, long-term mental and physical conditions, and sexually transmitted diseases.`, ja: `占星術師の中には、慢性疾患、長期にわたる精神的および身体的状態、性感染症も司るという人もいます。` } },
      { type: "paragraph", text: { en: `The 8th generally weakens planets occupying it (although exceptions exist), along with the houses ruled by those planets.`, ja: `8番目は一般に、それを占める惑星（例外はありますが）と、それらの惑星が支配するハウスを弱体化させます。` } },
      { type: "paragraph", text: { en: `House Classification: Dusthana / Moksha (Negative / Liberation)`, ja: `ハウス分類: ダスターナ / モクシャ (ネガティブ / 解放)` } },
      { type: "paragraph", text: { en: `House Indicator: Saturn`, ja: `ハウスインジケーター: 土星` } },
      { type: "heading", level: 3, text: { en: `Ninth House – ‘House of Fortune’`, ja: `9番目の家 – 「運命の家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Luck, fortune, and prosperity`, ja: `• 幸運、富、繁栄` } },
      { type: "paragraph", text: { en: `• Religion, faith, worship, spiritual teachers, law, and higher knowledge`, ja: `• 宗教、信仰、崇拝、精神的な教師、法律、および高度な知識` } },
      { type: "paragraph", text: { en: `• Certain aspects of the relationship with one's father`, ja: `• 父親との関係の特定の側面` } },
      { type: "paragraph", text: { en: `• Pilgrimages and long-distance travel`, ja: `• 巡礼と長距離旅行` } },
      { type: "paragraph", text: { en: `The 9th house is of equal importance to the 1st house.`, ja: `9ハウスは1ハウスと同じくらい重要です。` } },
      { type: "paragraph", text: { en: `It primarily signifies luck, fortune, and blessings in life.`, ja: `それは主に人生における幸運、幸運、祝福を意味します。` } },
      { type: "paragraph", text: { en: `The 9th is generally regarded as the most auspicious house in the horoscope. Planets placed here tend to perform exceptionally well, and the ruler of the 9th carries a highly positive energy wherever it is located.`, ja: `9 室は一般に星占いで最も縁起の良い家とみなされています。ここに配置された惑星は非常に優れたパフォーマンスを発揮する傾向があり、9 番目の支配者はどこに配置されても非常にポジティブなエネルギーを運びます。` } },
      { type: "paragraph", text: { en: `Some astrologers associate past-life credit more strongly with the 9th house than with the 5th.`, ja: `占星術師の中には、過去世の功績を、5 室よりも 9 室と強く結び付ける人もいます。` } },
      { type: "paragraph", text: { en: `A strong 9th house can bestow tremendous good fortune and a sense of divine grace.`, ja: `強い9ハウスは、途方もない幸運と神の恵みの感覚を与えることができます。` } },
      { type: "paragraph", text: { en: `A person's relationship with their spiritual teacher is seen through the 9th house. Traditionally in India, the father often fulfilled this role during childhood before a spiritual guru was encountered later in life. Consequently, some aspects of the father-child relationship are also examined through the 9th house.`, ja: `精神的な教師との関係は、9 ハウスを通して見られます。インドでは伝統的に、父親が幼少期にこの役割を果たし、その後、霊的な指導者に出会うことがよくありました。したがって、父と子の関係のいくつかの側面も、9 ハウスを通じて検査されます。` } },
      { type: "paragraph", text: { en: `House Classification: Trikona / Dharma (Trinal / Action)`, ja: `ハウス分類: トリコナ / ダルマ (トリナル / アクション)` } },
      { type: "paragraph", text: { en: `House Indicator: Jupiter`, ja: `ハウスインジケーター: 木星` } },
      { type: "heading", level: 3, text: { en: `Tenth House – ‘House of Status and Power’`, ja: `第10ハウス – 「地位と権力のハウス」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Career, status, and reputation`, ja: `• キャリア、地位、評判` } },
      { type: "paragraph", text: { en: `• Fame and professional achievement`, ja: `• 名声と職業上の業績` } },
      { type: "paragraph", text: { en: `• Authority figures, government officials, and institutions`, ja: `• 権威者、政府関係者、および機関` } },
      { type: "paragraph", text: { en: `• The status, authority, and influence of the father`, ja: `• 父親の地位、権威、影響力` } },
      { type: "paragraph", text: { en: `The 10th house indicates the degree of success, recognition, and professional standing we may achieve in our chosen career.`, ja: `10ハウスは、私たちが選択したキャリアで達成できる成功、評価、専門的地位の程度を示します。` } },
      { type: "paragraph", text: { en: `It is an Upachaya or growing house, where malefic planets can perform well, provided they are not debilitated or adversely affected.`, ja: `それはウパチャヤまたは成長ハウスであり、弱体化または悪影響を受けない限り、凶星がうまく機能できる場所です。` } },
      { type: "paragraph", text: { en: `Many important factors relating to a person's father are also assessed from the 10th house.`, ja: `人の父親に関する多くの重要な要素も、10 ハウスから評価されます。` } },
      { type: "paragraph", text: { en: `House Classification: Kendra / Upachaya / Artha (Angular / Growing / Wealth)`, ja: `ハウス分類: ケンドラ / ウパチャヤ / アーサ (角張った / 成長 / 富)` } },
      { type: "paragraph", text: { en: `House Indicator: Mercury`, ja: `ハウスインジケーター: 水星` } },
      { type: "heading", level: 3, text: { en: `Eleventh House – ‘House of Gains, Profits and Desires’`, ja: `11番目の家 – 「利益、利益、欲望の家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Gains, profits, and income`, ja: `• 利益、利益、収入` } },
      { type: "paragraph", text: { en: `• Desires, wishes, ambitions, and opportunities`, ja: `• 願望、希望、野心、機会` } },
      { type: "paragraph", text: { en: `The 11th house differs from the 2nd in that it governs gains and profits obtained by any means. Therefore, even if the 2nd house is weak, substantial income may still be generated, although this does not necessarily result in accumulated wealth.`, ja: `11ハウスは、何らかの手段で得た利得や利益を司るという点で2ハウスとは異なります。したがって、2ハウスが弱くても、必ずしも富の蓄積につながるわけではありませんが、かなりの収入が得られる可能性があります。` } },
      { type: "paragraph", text: { en: `The 11th house governs the fulfilment of major desires and ambitions. A strong 11th brings opportunities that enable a person to realise their goals.`, ja: `11室は主要な願望や野心の実現を支配します。強い11は、人が自分の目標を実現できる機会をもたらします。` } },
      { type: "paragraph", text: { en: `Like other Upachaya houses, malefic planets can eventually produce favourable results here.`, ja: `他のウパチャヤハウスと同様に、凶星はここでも最終的に好ましい結果を生み出す可能性があります。` } },
      { type: "paragraph", text: { en: `House Classification: Upachaya / Kama (Growing / Desire)`, ja: `ハウス分類: ウパチャヤ / カーマ (成長 / 欲望)` } },
      { type: "paragraph", text: { en: `House Indicator: Jupiter`, ja: `ハウスインジケーター: 木星` } },
      { type: "heading", level: 3, text: { en: `Twelfth House – ‘House of Loss and Expenditure’`, ja: `12番目の家 – 「損失と支出の家」` } },
      { type: "heading", level: 3, text: { en: `House Indications:`, ja: `ハウスの表示:` } },
      { type: "paragraph", text: { en: `• Expenditure, financial loss, and waste`, ja: `• 支出、経済的損失、無駄` } },
      { type: "paragraph", text: { en: `• Misfortune`, ja: `• 不幸` } },
      { type: "paragraph", text: { en: `• Salvation, liberation, and enlightenment`, ja: `• 救い、解放、啓発` } },
      { type: "paragraph", text: { en: `• Journeys to distant lands`, ja: `• 遠い国への旅` } },
      { type: "paragraph", text: { en: `The 12th house governs all forms of loss and expenditure.`, ja: `12室はあらゆる形態の損失と支出を管理します。` } },
      { type: "paragraph", text: { en: `A strong 12th house helps preserve and protect accumulated wealth.`, ja: `強い12ハウスは、蓄積された富を維持し、保護するのに役立ちます。` } },
      { type: "paragraph", text: { en: `It also indicates progress toward higher states of consciousness, spiritual development, and eventual enlightenment.`, ja: `また、より高い意識状態、精神的な発達、そして最終的な悟りに向けた進歩も示しています。` } },
      { type: "paragraph", text: { en: `Planets placed here are generally weakened (although there are exceptions), and the houses they rule may also be adversely affected.`, ja: `ここに配置された惑星は（例外もありますが）一般に弱体化し、支配するハウスにも悪影響が及ぶ可能性があります。` } },
      { type: "paragraph", text: { en: `House Classification: Dusthana / Moksha (Negative / Liberation)`, ja: `ハウス分類: ダスターナ / モクシャ (ネガティブ / 解放)` } },
      { type: "paragraph", text: { en: `House Indicator: Saturn`, ja: `ハウスインジケーター: 土星` } },
      { type: "heading", level: 3, text: { en: `Parts of the Body Associated with Each House`, ja: `各家に関係する体の部位` } },
      { type: "paragraph", text: { en: `Each house corresponds to a particular part of the body. When a house is significantly weakened, it may indicate potential health issues affecting the related area of the physiology.`, ja: `各ハウスは体の特定の部分に対応します。家が著しく弱っている場合、生理機能の関連領域に影響を与える潜在的な健康上の問題を示している可能性があります。` } },
      { type: "table", headers: [{ en: `House`, ja: `ハウス` }, { en: `Part of Body`, ja: `身体部位` }], rows: [
        [{ en: `1`, ja: `1` }, { en: `Head`, ja: `頭` }],
        [{ en: `2`, ja: `2` }, { en: `Eyes, face, mouth, upper throat`, ja: `目、顔、口、喉上部` }],
        [{ en: `3`, ja: `3` }, { en: `Arms, shoulders, lower throat`, ja: `腕、肩、喉下部` }],
        [{ en: `4`, ja: `4` }, { en: `Chest, heart`, ja: `胸、心臓` }],
        [{ en: `5`, ja: `5` }, { en: `Stomach`, ja: `胃` }],
        [{ en: `6`, ja: `6` }, { en: `Region of the navel`, ja: `へそ周辺` }],
        [{ en: `7`, ja: `7` }, { en: `Body below the waist`, ja: `腰から下の体` }],
        [{ en: `8`, ja: `8` }, { en: `Reproductive organs, anus`, ja: `生殖器、肛門` }],
        [{ en: `9`, ja: `9` }, { en: `Hips, thighs`, ja: `腰、太もも` }],
        [{ en: `10`, ja: `10` }, { en: `Knees`, ja: `膝` }],
        [{ en: `11`, ja: `11` }, { en: `Calves`, ja: `ふくらはぎ` }],
        [{ en: `12`, ja: `12` }, { en: `Feet`, ja: `足` }],
      ] },
      { type: "heading", level: 3, text: { en: `House Classification`, ja: `住宅の分類` } },
      { type: "paragraph", text: { en: `Houses 5 and 9 (Trikona) are regarded as exceptionally auspicious. Planets placed in these houses become strengthened, and the houses they rule also benefit from their placement in the 5th or 9th.`, ja: `ハウス 5 ​​と 9 (トリコナ) は、非常に縁起が良いと考えられています。これらのハウスに配置された惑星は強化され、それらが支配するハウスも5室または9室に配置されることで恩恵を受けます。` } },
      { type: "paragraph", text: { en: `In addition, the rulers of the 5th and 9th houses—even if naturally malefic planets such as Saturn—become functional benefics and carry a positive influence wherever they are placed.`, ja: `さらに、5 室と 9 室の支配星は、たとえ土星のような本来的に凶星であっても、機能的な恩恵をもたらし、どこに配置されてもポジティブな影響を及ぼします。` } },
      { type: "paragraph", text: { en: `Houses 6, 8, and 12 (Dusthana) are considered challenging houses. Planets occupying them tend to become weakened, and the houses ruled by those planets may also suffer.`, ja: `ハウス 6、8、12 (ダスターナ) は、難しいハウスとみなされます。それらを占める惑星は弱くなる傾向があり、それらの惑星によって支配される家も苦しむ可能性があります。` } },
      { type: "paragraph", text: { en: `The rulers of the 6th, 8th, and 12th houses often create difficulties somewhere in the chart, even if they are naturally benefic planets such as Jupiter. This generally applies unless the planet also rules one of the auspicious houses, namely the 5th or 9th.`, ja: `6、8、12 ハウスの支配星は、たとえ木星のような本来的に有益な惑星であっても、チャートのどこかに困難を引き起こすことがよくあります。これは、惑星が縁起の良いハウス、つまり 5 室または 9 室のいずれかを支配している場合を除いて、一般的に当てはまります。` } },
      { type: "paragraph", text: { en: `Houses 3, 6, 10, and 11 form the special category known as Upachaya or "growing" houses. Malefic planets tend to perform well in these houses and eventually produce beneficial results. Difficulties indicated by these houses often diminish with time.`, ja: `ハウス 3、6、10、および 11 は、ウパチャヤまたは「成長する」ハウスとして知られる特別なカテゴリーを形成します。凶星はこれらのハウスでうまく機能し、最終的には有益な結果を生み出す傾向があります。これらのハウスが示す困難は、時間の経過とともに軽減されることがよくあります。` } },
      { type: "paragraph", text: { en: `Houses 1, 4, 7, and 10 are known as Kendras or angular houses. Planets placed within them are strengthened.`, ja: `ハウス 1、4、7、および 10 は、ケンドラまたは角のあるハウスとして知られています。その中に配置された惑星は強化されます。` } },
      { type: "paragraph", text: { en: `The houses are also grouped into repeating cycles of four:`, ja: `ハウスは、次の 4 つの繰り返しサイクルにもグループ化されます。` } },
      { type: "paragraph", text: { en: `• Dharma (Duty and evolutionary action)`, ja: `• ダルマ（義務と進化的行動）` } },
      { type: "paragraph", text: { en: `• Artha (Wealth)`, ja: `• アーサ（富）` } },
      { type: "paragraph", text: { en: `• Kama (Desire)`, ja: `• カーマ (欲望)` } },
      { type: "paragraph", text: { en: `• Moksha (Liberation)`, ja: `• モクシャ (解放)` } },
      { type: "paragraph", text: { en: `This pattern begins with the 1st house and repeats throughout the horoscope. Thus, the 5th house is Dharma, the 6th Artha, the 7th Kama, the 8th Moksha, and the cycle repeats again through the 9th to the 12th houses.`, ja: `このパターンは第 1 ハウスから始まり、ホロスコープ全体で繰り返されます。したがって、５室はダルマ、６室はアルタ、７室はカーマ、８室はモクシャであり、このサイクルは９室から１２室まで再び繰り返される。` } },
      { type: "heading", level: 3, text: { en: `Footnotes`, ja: `脚注` } },
      { type: "paragraph", text: { en: `[1] When we describe a house as "strong," we are considering factors such as the strength and status of the ruling planet (for example, Exalted or Own Sign status), the house occupied by the ruler (for example, placement in the auspicious 9th house), benefic planets occupying the house, and positive aspects from natural benefics such as Jupiter.`, ja: `[1] 私たちがハウスを「強い」と表現するとき、支配星の強さとステータス (例えば、高揚または自身のサインのステータス)、支配星が占有するハウス (例えば、縁起の良い 9 ハウスへの配置)、ハウスを占有する恩恵を受ける惑星、および木星などの自然の恩恵をもたらすポジティブな側面などの要素を考慮します。` } },
      { type: "paragraph", text: { en: `[2] We can further evaluate a house by examining the condition and well-being of its indicator planet. While this is generally less important than factors such as the house ruler, occupying planets, and aspects, it can still modify our interpretation. The natural significations of the indicator planet often correspond closely with the affairs of the house. For example, Venus naturally signifies love, affection, and passion, which aligns well with the 7th house and its association with marriage and partnerships.`, ja: `[2] 指標となる惑星の状態と幸福度を調べることで、住宅をさらに評価することができます。これは一般に、ハウスルーラー、占有惑星、アスペクトなどの要素ほど重要ではありませんが、それでも解釈を変更する可能性があります。指標惑星の自然な意味は、家の事柄と密接に対応していることがよくあります。たとえば、金星は本来、愛、愛情、情熱を表し、7 ハウスと結婚やパートナーシップとの関連性とよく一致します。` } },
    ],
  }
];
