import type { WisdomArticle } from "./types";

/** Articles sourced verbatim from temp-content/p5.txt (link-scrubbed, headings normalized) */
export const p5Articles: WisdomArticle[] = [
  {
    id: "good-bad-houses",
    section: "houses",
    title: { en: `‘Good’ and ‘Bad’ Houses in Jyotish`, ja: `ジョーティッシュの「良い」家と「悪い」家` },
    related: ["twelve-houses","functional-benefics-malefics","planetary-strengths"],
    blocks: [
      { type: "heading", level: 2, text: { en: `‘Good’ and ‘Bad’ Houses in Jyotish`, ja: `ジョーティッシュの「良い」家と「悪い」家` } },
      { type: "paragraph", text: { en: `Summary: Covering the Equal House concept in Jyotish together with an analysis of ‘Good’ and ‘Bad’ houses, including discussions on Kendra, Trikona, Dusthana, and Upachaya houses.`, ja: `概要: ケンドラ、トリコナ、ダスタナ、ウパチャヤ ハウスに関する議論を含む、ジョーティッシュ語の平等ハウスの概念を「良い」ハウスと「悪い」ハウスの分析とともに取り上げます。` } },
      { type: "heading", level: 3, text: { en: `The Equal House Concept`, ja: `イコールハウスの考え方` } },
      { type: "paragraph", text: { en: `Jyotish divides the 360 degrees of the sky into twelve equal sections, each measuring 30 degrees. These divisions create the twelve houses used in Vedic Astrology. Jyotish always employs the Sidereal Zodiac.`, ja: `ジョーティッシュは、空の 360 度を 30 度ずつ 12 等分に分割します。これらの区分は、ヴェーダ占星術で使用される 12 ハウスを作成します。ジョーティッシュは常に恒星黄道帯を採用します。` } },
      { type: "paragraph", text: { en: `Each house governs specific areas of life. Further details regarding the primary significations of the houses can be found in the article The Twelve Houses. Most chart interpretations in Jyotish are based upon a house-by-house examination.`, ja: `各ハウスは生活の特定の領域を統治します。ハウスの主な意味に関する詳細については、「The Twelve Houses」の記事を参照してください。ジョーティッシュにおけるほとんどのチャート解釈は、ハウスごとの検査に基づいています。` } },
      { type: "paragraph", text: { en: `In Jyotish, each of the twelve houses corresponds exactly to a particular sign. As a result, a house can never overlap two zodiac signs in Vedic Astrology.`, ja: `ジョーティッシュでは、12 ハウスのそれぞれが特定の星座に正確に対応します。その結果、ヴェーダ占星術では、ハウスが 2 つの星座に重なることはありません。` } },
      { type: "paragraph", text: { en: `Western Astrology generally begins the first house at the exact degree of the Ascendant. Jyotish follows a different approach. In Vedic Astrology, the entire sign containing the Ascendant becomes the first house, regardless of the Ascendant's exact degree position.[1]`, ja: `西洋占星術では通常、アセンダントの正確な度数で最初のハウスが始まります。ジョーティッシュは別のアプローチを取ります。ヴェーダ占星術では、アセンダントの正確な度数の位置に関係なく、アセンダントを含むサイン全体が最初のハウスになります。[1]` } },
      { type: "paragraph", text: { en: `Therefore, if the Ascendant is located at 1 degree Leo, 29 degrees Leo, or anywhere in between, the whole sign of Leo becomes the first house. The second house corresponds entirely with Virgo, the third with Libra, and so on. The house containing the Ascendant is indicated on the birth chart by a diagonal line.`, ja: `したがって、アセンダントが獅子座 1 度、獅子座 29 度、またはその間のどこかに位置している場合、獅子座全体が第 1 ハウスになります。 2 番目の家は乙女座と完全に対応し、3 番目の家は天秤座と完全に対応します。アセンダントが属するハウスは、出生図では斜線で示されます。` } },
      { type: "paragraph", text: { en: `Equal House Diagram in Jyotish`, ja: `ジョーティッシュのイコールハウス図` } },
      { type: "paragraph", text: { en: `The South Indian chart format, which is often the easiest for beginners to learn, counts houses clockwise from the sign containing the Ascendant. In the example chart above, the Ascendant is marked by the diagonal line in Leo.`, ja: `南インドのチャート形式は、多くの場合、初心者にとって最も学びやすいもので、アセンダントを含むサインから時計回りにハウスを数えます。上のチャートの例では、アセンダントは獅子座の斜線でマークされています。` } },
      { type: "paragraph", text: { en: `The zodiac signs always remain in fixed positions within the chart. For example, Pisces will always appear in the upper-left corner.`, ja: `星座は常にチャート内の固定位置に残ります。たとえば、魚座は常に左上隅に表示されます。` } },
      { type: "paragraph", text: { en: `The meanings assigned to houses in Jyotish are not always identical to those used in Western Astrology.`, ja: `ジョーティッシュのハウスに割り当てられた意味は、西洋占星術で使用される意味と必ずしも同じではありません。` } },
      { type: "paragraph", text: { en: `Errors in recorded birth times can sometimes create significant difficulties, especially when the Ascendant lies close to the boundary between two signs. However, there are methods available to overcome this problem.[2]`, ja: `記録された出生時間のエラーは、特にアセンダントが 2 つの星座の境界近くにある場合に、重大な問題を引き起こす可能性があります。ただし、この問題を解決する方法はいくつかあります[2]。` } },
      { type: "heading", level: 3, text: { en: `‘Good’ and ‘Bad’ Houses`, ja: `「良い」家と「悪い」家` } },
      { type: "paragraph", text: { en: `The ruling planet of a particular house changes according to the Ascendant.`, ja: `特定のハウスの支配星はアセンダントに応じて変わります。` } },
      { type: "paragraph", text: { en: `For example, the Moon becomes the ruler of the 1st house for a Cancer Ascendant, while the Sun rules the 1st house for a Leo Ascendant (see the article on planetary rulership of signs).`, ja: `たとえば、月は蟹座アセンダントの第 1 ハウスの支配星になりますが、太陽が獅子座アセンダントの第 1 ハウスの支配星になります (星座の惑星支配に関する記事を参照)。` } },
      { type: "paragraph", text: { en: `Regardless of which zodiac sign is associated with a house, favourable houses strengthen planets placed within them, whereas unfavourable houses tend to weaken them.`, ja: `どの星座がハウスに関連付けられているかに関係なく、有利なハウスはその中に配置された惑星を強化し、不利なハウスは惑星を弱める傾向があります。` } },
      { type: "heading", level: 3, text: { en: `Trikona or Trinal Houses`, ja: `トリコナまたはトリナルハウス` } },
      { type: "paragraph", text: { en: `According to Jyotish, the 5th and 9th houses—known as the Trinal or Trikona houses—are extremely auspicious. Planets placed in these houses generally perform well and gain additional strength.`, ja: `ジョーティッシュによれば、トリナルまたはトリコナハウスとして知られる５室と９室は非常に縁起が良いとのこと。これらのハウスに配置された惑星は通常、良好なパフォーマンスを示し、さらなる強度を獲得します。` } },
      { type: "paragraph", text: { en: `Many astrologers also regard the 1st house as a Trikona house.`, ja: `多くの占星術師も、1 ハウスをトリコナ ハウスとみなしています。` } },
      { type: "paragraph", text: { en: `As a result, the natural positive qualities of planets occupying the 5th or 9th house become enhanced, allowing them to deliver their beneficial results more fully.`, ja: `その結果、5室または9室を占める惑星の本来のポジティブな性質が強化され、有益な結果をより完全に発揮できるようになります。` } },
      { type: "paragraph", text: { en: `Any houses governed by those planets also receive significant support and strengthening.`, ja: `これらの惑星によって統治されているハウスも、重要なサポートと強化を受けます。` } },
      { type: "paragraph", text: { en: `The rulers of the 5th and 9th houses carry a naturally positive energy. They bring this favourable influence into whichever house they occupy.`, ja: `5 室と 9 室の支配者は、自然にポジティブなエネルギーを持っています。彼らはどの家に住んでいても、この好ましい影響をもたらします。` } },
      { type: "paragraph", text: { en: `Likewise, they benefit planets they are conjunct with and those they aspect.`, ja: `同様に、それらは結合している惑星やアスペクトしている惑星にも利益をもたらします。` } },
      { type: "heading", level: 3, text: { en: `Kendras or Angular Houses`, ja: `ケンドラまたは角のある家` } },
      { type: "paragraph", text: { en: `The Kendras, or Angular Houses—namely the 1st, 4th, 7th, and 10th houses—are also considered favourable houses. Planets positioned within them gain strength, and the houses themselves represent generally beneficial areas of life.`, ja: `ケンドラ、または角のあるハウス、つまり 1 室、4 室、7 室、および 10 室も、好ましいハウスとみなされます。それらの中に位置する惑星は力を増し、ハウス自体は一般的に人生に有益な領域を表します。` } },
      { type: "paragraph", text: { en: `A good house has two important effects. First, it strengthens planets placed within it and the matters associated with those planets. Second, its ruler carries a positive influence that benefits the house where it is placed.`, ja: `良い家には 2 つの重要な効果があります。まず、その中に配置された惑星とそれらの惑星に関連する事柄を強化します。第二に、その支配者は、それが置かれている家に利益をもたらすポジティブな影響をもたらします。` } },
      { type: "heading", level: 3, text: { en: `Dusthanas or Negative Houses`, ja: `ダスタナスまたはネガティブハウス` } },
      { type: "paragraph", text: { en: `The 6th, 8th, and 12th houses, known as Dusthanas, are regarded as negative houses.`, ja: `ダスタナスとして知られる６、８、１２室はネガティブハウスとみなされます。` } },
      { type: "paragraph", text: { en: `These houses do not represent anything inherently evil. They are classified as negative because they tend to weaken planets occupying them, reducing the ability of those planets to express their natural positive qualities.`, ja: `これらの家は本質的に邪悪なものを表しているわけではありません。それらは、そこに住んでいる惑星を弱め、それらの惑星が本来持っているポジティブな性質を表現する能力を低下させる傾向があるため、ネガティブなものとして分類されます。` } },
      { type: "paragraph", text: { en: `Furthermore, the houses ruled by planets placed in the 6th, 8th, or 12th are also weakened, causing difficulties in the affairs associated with those houses.`, ja: `さらに、6、8、12に位置する惑星が支配するハウスも弱まり、それらのハウスに関連する事柄に困難が生じます。` } },
      { type: "paragraph", text: { en: `The rulers of the 6th, 8th, and 12th houses are likewise considered to carry a challenging energy. This influence can disturb the house they occupy, the planets they conjoin, and the houses or planets they aspect.`, ja: `6、8、12 ハウスの支配者も同様に、挑戦的なエネルギーを持っていると考えられています。この影響は、それらが占有するハウス、それらが結合する惑星、およびそれらがアスペクトするハウスまたは惑星を乱す可能性があります。` } },
      { type: "paragraph", text: { en: `Among the three Dusthanas, the 8th house is generally regarded as the most difficult.`, ja: `3 つのダスターナの中で、一般に 8 室が最も難しいと考えられています。` } },
      { type: "paragraph", text: { en: `Even though these houses are considered negative, it is important to understand their deeper meaning. A strong 6th house helps us overcome enemies and competitors. A strong 8th house can indicate longevity and vitality. A strong 12th house suggests limited losses and expenditures, while also supporting spiritual growth and progress toward enlightenment.`, ja: `これらの家はネガティブなものと考えられていますが、その深い意味を理解することが重要です。強い6ハウスは、敵や競争相手に打ち勝つのに役立ちます。強い8ハウスは長寿と活力を示します。強い12ハウスは、損失と出費が限定的であることを示唆すると同時に、精神的な成長と啓発への進歩をサポートします。` } },
      { type: "heading", level: 3, text: { en: `Upachaya or Growing Houses`, ja: `ウパチャヤまたは成長する家` } },
      { type: "paragraph", text: { en: `The 3rd, 6th, 10th, and 11th houses are classified as Upachaya houses, often translated as "growing houses."`, ja: `3、6、10、11 ハウスはウパチャヤ ハウスに分類され、多くの場合「成長するハウス」と訳されます。` } },
      { type: "paragraph", text: { en: `Any difficulties indicated by these houses tend to improve with time, and malefic planets placed within them frequently produce beneficial results as life progresses.`, ja: `これらのハウスが示す困難は時間の経過とともに改善する傾向があり、それらのハウスに配置された凶星は、人生が進むにつれて有益な結果をもたらすことがよくあります。` } },
      { type: "paragraph", text: { en: `For this reason, malefic planets are often considered well placed when occupying either their Own Signs, Exalted Signs, or Upachaya houses.`, ja: `このため、凶星は、自身の星座、高貴な星座、またはウパチャヤハウスのいずれかを占有する場合、適切な位置にあるとみなされることがよくあります。` } },
      { type: "heading", level: 3, text: { en: `Footnotes`, ja: `脚注` } },
      { type: "paragraph", text: { en: `[1] The Ascendant is the zodiac sign that appears to be rising on the eastern horizon at the moment of birth. For example, if the eastern horizon was at 20 degrees Capricorn at the time of birth, the individual would be said to have a Capricorn Ascendant. The Ascendant is marked on the chart by a diagonal line. Note that this refers to the Sidereal Zodiac used in Jyotish, rather than the Tropical Zodiac used in Western Astrology.`, ja: `[1] アセンダントは、生まれた瞬間に東の地平線に昇っているように見える星座です。たとえば、出生時に東の地平線が山羊座 20 度にあった場合、その人は山羊座のアセンダントを持っていると言われます。アセンダントはチャート上で斜線でマークされます。これは、西洋占星術で使用される熱帯黄道帯ではなく、ジョーティッシュで使用される恒星黄道帯を指すことに注意してください。` } },
      { type: "paragraph", text: { en: `[2] Highly skilled and experienced Vedic Astrologers can often work backwards from important life events to determine a person's correct birth time. This process is known as birth-time rectification.`, ja: `[2] 高度な技術と経験を持つヴェーダ占星術師は、多くの場合、重要な人生の出来事から逆算して、人の正確な出生時刻を判断できます。このプロセスは誕生時修正として知られています。` } },
    ],
  },
  {
    id: "natural-benefics-malefics",
    section: "planets",
    title: { en: `Natural Benefic and Malefic Planets`, ja: `自然の吉星と凶星` },
    related: ["functional-benefics-malefics","planetary-strengths","planetary-aspects"],
    blocks: [
      { type: "heading", level: 2, text: { en: `Natural Benefic and Malefic Planets`, ja: `自然の吉星と凶星` } },
      { type: "paragraph", text: { en: `Summary: An exploration of the natural benefic and malefic planets in Vedic Astrology, including the terminology used in Jyotish and the classification of all nine planets, including Rahu and Ketu.`, ja: `概要: ジョーティッシュで使用される用語と、ラーフとケートゥを含む 9 つの惑星すべての分類を含む、ヴェーダ占星術における自然の吉星と凶星についての探求。` } },
      { type: "heading", level: 3, text: { en: `List of Natural Benefics and Malefics in Jyotish`, ja: `ジョーティッシュの自然の有益性と有害性のリスト` } },
      { type: "paragraph", text: { en: `• Venus, Jupiter, and the waxing Moon are natural benefics.`, ja: `• 金星、木星、上弦の月は自然の恵みです。` } },
      { type: "paragraph", text: { en: `• Mars, Saturn, Rahu, and Ketu are natural malefics.`, ja: `• 火星、土星、ラーフ、ケートゥは自然の凶星です。` } },
      { type: "paragraph", text: { en: `• Mercury's nature depends upon the planets it associates with.`, ja: `• 水星の性質は、関連する惑星によって異なります。` } },
      { type: "paragraph", text: { en: `• The Sun is regarded as ‘Cruel’ rather than strictly ‘malefic’.`, ja: `• 太陽は、厳密には「凶悪」であるというよりも「残酷」であると考えられています。` } },
      { type: "paragraph", text: { en: `• The waning Moon is considered mildly malefic.`, ja: `• 欠けていく月は、穏やかに凶悪であると考えられています。` } },
      { type: "heading", level: 3, text: { en: `Benefics and Malefics – Terminology Explained`, ja: `ベネフィックスとマレフィックス - 用語の説明` } },
      { type: "paragraph", text: { en: `From the viewpoint of higher states of consciousness, as described in Vedic literature and the philosophy of Vedanta, there is ultimately no division between ‘good’ and ‘bad’. Things simply exist as they are. The planets function as the ‘cosmic postman’, delivering the results of our past karmas at the appropriate time.`, ja: `ヴェーダ文献やヴェーダーンタ哲学で説明されているように、高次の意識状態の観点から見ると、最終的には「善」と「悪」の区別はありません。物事はただそのまま存在しているだけです。惑星は「宇宙の郵便配達人」として機能し、私たちの過去のカルマの結果を適切なタイミングで届けます。` } },
      { type: "paragraph", text: { en: `For practical purposes, however, astrologers often describe planetary influences as ‘good’ when they bring happiness, enjoyment, fulfilment, and favourable outcomes, and as ‘bad’ when they result in disruption, obstacles, suffering, or significant life challenges.`, ja: `しかし実際的な目的のために、占星術師はしばしば惑星の影響が幸福、楽しみ、充実感、好ましい結果をもたらす場合には「良い」と表現し、混乱、障害、苦しみ、または重大な人生の課題をもたらす場合には「悪い」と表現します。` } },
      { type: "paragraph", text: { en: `In Jyotish, planets that generally produce favourable results are known as benefics, while those that tend to create difficulties are called malefics.`, ja: `ジョーティッシュでは、一般的に好ましい結果をもたらす惑星はベネフィックとして知られ、困難を引き起こす傾向にある惑星はマレフィックと呼ばれます。` } },
      { type: "paragraph", text: { en: `The Sanskrit term for a natural benefic is ‘shubha’, meaning auspicious, while a natural malefic is called ‘papa’, meaning sinful.`, ja: `サンスクリット語で自然の恩恵を意味する「シュバ」は縁起が良いという意味ですが、自然の凶悪な人物は「パパ」（罪深いという意味）と呼ばれます。` } },
      { type: "heading", level: 3, text: { en: `Nine ‘Planets’ Used by Jyotish`, ja: `ジョーティッシュが使用する9つの「惑星」` } },
      { type: "paragraph", text: { en: `Before proceeding further, it is important to understand that Jyotish does not make use of the outer planets Neptune, Uranus, and Pluto, which are commonly employed in Western Astrology. Likewise, it does not rely on sub-planets or asteroids such as Chiron.`, ja: `さらに進む前に、ジョーティッシュは西洋占星術で一般的に使用される外惑星である海王星、天王星、冥王星を利用しないことを理解することが重要です。同様に、キロンのような亜惑星や小惑星にも依存しません。` } },
      { type: "paragraph", text: { en: `The reason is simple: Jyotish does not require them. Vedic Astrology works with a field of information rather than physical forces emitted by celestial bodies. All the information necessary for accurate karmic prediction is contained within the positions of the nine planetary influences, known collectively as the Navagraha, distributed through the twelve zodiac signs and twenty-seven Nakshatras of the sidereal zodiac.`, ja: `理由は簡単です。Jyotish ではそれらが必要ないからです。ヴェーダ占星術は、天体が発する物理的な力ではなく、情報の分野を利用します。正確なカルマ予測に必要なすべての情報は、集合的にナヴァグラハとして知られる 9 つの惑星の影響の位置に含まれており、恒星黄道帯の 12 の星座と 27 のナクシャトラに分布しています。` } },
      { type: "paragraph", text: { en: `The nine ‘planets’ of Vedic Astrology consist of seven physical celestial bodies—the Sun, Moon, Mercury, Venus, Mars, Jupiter, and Saturn—along with two non-physical points. These are the lunar nodes associated with eclipses, representing the locations where the Moon’s orbit intersects the plane of the Earth’s orbit around the Sun.`, ja: `ヴェーダ占星術の 9 つの「惑星」は、太陽、月、水星、金星、火星、木星、土星の 7 つの物理的な天体と、2 つの非物理的な点で構成されています。これらは日食に関連する月のノードであり、月の軌道が太陽の周りの地球の軌道面と交差する位置を表します。` } },
      { type: "paragraph", text: { en: `The North Node is known as Rahu, and the South Node is called Ketu.`, ja: `北ノードはラーフとして知られ、南ノードはケートゥと呼ばれます。` } },
      { type: "heading", level: 3, text: { en: `Natural Benefic and Natural Malefic Planets`, ja: `天然の吉星と天然の凶星` } },
      { type: "paragraph", text: { en: `The idea of a Natural Benefic or Natural Malefic is relatively straightforward.`, ja: `自然の善性または自然の凶性のアイデアは比較的単純です。` } },
      { type: "paragraph", text: { en: `Some planets are regarded as inherently positive and are generally associated with beneficial outcomes, while others are considered inherently challenging and tend to bring difficulties.`, ja: `いくつかの惑星は本質的にポジティブであると考えられており、一般に有益な結果に関連付けられていますが、他の惑星は本質的に挑戦的であり、困難をもたらす傾向があると考えられています。` } },
      { type: "paragraph", text: { en: `In Vedic Astrology, Jupiter and Venus are two well-known examples of natural benefic planets.`, ja: `ヴェーダ占星術では、木星と金星の 2 つは、自然に有益な惑星のよく知られた例です。` } },
      { type: "paragraph", text: { en: `Similarly, Mars and Saturn are considered natural malefics in Jyotish.`, ja: `同様に、火星と土星はジョーティッシュでは自然の凶星と考えられています。` } },
      { type: "paragraph", text: { en: `These classifications are largely familiar to Western Astrologers. However, significant differences arise when considering the remaining planets and how they are interpreted in Jyotish compared with Western Astrology.`, ja: `これらの分類は西洋占星術師にはよく知られています。しかし、残りの惑星とそれらが西洋占星術と比較してジョーティッシュでどのように解釈されるかを考慮すると、大きな違いが生じます。` } },
      { type: "heading", level: 3, text: { en: `What About Mercury?`, ja: `水銀はどうですか？` } },
      { type: "paragraph", text: { en: `Mercury occupies a unique position. When Mercury is alone or associated with benefic planets—through conjunctions or benefic aspects—it behaves as a benefic. When it is associated with malefics, it tends to act as a malefic.`, ja: `水星は独特の位置を占めています。水星が単独で存在する場合、またはコンジャンクションや有益な側面を通じて、有益な惑星と関連している場合、水星は有益であるかのように振る舞います。凶星と関連付けられると、凶星として作用する傾向があります。` } },
      { type: "paragraph", text: { en: `In other words, Mercury adopts either a benefic or malefic role depending upon the company it keeps.`, ja: `言い換えれば、水星は、付き合い方に応じて、有益な役割も凶悪な役割も担うのです。` } },
      { type: "heading", level: 3, text: { en: `What About the Sun, Moon, Rahu and Ketu?`, ja: `太陽、月、ラーフ、ケートゥについてはどうですか？` } },
      { type: "paragraph", text: { en: `The remaining planetary influences—Sun, Moon, Rahu, and Ketu—require separate consideration.`, ja: `残りの惑星の影響 (太陽、月、ラーフ、ケートゥ) については、別途考慮する必要があります。` } },
      { type: "heading", level: 3, text: { en: `The Sun`, ja: `太陽` } },
      { type: "paragraph", text: { en: `In Jyotish, the Sun is not classified as a natural benefic. This often surprises astrologers trained in the Western tradition.`, ja: `ジョーティッシュでは、太陽は自然の恵みとして分類されていません。これは、西洋の伝統で訓練を受けた占星術師を驚かせることがよくあります。` } },
      { type: "paragraph", text: { en: `Because of its intense heat and powerful nature, the Sun is frequently described by Vedic Astrologers as ‘cruel’. In practical terms, planets situated very close to the Sun in a birth chart become combust or scorched.`, ja: `太陽はその強烈な熱と強力な性質のため、ヴェーダ占星術師によってしばしば「残酷」であると表現されます。実際的に言えば、出生図で太陽の非常に近くに位置する惑星は燃焼または焦げます。` } },
      { type: "paragraph", text: { en: `As a result, natural benefics such as Venus may be unable to deliver their usual positive effects when combust, while natural malefics such as Mars can sometimes become even more troublesome under combustion.`, ja: `その結果、金星のような自然の有益物質は、燃焼時に通常のプラスの効果を発揮できない可能性があり、一方、火星のような自然の凶物質は、燃焼中にさらに厄介になる場合があります。` } },
      { type: "heading", level: 3, text: { en: `The Moon`, ja: `月` } },
      { type: "paragraph", text: { en: `The Moon’s benefic or malefic nature depends largely on whether it is increasing or decreasing in brightness.`, ja: `月の吉凶の性質は、明るさが増加しているか減少しているかに大きく依存します。` } },
      { type: "paragraph", text: { en: `A Full Moon is considered highly auspicious. A waxing Moon is regarded as a natural benefic and is generally associated with favourable results.`, ja: `満月は非常に縁起が良いと考えられています。上弦の月は自然の恵みとみなされ、一般に好ましい結果と関連付けられています。` } },
      { type: "paragraph", text: { en: `A waning Moon, on the other hand, is viewed as malefic, although only mildly so. Many astrologers prefer to describe it as ‘ashubha’, meaning not auspicious, rather than fully malefic.`, ja: `一方、欠けていく月は、ほんのわずかではありますが、凶星とみなされます。多くの占星術師は、完全に凶星というよりも、縁起が良くないという意味の「アシュバ」と表現することを好みます。` } },
      { type: "heading", level: 3, text: { en: `Rahu and Ketu`, ja: `ラーフとケートゥ` } },
      { type: "paragraph", text: { en: `Jyotish places considerable emphasis on Rahu and Ketu, the lunar nodes.`, ja: `ジョーティッシュは、月のノードであるラーフとケートゥにかなりの重点を置いています。` } },
      { type: "paragraph", text: { en: `Although they have no physical existence and are simply calculated points where the Moon’s orbit intersects the ecliptic, they signify powerful and very real karmic influences.`, ja: `それらは物理的な存在を持たず、月の軌道が黄道と交差する単純に計算された点ですが、強力で非常に現実的なカルマの影響を意味します。` } },
      { type: "paragraph", text: { en: `In Vedic Astrology, both Rahu and Ketu are classified as natural malefics.`, ja: `ヴェーダ占星術では、ラーフとケートゥは両方とも自然凶星として分類されています。` } },
      { type: "heading", level: 3, text: { en: `Modifying Factors`, ja: `変更要因` } },
      { type: "paragraph", text: { en: `People who are new to Jyotish often ask what kinds of benefits a natural benefic such as Venus can actually provide. The answer depends greatly on its placement within an individual's birth chart.`, ja: `ジョーティッシュを初めて使用する人は、金星のような自然の恩恵が実際にどのような恩恵をもたらすのかをよく尋ねます。答えは、個人の出生図内での位置に大きく依存します。` } },
      { type: "paragraph", text: { en: `The following general principles apply:`, ja: `次の一般原則が適用されます。` } },
      { type: "heading", level: 3, text: { en: `Planetary Strength Matters`, ja: `惑星の強さが重要` } },
      { type: "paragraph", text: { en: `Strong planets are capable of producing stronger results than weak planets.`, ja: `強い惑星は、弱い惑星よりも強力な結果を生み出すことができます。` } },
      { type: "paragraph", text: { en: `A powerful natural benefic can bring substantial benefits, whereas a weak benefic may struggle to produce positive outcomes.`, ja: `強力な天然の有益性は多大な利益をもたらす可能性がありますが、弱い有益性はプラスの結果を生み出すのに苦労する可能性があります。` } },
      { type: "paragraph", text: { en: `Planetary strength depends significantly on zodiacal placement. Each planet has a specific sign in which it becomes exceptionally strong, known as its exaltation. The sign directly opposite its exaltation is where the planet becomes greatly weakened and is said to be debilitated or fallen.`, ja: `惑星の強さは黄道帯の配置に大きく依存します。各惑星には、その高揚として知られる、その惑星が非常に強くなる特定の兆候があります。その高揚の真反対の兆候は、惑星が著しく弱体化する場所であり、衰弱または衰退すると言われています。` } },
      { type: "paragraph", text: { en: `A natural benefic placed in its exaltation sign or its own sign is generally highly favourable for the native.`, ja: `高揚サインまたは独自のサインに配置された自然の恩恵は、一般的にネイティブにとって非常に有利です。` } },
      { type: "paragraph", text: { en: `For a more detailed discussion, see: Planetary Strengths or Powers.`, ja: `より詳細な議論については、「惑星の強みまたは力」を参照してください。` } },
      { type: "heading", level: 3, text: { en: `Strong Malefics and Weak Malefics`, ja: `強い凶星と弱い凶星` } },
      { type: "paragraph", text: { en: `A strong natural malefic—such as one placed in exaltation or its own sign—will often contribute positively to the affairs of the house it occupies. Strength tends to enhance the constructive qualities of a malefic planet.`, ja: `生来の強い凶星（高揚や自身の星座に置かれた凶星など）は、しばしばそれが占有する家の事柄にプラスの影響を及ぼします。強さは凶星の建設的な性質を高める傾向があります。` } },
      { type: "paragraph", text: { en: `Conversely, a weak malefic is more likely to create significant difficulties.`, ja: `逆に、凶星が弱いと、重大な困難が生じる可能性が高くなります。` } },
      { type: "paragraph", text: { en: `For example, a strong Mars can provide courage, initiative, determination, and healthy motivation.`, ja: `たとえば、強い火星は勇気、自発性、決意、そして健康的なモチベーションをもたらします。` } },
      { type: "heading", level: 3, text: { en: `Saturn – A Special Case`, ja: `土星 – 特殊なケース` } },
      { type: "paragraph", text: { en: `The above principle is generally applicable, but Saturn deserves special mention.`, ja: `上記の原則は一般的に当てはまりますが、土星については特に言及する価値があります。` } },
      { type: "paragraph", text: { en: `A strong Saturn can bestow qualities such as humility, patience, discipline, and integrity. At the same time, during its period of operation (Mahadasha), it may also bring greater adversity, responsibility, or sorrow.`, ja: `強い土星は、謙虚さ、忍耐力、規律、誠実さなどの資質を与えることができます。同時に、その活動期間中（マハダシャー）には、より大きな逆境、責任、または悲しみがもたらされる可能性があります。` } },
      { type: "heading", level: 3, text: { en: `Further Study`, ja: `さらなる研究` } },
      { type: "paragraph", text: { en: `The planetary indicators (Karakas) connected with various physiological, psychological, and sociological aspects of an individual are discussed separately in another article.`, ja: `個人のさまざまな生理学的、心理学的、社会学的側面に関連する惑星指標 (カラカス) については、別の記事で個別に説明します。` } },
    ],
  },
  {
    id: "functional-benefics-malefics",
    section: "planets",
    title: { en: `Functional Benefics and Malefics for All Ascendants`, ja: `すべてのアセンダントに対する機能的利益と有害性` },
    related: ["natural-benefics-malefics","gemstones","twelve-houses"],
    blocks: [
      { type: "heading", level: 2, text: { en: `Functional Benefics and Malefics for All Ascendants`, ja: `すべてのアセンダントに対する機能的利益と有害性` } },
      { type: "paragraph", text: { en: `Summary: A list of the functional benefic and functional malefic planets for each of the twelve ascendants in the Sidereal Zodiac used by Vedic Astrology. This is essential information for chart interpretation and the application of remedial measures.`, ja: `概要: ヴェーダ占星術で使用される恒星黄道帯の 12 のアセンダントそれぞれの機能的吉星および機能的凶星のリスト。これは、チャートの解釈と是正措置の適用に不可欠な情報です。` } },
      { type: "paragraph", text: { en: `List of Functional Benefics and Malefics for all Ascendants`, ja: `すべてのアセンダントの機能的ベネフィックとマレフィックのリスト` } },
      { type: "paragraph", text: { en: `This information is absolutely fundamental to Jyotish and forms an important part of chart interpretation.`, ja: `この情報はジョーティッシュにとって絶対に基本的なものであり、チャート解釈の重要な部分を形成します。` } },
      { type: "paragraph", text: { en: `It is also crucial when prescribing suitable remedial measures to balance planetary energies for a particular ascendant. As a general rule, functional benefic planets may be strengthened through appropriate gemstones. Functional malefics, however, should generally not be strengthened in this way, and alternative remedies such as planetary mantras are often preferred.`, ja: `また、特定のアセンダントの惑星エネルギーのバランスを取るための適切な改善策を処方する際にも重要です。一般に、機能的に有益な惑星は、適切な宝石によって強化される可能性があります。ただし、機能的な凶作用は一般にこの方法で強化されるべきではなく、惑星のマントラなどの代替療法が好まれることがよくあります。` } },
      { type: "paragraph", text: { en: `This guide to functional benefics and malefics for all twelve ascendants is intended for students of Jyotish who already possess a basic understanding of the subject. Please note the following:`, ja: `12 のアセンダントすべての機能的恩恵と凶悪性に関するこのガイドは、すでにこの主題の基本的な理解を持っているジョーティッシュの学生を対象としています。以下の点にご注意ください。` } },
      { type: "paragraph", text: { en: `• The numbers shown in brackets, for example (9 & 12), refer to the houses ruled or owned by the planet relative to the specific ascendant in the Sidereal Zodiac.`, ja: `• たとえば (9 と 12) のように括弧内に示されている数字は、恒星黄道帯の特定のアセンダントと比較して、惑星が支配または所有するハウスを指します。` } },
      { type: "paragraph", text: { en: `• Rahu and Ketu do not own any houses and are therefore not classified as functional benefics or malefics. They remain natural malefics.`, ja: `• ラーフとケートゥは家を所有していないため、機能的利益者または有害者として分類されません。彼らは生来の凶星であり続けます。` } },
      { type: "paragraph", text: { en: `• The notes provided below are derived mainly from the teachings of Parashara.`, ja: `• 以下に示す注記は、主にパラシャラの教えに基づいています。` } },
      { type: "paragraph", text: { en: `• Where available, the degree of positivity or negativity is indicated using a grading scale from 1 to 5.[1]`, ja: `• 可能な場合は、ポジティブまたはネガティブの程度が 1 ～ 5 の等級スケールを使用して示されます。[1]` } },
      { type: "paragraph", text: { en: `• A Grade 5 benefic is exceptionally auspicious and considerably more favourable than a Grade 1 benefic.`, ja: `• グレード 5 の恩恵は非常に縁起が良く、グレード 1 の恩恵よりもはるかに有利です。` } },
      { type: "paragraph", text: { en: `• A Grade 5 malefic is highly problematic and far more difficult than a Grade 1 malefic.`, ja: `• グレード 5 の凶星は非常に問題が多く、グレード 1 の凶星よりもはるかに困難です。` } },
      { type: "paragraph", text: { en: `• The ruler of the Ascendant never harms the native.`, ja: `・アセンダントの支配者は決して先住民に危害を加えない。` } },
      { type: "paragraph", text: { en: `• Not all Jyotish astrologers will agree completely on every point listed below. Jyotish contains many layers, subtleties, and exceptions, but the following serves as a useful general guide.`, ja: `• すべてのジョーティッシュ占星術師が、以下に挙げるすべての点に完全に同意するわけではありません。 Jotish には多くの層、微妙な点、例外が含まれていますが、以下は有用な一般ガイドとして役立ちます。` } },
      { type: "heading", level: 3, text: { en: `Aries Ascendant`, ja: `牡羊座のアセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Jupiter`, ja: `木星` }, { en: `(9 & 12)`, ja: `(9 & 12)` }, { en: `Very auspicious – Grade 4`, ja: `非常に縁起の良い – グレード 4` }],
        [{ en: `Sun`, ja: `太陽` }, { en: `(5)`, ja: `(5)` }, { en: `Auspicious – Grade 2`, ja: `縁起の良い – グレード 2` }],
        [{ en: `Mars`, ja: `火星` }, { en: `(1 & 8)`, ja: `(1 & 8)` }, { en: `Helpful to auspicious planets`, ja: `縁起の良い惑星に役立つ` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Saturn`, ja: `土星` }, { en: `(10 & 11)`, ja: `(10&11)` }, { en: `Inauspicious – Grade 3`, ja: `不吉 - グレード 3` }],
        [{ en: `Mercury`, ja: `水銀` }, { en: `(3 & 6)`, ja: `(3&6)` }, { en: `Inauspicious – Grade 3`, ja: `不吉 - グレード 3` }],
        [{ en: `Venus`, ja: `金星` }, { en: `(2 & 7)`, ja: `(2&7)` }, { en: `Inauspicious – Grade 1`, ja: `不吉 - グレード 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Mars has its Moolatrikona sign in Aries (1) and is therefore predominantly favourable.`, ja: `• 火星は牡羊座 (1) にムーラトリコーナサインを持っているため、圧倒的に有利です。` } },
      { type: "paragraph", text: { en: `• Mars assists the Sun and Jupiter. Some astrologers also include the Moon in this category.`, ja: `• 火星は太陽と木星を助けます。占星術師の中には、月をこのカテゴリーに含める人もいます。` } },
      { type: "paragraph", text: { en: `• Saturn associated with Venus is generally unfavourable.`, ja: `• 金星と関連する土星は一般的に不利です。` } },
      { type: "paragraph", text: { en: `• Associations between Jupiter–Sun, Jupiter–Mars, and Mars–Sun are considered beneficial.`, ja: `• 木星と太陽、木星と火星、火星と太陽の関係は有益であると考えられています。` } },
      { type: "paragraph", text: { en: `• A conjunction between Saturn and Jupiter does not usually produce auspicious results.`, ja: `• 土星と木星の合は、通常、縁起の良い結果をもたらしません。` } },
      { type: "paragraph", text: { en: `• Jupiter operating under the influence of a malefic can produce inauspicious outcomes.`, ja: `• 凶星の影響下で活動する木星は、不吉な結果を生み出す可能性があります。` } },
      { type: "heading", level: 3, text: { en: `Taurus Ascendant`, ja: `おうし座のアセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Saturn`, ja: `土星` }, { en: `(9 & 10)`, ja: `(9 & 10)` }, { en: `Very auspicious (Yogakaraka)`, ja: `とても縁起が良い（ヨガカラカ）` }],
        [{ en: `Mercury`, ja: `水銀` }, { en: `(2 & 5)`, ja: `(2&5)` }, { en: `Auspicious`, ja: `縁起の良い` }],
        [{ en: `Sun`, ja: `太陽` }, { en: `(4)`, ja: `(4)` }, { en: `Beneficial`, ja: `有益` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Jupiter`, ja: `木星` }, { en: `(8 & 11)`, ja: `(8 & 11)` }, { en: `Very adverse indeed`, ja: `確かに非常に不利です` }],
        [{ en: `Mars`, ja: `火星` }, { en: `(7 & 12)`, ja: `(7 & 12)` }, { en: `Maraka`, ja: `マラカ` }],
        [{ en: `Moon`, ja: `月` }, { en: `(3)`, ja: `(3)` }, { en: `Inauspicious`, ja: `不吉な` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• The Moon, as ruler of the 3rd house, is not particularly auspicious, though not excessively harmful. The 3rd house is considered less troublesome than the 6th, which itself is generally less difficult than the 11th.`, ja: `• 月は 3 室の支配星なので、過度に有害ではないものの、特に縁起が良いわけではありません。 3 ハウスは 6 ハウスほど面倒ではないと考えられており、6 ハウス自体は一般に 11 ハウスよりも難しくありません。` } },
      { type: "paragraph", text: { en: `• Parashara classifies Venus as a malefic despite ruling the Ascendant. This is presumably because Libra, Venus' Moolatrikona sign, falls in the 6th house from Taurus.`, ja: `• パラシャラはアセンダントを支配しているにもかかわらず、金星を凶星として分類しています。これはおそらく、金星のムーラトリコーナサインである天秤座がおうし座から６室に位置しているためと考えられます。` } },
      { type: "paragraph", text: { en: `• Other astrologers maintain that Venus remains benefic for Taurus Lagna because it rules the Ascendant, which functions as both a Trine and a Kendra. They argue that the Ascendant lord is always beneficial.`, ja: `• 他の占星術師は、金星はトラインとケンドラの両方として機能するアセンダントを支配するため、金星が引き続き牡牛座ラグナにとって有益であると主張しています。彼らは、アセンダントロードは常に有益であると主張します。` } },
      { type: "paragraph", text: { en: `• Mercury acts more effectively when associated with Saturn or the Sun.`, ja: `• 水星は、土星または太陽と関連すると、より効果的に作用します。` } },
      { type: "heading", level: 3, text: { en: `Gemini Ascendant`, ja: `双子座アセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Venus`, ja: `金星` }, { en: `(5 & 12)`, ja: `(5 & 12)` }, { en: `Auspicious – Grade 2`, ja: `縁起の良い – グレード 2` }],
        [{ en: `Saturn`, ja: `土星` }, { en: `(8 & 9)`, ja: `(8&9)` }, { en: `Auspicious – see notes`, ja: `縁起が良い – 注を参照` }],
        [{ en: `Mercury`, ja: `水銀` }, { en: `(1 & 4)`, ja: `(1&4)` }, { en: `Auspicious`, ja: `縁起の良い` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mars`, ja: `火星` }, { en: `(6 & 11)`, ja: `(6 & 11)` }, { en: `Very adverse indeed – Grade 5`, ja: `確かに非常に有害 – グレード 5` }],
        [{ en: `Sun`, ja: `太陽` }, { en: `(3)`, ja: `(3)` }, { en: `Inauspicious – Grade 1`, ja: `不吉 - グレード 1` }],
        [{ en: `Jupiter`, ja: `木星` }, { en: `(7 & 10)`, ja: `(7&10)` }, { en: `Inauspicious`, ja: `不吉な` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Venus is highly favourable because the 5th house (Libra) is its Moolatrikona sign.`, ja: `• 金星は、5室（天秤座）がムーラトリコーナサインであるため、非常に有利です。` } },
      { type: "paragraph", text: { en: `• Saturn's role as ruler of the 8th and 9th houses is not specifically discussed by Parashara. Since Aquarius, Saturn's Moolatrikona sign, is the 9th house, Saturn is generally considered favourable, though the overall chart should always be examined.`, ja: `・8室と9室の支配者としての土星の役割は、パラシャラによって特に議論されていない。土星のムーラトリコーナサインである水瓶座は9室にあるため、全体的なチャートを常に調べる必要がありますが、土星は一般に有利であると考えられています。` } },
      { type: "paragraph", text: { en: `• The Sun's rulership of the 3rd house is not especially beneficial.`, ja: `・太陽が３室支配であることは、特に有利ではない。` } },
      { type: "heading", level: 3, text: { en: `Cancer Ascendant`, ja: `がんアセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mars`, ja: `火星` }, { en: `(5 & 10)`, ja: `(5 & 10)` }, { en: `Auspicious – Grade 2 (Yogakaraka)`, ja: `縁起 – グレード 2 (ヨガカラカ)` }],
        [{ en: `Jupiter`, ja: `木星` }, { en: `(6 & 9)`, ja: `(6 & 9)` }, { en: `Auspicious – Grade 2`, ja: `縁起の良い – グレード 2` }],
        [{ en: `Moon`, ja: `月` }, { en: `(1)`, ja: `(1)` }, { en: `Beneficial`, ja: `有益` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Venus`, ja: `金星` }, { en: `(4 & 11)`, ja: `(4 & 11)` }, { en: `Inauspicious – Grade 3`, ja: `不吉 - グレード 3` }],
        [{ en: `Mercury`, ja: `水銀` }, { en: `(3 & 12)`, ja: `(3 & 12)` }, { en: `Inauspicious – Grade 3`, ja: `不吉 - グレード 3` }],
        [{ en: `Saturn`, ja: `土星` }, { en: `(7 & 8)`, ja: `(7&8)` }, { en: `Strong Maraka`, ja: `強いマラカ` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Mars associated with the Sun, Moon, or Jupiter is considered highly favourable.`, ja: `• 太陽、月、または木星と関連する火星は、非常に好ましいと考えられます。` } },
      { type: "heading", level: 3, text: { en: `Leo Ascendant`, ja: `獅子座アセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mars`, ja: `火星` }, { en: `(4 & 9)`, ja: `(4 & 9)` }, { en: `Extremely auspicious – Grade 5 (Yogakaraka)`, ja: `非常に縁起の良い – グレード 5 (ヨガカラカ)` }],
        [{ en: `Jupiter`, ja: `木星` }, { en: `(5 & 8)`, ja: `(5&8)` }, { en: `Auspicious – Grade 2`, ja: `縁起の良い – グレード 2` }],
        [{ en: `Sun`, ja: `太陽` }, { en: `(1)`, ja: `(1)` }, { en: `Beneficial`, ja: `有益` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mercury`, ja: `水銀` }, { en: `(2 & 11)`, ja: `(2&11)` }, { en: `Very inauspicious – Grade 4`, ja: `非常に不吉 – グレード 4` }],
        [{ en: `Saturn`, ja: `土星` }, { en: `(6 & 7)`, ja: `(6&7)` }, { en: `Inauspicious – Grade 2`, ja: `不吉 - グレード 2` }],
        [{ en: `Venus`, ja: `金星` }, { en: `(3 & 10)`, ja: `(3 & 10)` }, { en: `Inauspicious – Grade 1`, ja: `不吉 - グレード 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Many astrologers regard Venus as somewhat unreliable for Leo Ascendant.`, ja: `• 多くの占星術師は、獅子座のアセンダントにとって金星はやや信頼できないと考えています。` } },
      { type: "paragraph", text: { en: `• A conjunction of Jupiter and Venus generally does not produce auspicious results.`, ja: `• 木星と金星の結合は、一般に縁起の良い結果をもたらしません。` } },
      { type: "heading", level: 3, text: { en: `Virgo Ascendant`, ja: `乙女座アセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Venus`, ja: `金星` }, { en: `(2 & 9)`, ja: `(2&9)` }, { en: `Very auspicious (Yogakaraka)`, ja: `とても縁起が良い（ヨガカラカ）` }],
        [{ en: `Mercury`, ja: `水銀` }, { en: `(1 & 10)`, ja: `(1 & 10)` }, { en: `Auspicious`, ja: `縁起の良い` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mars`, ja: `火星` }, { en: `(3 & 8)`, ja: `(3 & 8)` }, { en: `Very inauspicious – Grade 4`, ja: `非常に不吉 – グレード 4` }],
        [{ en: `Moon`, ja: `月` }, { en: `(11)`, ja: `(11)` }, { en: `Inauspicious – Grade 3`, ja: `不吉 - グレード 3` }],
        [{ en: `Jupiter`, ja: `木星` }, { en: `(4 & 7)`, ja: `(4 & 7)` }, { en: `Inauspicious – Grade 1`, ja: `不吉 - グレード 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• The Sun's role as ruler of the 12th depends heavily upon its associations and is generally acceptable when joined with benefic planets in favourable houses.`, ja: `• 12 室の支配者としての太陽の役割は、その関係に大きく依存しており、有利なハウスで有益な惑星と結合する場合は一般に許容されます。` } },
      { type: "paragraph", text: { en: `• Saturn (5th and 6th lord) is not specifically mentioned by Parashara. It is generally favourable due to its rulership of the 5th and relationship with Mercury, although some doshas arise because of its 6th house ownership.`, ja: `• 土星（第 5 位と第 6 位の支配者）については、パラシャラによって特に言及されていません。 5室の支配権と水星との関係により、一般に有利ですが、6室の所有権のためにいくつかのドーシャが発生します。` } },
      { type: "paragraph", text: { en: `• Jupiter, ruling the 4th and 7th houses, becomes a Maraka.`, ja: `・４、７室支配の木星がマラカとなる。` } },
      { type: "heading", level: 3, text: { en: `Libra Ascendant`, ja: `天秤座のアセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mercury`, ja: `水銀` }, { en: `(9 & 12)`, ja: `(9 & 12)` }, { en: `Very auspicious – Grade 4`, ja: `非常に縁起の良い – グレード 4` }],
        [{ en: `Saturn`, ja: `土星` }, { en: `(4 & 5)`, ja: `(4&5)` }, { en: `Auspicious – Grade 3 (Yogakaraka)`, ja: `縁起 – グレード 3 (ヨガカラカ)` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Jupiter`, ja: `木星` }, { en: `(3 & 6)`, ja: `(3&6)` }, { en: `Inauspicious – Grade 3`, ja: `不吉 - グレード 3` }],
        [{ en: `Sun`, ja: `太陽` }, { en: `(11)`, ja: `(11)` }, { en: `Inauspicious – Grade 3`, ja: `不吉 - グレード 3` }],
        [{ en: `Mars`, ja: `火星` }, { en: `(2 & 7)`, ja: `(2&7)` }, { en: `Inauspicious – Grade 1`, ja: `不吉 - グレード 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Venus rules the 1st and 8th houses. Parashara describes Venus as neutral. However, many astrologers argue that Venus should be regarded as auspicious because it rules the Lagna. An interesting debate.`, ja: `• Venus rules the 1st and 8th houses. Parashara describes Venus as neutral.しかし、多くの占星術師は、金星はラグナを支配しているので縁起が良いとみなされるべきだと主張しています。興味深い議論です。` } },
      { type: "paragraph", text: { en: `• The Moon (10th lord) associated with Mercury (9th and 12th lord) can create Rajayoga.`, ja: `• 水星（9 位と 12 位の支配星）と関連する月（10 位の支配星）は、ラジャヨガを生み出す可能性があります。` } },
      { type: "paragraph", text: { en: `• Mars functions as a Maraka.`, ja: `• 火星はマラカとして機能します。` } },
      { type: "heading", level: 3, text: { en: `Scorpio Ascendant`, ja: `蠍座のアセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Moon`, ja: `月` }, { en: `(9)`, ja: `(9)` }, { en: `Very auspicious – Grade 4`, ja: `非常に縁起の良い – グレード 4` }],
        [{ en: `Jupiter`, ja: `木星` }, { en: `(2 & 5)`, ja: `(2&5)` }, { en: `Auspicious – Grade 2`, ja: `縁起の良い – グレード 2` }],
        [{ en: `Sun`, ja: `太陽` }, { en: `(10)`, ja: `(10)` }, { en: `Auspicious – Grade 1`, ja: `縁起の良い – グレード 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mercury`, ja: `水銀` }, { en: `(8 & 11)`, ja: `(8 & 11)` }, { en: `Very adverse indeed – Grade 5`, ja: `確かに非常に有害 – グレード 5` }],
        [{ en: `Venus`, ja: `金星` }, { en: `(7 & 12)`, ja: `(7 & 12)` }, { en: `Inauspicious – Grade 2`, ja: `不吉 - グレード 2` }],
        [{ en: `Saturn`, ja: `土星` }, { en: `(3 & 4)`, ja: `(3&4)` }, { en: `Inauspicious – Grade 1`, ja: `不吉 - グレード 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Mars (1 & 6) is classified as neutral. However, many astrologers would regard Mars as auspicious because it rules the Lagna.`, ja: `• 火星 (1 と 6) は中立に分類されます。しかし、多くの占星術師は火星がラグナを支配しているため、火星は縁起が良いと考えるでしょう。` } },
      { type: "paragraph", text: { en: `• Venus functions as a Maraka.`, ja: `• 金星はマラカとして機能します。` } },
      { type: "paragraph", text: { en: `• The Sun and Moon together can produce Yogakaraka effects.`, ja: `• 太陽と月が一緒になるとヨガカラカ効果が生まれます。` } },
      { type: "heading", level: 3, text: { en: `Sagittarius Ascendant`, ja: `射手座アセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Sun`, ja: `太陽` }, { en: `(9)`, ja: `(9)` }, { en: `Very auspicious – Grade 4`, ja: `非常に縁起の良い – グレード 4` }],
        [{ en: `Mars`, ja: `火星` }, { en: `(5 & 12)`, ja: `(5 & 12)` }, { en: `Auspicious – Grade 2`, ja: `縁起の良い – グレード 2` }],
        [{ en: `Mercury`, ja: `水銀` }, { en: `(7 & 10)`, ja: `(7&10)` }, { en: `Auspicious`, ja: `縁起の良い` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Venus`, ja: `金星` }, { en: `(6 & 11)`, ja: `(6 & 11)` }, { en: `Very adverse indeed – Grade 5`, ja: `確かに非常に有害 – グレード 5` }],
        [{ en: `Saturn`, ja: `土星` }, { en: `(2 & 3)`, ja: `(2&3)` }, { en: `Inauspicious – Grade 2`, ja: `不吉 - グレード 2` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• The Moon, as ruler of the 8th house, is not specifically listed as inauspicious. It is generally considered favourable when associated with Mercury, the Sun, or Mars.`, ja: `• 月は 8 室の支配星なので、特に不吉なものとしては挙げられていません。一般に、水星、太陽、または火星と関連付けられている場合に好ましいと考えられています。` } },
      { type: "paragraph", text: { en: `• Mercury is auspicious because its Moolatrikona sign governs the 10th house.`, ja: `• 水星は、ムーラトリコーナサインが 10 室を支配しているため、縁起が良いです。` } },
      { type: "paragraph", text: { en: `• A mutual association between the Sun and Mercury creates Yoga.`, ja: `・太陽と水星の相互関係がヨガを生み出します。` } },
      { type: "paragraph", text: { en: `• An association between the Moon and Jupiter forms a favourable Yoga.`, ja: `・月と木星の関係は好ましいヨガを形成します。` } },
      { type: "paragraph", text: { en: `• Jupiter is regarded as neutral.`, ja: `• 木星は中立とみなされます。` } },
      { type: "heading", level: 3, text: { en: `Capricorn Ascendant`, ja: `山羊座アセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Venus`, ja: `金星` }, { en: `(5 & 10)`, ja: `(5 & 10)` }, { en: `Very auspicious (Yogakaraka)`, ja: `とても縁起が良い（ヨガカラカ）` }],
        [{ en: `Mercury`, ja: `水銀` }, { en: `(6 & 9)`, ja: `(6 & 9)` }, { en: `Auspicious`, ja: `縁起の良い` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mars`, ja: `火星` }, { en: `(4 & 11)`, ja: `(4 & 11)` }, { en: `Inauspicious – Grade 3`, ja: `不吉 - グレード 3` }],
        [{ en: `Jupiter`, ja: `木星` }, { en: `(3 & 12)`, ja: `(3 & 12)` }, { en: `Inauspicious`, ja: `不吉な` }],
        [{ en: `Moon`, ja: `月` }, { en: `(7)`, ja: `(7)` }, { en: `See notes`, ja: `注を参照` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Saturn (1 & 2) is classified as neutral. However, many astrologers regard Saturn as auspicious because it rules the Ascendant.`, ja: `• 土星 (1 と 2) は中立に分類されます。しかし、多くの占星術師は、土星はアセンダントを支配しているため、縁起が良いと考えています。` } },
      { type: "paragraph", text: { en: `• The Sun (8th lord) is generally considered neutral.`, ja: `• 太陽（第 8 支配星）は一般に中立とみなされます。` } },
      { type: "paragraph", text: { en: `• The Moon functions as a Maraka.`, ja: `• 月はマラカとして機能します。` } },
      { type: "heading", level: 3, text: { en: `Aquarius Ascendant`, ja: `水瓶座アセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Venus`, ja: `金星` }, { en: `(4 & 9)`, ja: `(4 & 9)` }, { en: `Extremely auspicious – Grade 5 (Yogakaraka)`, ja: `非常に縁起の良い – グレード 5 (ヨガカラカ)` }],
        [{ en: `Saturn`, ja: `土星` }, { en: `(1 & 12)`, ja: `(1 & 12)` }, { en: `Auspicious`, ja: `縁起の良い` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Jupiter`, ja: `木星` }, { en: `(2 & 11)`, ja: `(2&11)` }, { en: `Very adverse indeed – Grade 5`, ja: `確かに非常に有害 – グレード 5` }],
        [{ en: `Moon`, ja: `月` }, { en: `(6)`, ja: `(6)` }, { en: `Inauspicious – Grade 2`, ja: `不吉 - グレード 2` }],
        [{ en: `Mars`, ja: `火星` }, { en: `(3 & 10)`, ja: `(3 & 10)` }, { en: `Inauspicious – Grade 1`, ja: `不吉 - グレード 1` }],
        [{ en: `Sun`, ja: `太陽` }, { en: `(7)`, ja: `(7)` }, { en: `Maraka tendencies`, ja: `マラカの傾向` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Venus produces Rajayoga.`, ja: `• 金星はラジャヨガを生み出します。` } },
      { type: "paragraph", text: { en: `• Saturn is considered auspicious because Aquarius is its Moolatrikona sign.`, ja: `• 土星は水瓶座がムーラトリコーナ星座であるため、縁起が良いと考えられています。` } },
      { type: "paragraph", text: { en: `• Mercury (5 & 8) should generally be favourable but can produce mixed results depending upon its associations.`, ja: `• 水星 (5 と 8) は一般に有利ですが、その関連性によってはさまざまな結果が生じる可能性があります。` } },
      { type: "heading", level: 3, text: { en: `Pisces Ascendant`, ja: `魚座のアセンダント` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `機能的な利点` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Mars`, ja: `火星` }, { en: `(2 & 9)`, ja: `(2&9)` }, { en: `Very auspicious – Grade 4`, ja: `非常に縁起の良い – グレード 4` }],
        [{ en: `Moon`, ja: `月` }, { en: `(5)`, ja: `(5)` }, { en: `Auspicious – Grade 2`, ja: `縁起の良い – グレード 2` }],
        [{ en: `Jupiter`, ja: `木星` }, { en: `(1 & 10)`, ja: `(1 & 10)` }, { en: `Auspicious – Grade 1`, ja: `縁起の良い – グレード 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `機能的凶星` } },
      { type: "table", headers: [{ en: `Planet`, ja: `惑星` }, { en: `Houses Ruled`, ja: `支配された家` }, { en: `Notes`, ja: `注意事項` }], rows: [
        [{ en: `Saturn`, ja: `土星` }, { en: `(11 & 12)`, ja: `(11&12)` }, { en: `Very adverse indeed – Grade 5`, ja: `確かに非常に有害 – グレード 5` }],
        [{ en: `Venus`, ja: `金星` }, { en: `(3 & 8)`, ja: `(3 & 8)` }, { en: `Very inauspicious – Grade 4`, ja: `非常に不吉 – グレード 4` }],
        [{ en: `Sun`, ja: `太陽` }, { en: `(6)`, ja: `(6)` }, { en: `Inauspicious – Grade 2`, ja: `不吉 - グレード 2` }],
        [{ en: `Mercury`, ja: `水銀` }, { en: `(4 & 7)`, ja: `(4 & 7)` }, { en: `Inauspicious – Grade 1`, ja: `不吉 - グレード 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `注意事項` } },
      { type: "paragraph", text: { en: `• Pandit Ojha states that a Sambandha between Mars and Jupiter creates Rajayoga.`, ja: `• パンディット・オジャは、火星と木星の間のサンバンダがラージャヨガを生み出すと述べています。` } },
    ],
  },
  {
    id: "planetary-aspects",
    section: "aspects",
    title: { en: `Planetary Aspects`, ja: `惑星の側面` },
    related: ["planetary-strengths","natural-benefics-malefics","twelve-houses"],
    blocks: [
      { type: "heading", level: 2, text: { en: `Planetary Aspects`, ja: `惑星の側面` } },
      { type: "paragraph", text: { en: `Summary: Explaining the concept of Planetary Aspects in Jyotish and examining the rules required to apply these principles. Also highlighting the major differences between aspects in Vedic Astrology and Western Astrology.`, ja: `概要: ジョーティッシュ語の惑星アスペクトの概念を説明し、これらの原則を適用するために必要なルールを検討します。また、ヴェーダ占星術と西洋占星術のアスペクトの主な違いも強調します。` } },
      { type: "paragraph", text: { en: `Planetary aspects are an important part of chart interpretation, and the rules used in Jyotish differ significantly from those employed in Western Astrology.`, ja: `惑星のアスペクトはチャート解釈の重要な部分であり、ジョーティッシュで使用されるルールは西洋占星術で使用されるルールとは大きく異なります。` } },
      { type: "paragraph", text: { en: `Planets occupying a house project their field of influence across the birth chart and affect, either positively or negatively, other houses and any planets positioned within them. This influence is known as an aspect.`, ja: `ハウスを占める惑星は、その影響力の領域を出生図全体に投影し、他のハウスやその中に位置する惑星にプラスまたはマイナスの影響を与えます。この影響はアスペクトとして知られています。` } },
      { type: "paragraph", text: { en: `• In Jyotish, aspects are directed from one house to another house (unlike Western Astrology).`, ja: `• ジョーティッシュでは、アスペクトはあるハウスから別のハウスに向けられます（西洋占星術とは異なります）。` } },
      { type: "paragraph", text: { en: `• Aspects are therefore not based upon one planet's "orb of influence" (for example, a 10-degree sector) interacting with another planet's orb of influence.`, ja: `• したがって、アスペクトは、ある惑星の「影響力の球」（たとえば、10 度のセクター）が別の惑星の影響力の球と相互作用することに基づいていません。` } },
      { type: "paragraph", text: { en: `• Consequently, a planetary aspect can affect a house even when that house contains no planets. This is a very important distinction.`, ja: `• したがって、ハウスに惑星が含まれていない場合でも、惑星のアスペクトがハウスに影響を与える可能性があります。これは非常に重要な違いです。` } },
      { type: "paragraph", text: { en: `• Both occupied and empty houses can receive planetary influences through aspects cast from elsewhere in the birth chart.`, ja: `• 人が住んでいる家も空き家も、出生図の他の場所からキャストされたアスペクトを通じて惑星の影響を受ける可能性があります。` } },
      { type: "paragraph", text: { en: `• Aspects occur from planets located anywhere within one house (for example, the Sun at 2 degrees in the 1st house) and can influence planets located anywhere within the aspected house (for example, Saturn at 29 degrees in the 7th house).`, ja: `• アスペクトは、1 つのハウス内の任意の場所に位置する惑星 (たとえば、1 ハウスの 2 度にある太陽) から発生し、アスペクトされたハウス内の任意の場所にある惑星 (たとえば、7 ハウスの 29 度にある土星) に影響を与える可能性があります。` } },
      { type: "heading", level: 3, text: { en: `A Simple Example of an Aspect`, ja: `アスペクトの簡単な例` } },
      { type: "paragraph", text: { en: `In the example diagram, the Sun projects its field of influence onto the 7th house counted clockwise from its position. In this particular chart, that house corresponds with the sign of Libra.`, ja: `例の図では、太陽はその影響範囲をその位置から時計回りに数えて 7 番目の家に投影します。この特定のチャートでは、そのハウスは天秤座のサインに対応しています。` } },
      { type: "paragraph", text: { en: `What effect does this have? The answer depends upon several interconnected factors involved in chart interpretation.`, ja: `これにはどのような効果がありますか?その答えは、チャートの解釈に関係するいくつかの相互関連する要因によって決まります。` } },
      { type: "paragraph", text: { en: `The first step is to determine the Ascendant. This establishes whether the Sun functions as a benefic or malefic influence within the chart. We must then examine the house occupied by the Sun in order to assess its strength and condition. Once this is done, we can identify which house corresponds with Libra.`, ja: `最初のステップはアセンダントを決定することです。これにより、太陽がチャート内で有益な影響として機能するか、それとも有害な影響として機能するかが決まります。次に、太陽の強さと状態を評価するために、太陽が占めているハウスを調べる必要があります。これが完了すると、どのハウスが天秤座に対応するかを特定できます。` } },
      { type: "paragraph", text: { en: `Suppose the chart has a Sagittarius Ascendant. In that case, the Sun becomes the ruler of the auspicious 9th house (Leo in this chart) and is placed in its sign of exaltation, Aries. The Sun would then cast a highly positive influence through its aspect into Libra. Since Libra corresponds with the 11th house in this example, we would expect the affairs of the 11th house to be strengthened and enhanced.`, ja: `チャートに射手座のアセンダントがあるとします。その場合、太陽は縁起の良い9室（このチャートでは獅子座）の支配星となり、高揚のサインである牡羊座に位置します。そして、太陽はそのアスペクトを通じて天秤座に非常にポジティブな影響を与えることになります。この例では天秤座が11室に対応しているため、11室の事柄が強化され強化されることが予想されます。` } },
      { type: "paragraph", text: { en: `As a result, matters relating to gains, profits, opportunities, and the fulfilment of desires would likely benefit from this aspect.`, ja: `その結果、利得、利益、機会、欲望の実現に関連する事柄は、この側面から恩恵を受ける可能性があります。` } },
      { type: "heading", level: 3, text: { en: `Aspect Principle in Jyotish Astrology`, ja: `ジョーティッシュ占星術のアスペクト原理` } },
      { type: "heading", level: 3, text: { en: `Sun Aspects Only the 7th House`, ja: `太陽のアスペクトは7ハウスのみ` } },
      { type: "heading", level: 3, text: { en: `Aspect Rules`, ja: `アスペクトルール` } },
      { type: "paragraph", text: { en: `• Rahu and Ketu do not cast any aspects, but all the other planets do.`, ja: `• ラーフとケートゥはアスペクトをキャストしませんが、他のすべての惑星はアスペクトをキャストします。` } },
      { type: "paragraph", text: { en: `• All planets aspect the 7th house from their position.`, ja: `• すべての惑星は、その位置から 7 番目の家にアスペクトしています。` } },
      { type: "paragraph", text: { en: `• Mars additionally aspects the 4th and 8th houses from itself.`, ja: `・火星はさらに、自身から４室と８室にアスペクトしている。` } },
      { type: "paragraph", text: { en: `• Saturn additionally aspects the 3rd and 10th houses from itself.`, ja: `・土星はさらに、土星自身から３番目と１０番目の家にアスペクトしている。` } },
      { type: "paragraph", text: { en: `• Jupiter additionally aspects the 5th and 9th houses from itself.`, ja: `・木星はさらに、木星自体から５室と９室にアスペクトしている。` } },
      { type: "paragraph", text: { en: `When interpreting planetary aspects, both the natural characteristics and the functional characteristics of the aspecting planet must be taken into consideration.`, ja: `惑星のアスペクトを解釈するときは、アスペクトしている惑星の自然的特徴と機能的特徴の両方を考慮する必要があります。` } },
      { type: "heading", level: 3, text: { en: `Aspect Diagram for Mars`, ja: `火星のアスペクト ダイアグラム` } },
      { type: "heading", level: 3, text: { en: `Mars Aspects the 4th, 7th and 8th Houses in Jyotish`, ja: `火星はジョーティッシュの4、7、8ハウスにアスペクトします` } },
      { type: "paragraph", text: { en: `Mars casts aspects onto the 4th, 7th, and 8th houses counted from its own position in the birth chart.`, ja: `火星は、出生図における自身の位置から数えて4、7、8室にアスペクトをキャストします。` } },
      { type: "heading", level: 3, text: { en: `Aspect Diagram for Jupiter`, ja: `木星のアスペクト ダイアグラム` } },
      { type: "heading", level: 3, text: { en: `Jupiter Aspects the 5th, 7th and 9th Houses in Jyotish`, ja: `木星はジョーティシュの５、７、９室にアスペクトしている` } },
      { type: "paragraph", text: { en: `Jupiter casts aspects onto the 5th, 7th, and 9th houses counted from itself.`, ja: `木星は自身から数えて５、７、９室にアスペクトをキャストしている。` } },
      { type: "heading", level: 3, text: { en: `Aspect Diagram for Saturn`, ja: `土星のアスペクトダイアグラム` } },
      { type: "heading", level: 3, text: { en: `Saturn Aspects the 3rd, 7th and 10th Houses in Jyotish`, ja: `土星はジョーティッシュの３、７、１０室にアスペクトしている` } },
      { type: "paragraph", text: { en: `Saturn casts aspects onto the 3rd, 7th, and 10th houses counted from its own position.`, ja: `土星は自身の位置から数えて３、７、１０室にアスペクトをキャストしています。` } },
      { type: "heading", level: 3, text: { en: `Conjunction and Combustion`, ja: `結合と燃焼` } },
      { type: "paragraph", text: { en: `In Vedic Astrology, the term conjunction is used when two or more planets occupy the same sign or house, even if they are located near opposite ends of that house.`, ja: `ヴェーダ占星術では、コンジャンクションという用語は、2 つ以上の惑星が同じ星座またはハウスを占める場合、たとえそれらがそのハウスの反対側の端近くに位置していても使用されます。` } },
      { type: "paragraph", text: { en: `For example, if the Sun is positioned at 1 degree Taurus and Saturn at 28 degrees Taurus, they would still be considered conjunct in Jyotish.`, ja: `たとえば、太陽がおうし座 1 度、土星がおうし座 28 度に位置している場合でも、ジョーティッシュではそれらは結合していると見なされます。` } },
      { type: "paragraph", text: { en: `Unlike Western Astrology, Jyotish does not place the same emphasis on distinctions such as oppositions, trines, sextiles, and similar aspect patterns.`, ja: `西洋占星術とは異なり、ジョーティッシュはオポジション、トライン、セクスタイル、類似のアスペクト パターンなどの区別をそれほど重視しません。` } },
      { type: "paragraph", text: { en: `When planets move too close to the Sun, they become weakened and are said to be combust. The exact distance required for combustion varies according to the planet involved.`, ja: `惑星が太陽に近づきすぎると、惑星は弱くなり、燃焼するといわれています。燃焼に必要な正確な距離は、関与する惑星によって異なります。` } },
      { type: "paragraph", text: { en: `As a general guideline, if a planet lies within 10 degrees of the Sun, the possibility of combustion should be considered and the exact combustion limits for that particular planet researched.`, ja: `一般的なガイドラインとして、惑星が太陽から 10 度以内にある場合、燃焼の可能性を考慮し、その特定の惑星の正確な燃焼限界を調査する必要があります。` } },
      { type: "paragraph", text: { en: `Combustion can create a variety of difficulties, including weakening the planet itself, reducing the strength of its natural significations, and negatively affecting the houses it rules.`, ja: `燃焼は、惑星自体の弱体化、自然の意味の強さの減少、惑星が統治する家々への悪影響など、さまざまな困難を引き起こす可能性があります。` } },
      { type: "paragraph", text: { en: `The principle of combustion does not apply to Rahu or Ketu.`, ja: `燃焼の原理はラーフやケートゥには当てはまりません。` } },
    ],
  }
];
