import type { WisdomArticle } from "./types";

/** Articles sourced verbatim from temp-content/p5.txt (link-scrubbed, headings normalized) */
export const p5Articles: WisdomArticle[] = [
  {
    id: "good-bad-houses",
    section: "houses",
    title: { en: `‘Good’ and ‘Bad’ Houses in Jyotish`, ja: `‘Good’ and ‘Bad’ Houses in Jyotish` },
    related: ["twelve-houses","functional-benefics-malefics","planetary-strengths"],
    blocks: [
      { type: "heading", level: 2, text: { en: `‘Good’ and ‘Bad’ Houses in Jyotish`, ja: `‘Good’ and ‘Bad’ Houses in Jyotish` } },
      { type: "paragraph", text: { en: `Summary: Covering the Equal House concept in Jyotish together with an analysis of ‘Good’ and ‘Bad’ houses, including discussions on Kendra, Trikona, Dusthana, and Upachaya houses.`, ja: `Summary: Covering the Equal House concept in Jyotish together with an analysis of ‘Good’ and ‘Bad’ houses, including discussions on Kendra, Trikona, Dusthana, and Upachaya houses.` } },
      { type: "heading", level: 3, text: { en: `The Equal House Concept`, ja: `The Equal House Concept` } },
      { type: "paragraph", text: { en: `Jyotish divides the 360 degrees of the sky into twelve equal sections, each measuring 30 degrees. These divisions create the twelve houses used in Vedic Astrology. Jyotish always employs the Sidereal Zodiac.`, ja: `Jyotish divides the 360 degrees of the sky into twelve equal sections, each measuring 30 degrees. These divisions create the twelve houses used in Vedic Astrology. Jyotish always employs the Sidereal Zodiac.` } },
      { type: "paragraph", text: { en: `Each house governs specific areas of life. Further details regarding the primary significations of the houses can be found in the article The Twelve Houses. Most chart interpretations in Jyotish are based upon a house-by-house examination.`, ja: `Each house governs specific areas of life. Further details regarding the primary significations of the houses can be found in the article The Twelve Houses. Most chart interpretations in Jyotish are based upon a house-by-house examination.` } },
      { type: "paragraph", text: { en: `In Jyotish, each of the twelve houses corresponds exactly to a particular sign. As a result, a house can never overlap two zodiac signs in Vedic Astrology.`, ja: `In Jyotish, each of the twelve houses corresponds exactly to a particular sign. As a result, a house can never overlap two zodiac signs in Vedic Astrology.` } },
      { type: "paragraph", text: { en: `Western Astrology generally begins the first house at the exact degree of the Ascendant. Jyotish follows a different approach. In Vedic Astrology, the entire sign containing the Ascendant becomes the first house, regardless of the Ascendant's exact degree position.[1]`, ja: `Western Astrology generally begins the first house at the exact degree of the Ascendant. Jyotish follows a different approach. In Vedic Astrology, the entire sign containing the Ascendant becomes the first house, regardless of the Ascendant's exact degree position.[1]` } },
      { type: "paragraph", text: { en: `Therefore, if the Ascendant is located at 1 degree Leo, 29 degrees Leo, or anywhere in between, the whole sign of Leo becomes the first house. The second house corresponds entirely with Virgo, the third with Libra, and so on. The house containing the Ascendant is indicated on the birth chart by a diagonal line.`, ja: `Therefore, if the Ascendant is located at 1 degree Leo, 29 degrees Leo, or anywhere in between, the whole sign of Leo becomes the first house. The second house corresponds entirely with Virgo, the third with Libra, and so on. The house containing the Ascendant is indicated on the birth chart by a diagonal line.` } },
      { type: "paragraph", text: { en: `Equal House Diagram in Jyotish`, ja: `Equal House Diagram in Jyotish` } },
      { type: "paragraph", text: { en: `The South Indian chart format, which is often the easiest for beginners to learn, counts houses clockwise from the sign containing the Ascendant. In the example chart above, the Ascendant is marked by the diagonal line in Leo.`, ja: `The South Indian chart format, which is often the easiest for beginners to learn, counts houses clockwise from the sign containing the Ascendant. In the example chart above, the Ascendant is marked by the diagonal line in Leo.` } },
      { type: "paragraph", text: { en: `The zodiac signs always remain in fixed positions within the chart. For example, Pisces will always appear in the upper-left corner.`, ja: `The zodiac signs always remain in fixed positions within the chart. For example, Pisces will always appear in the upper-left corner.` } },
      { type: "paragraph", text: { en: `The meanings assigned to houses in Jyotish are not always identical to those used in Western Astrology.`, ja: `The meanings assigned to houses in Jyotish are not always identical to those used in Western Astrology.` } },
      { type: "paragraph", text: { en: `Errors in recorded birth times can sometimes create significant difficulties, especially when the Ascendant lies close to the boundary between two signs. However, there are methods available to overcome this problem.[2]`, ja: `Errors in recorded birth times can sometimes create significant difficulties, especially when the Ascendant lies close to the boundary between two signs. However, there are methods available to overcome this problem.[2]` } },
      { type: "heading", level: 3, text: { en: `‘Good’ and ‘Bad’ Houses`, ja: `‘Good’ and ‘Bad’ Houses` } },
      { type: "paragraph", text: { en: `The ruling planet of a particular house changes according to the Ascendant.`, ja: `The ruling planet of a particular house changes according to the Ascendant.` } },
      { type: "paragraph", text: { en: `For example, the Moon becomes the ruler of the 1st house for a Cancer Ascendant, while the Sun rules the 1st house for a Leo Ascendant (see the article on planetary rulership of signs).`, ja: `For example, the Moon becomes the ruler of the 1st house for a Cancer Ascendant, while the Sun rules the 1st house for a Leo Ascendant (see the article on planetary rulership of signs).` } },
      { type: "paragraph", text: { en: `Regardless of which zodiac sign is associated with a house, favourable houses strengthen planets placed within them, whereas unfavourable houses tend to weaken them.`, ja: `Regardless of which zodiac sign is associated with a house, favourable houses strengthen planets placed within them, whereas unfavourable houses tend to weaken them.` } },
      { type: "heading", level: 3, text: { en: `Trikona or Trinal Houses`, ja: `Trikona or Trinal Houses` } },
      { type: "paragraph", text: { en: `According to Jyotish, the 5th and 9th houses—known as the Trinal or Trikona houses—are extremely auspicious. Planets placed in these houses generally perform well and gain additional strength.`, ja: `According to Jyotish, the 5th and 9th houses—known as the Trinal or Trikona houses—are extremely auspicious. Planets placed in these houses generally perform well and gain additional strength.` } },
      { type: "paragraph", text: { en: `Many astrologers also regard the 1st house as a Trikona house.`, ja: `Many astrologers also regard the 1st house as a Trikona house.` } },
      { type: "paragraph", text: { en: `As a result, the natural positive qualities of planets occupying the 5th or 9th house become enhanced, allowing them to deliver their beneficial results more fully.`, ja: `As a result, the natural positive qualities of planets occupying the 5th or 9th house become enhanced, allowing them to deliver their beneficial results more fully.` } },
      { type: "paragraph", text: { en: `Any houses governed by those planets also receive significant support and strengthening.`, ja: `Any houses governed by those planets also receive significant support and strengthening.` } },
      { type: "paragraph", text: { en: `The rulers of the 5th and 9th houses carry a naturally positive energy. They bring this favourable influence into whichever house they occupy.`, ja: `The rulers of the 5th and 9th houses carry a naturally positive energy. They bring this favourable influence into whichever house they occupy.` } },
      { type: "paragraph", text: { en: `Likewise, they benefit planets they are conjunct with and those they aspect.`, ja: `Likewise, they benefit planets they are conjunct with and those they aspect.` } },
      { type: "heading", level: 3, text: { en: `Kendras or Angular Houses`, ja: `Kendras or Angular Houses` } },
      { type: "paragraph", text: { en: `The Kendras, or Angular Houses—namely the 1st, 4th, 7th, and 10th houses—are also considered favourable houses. Planets positioned within them gain strength, and the houses themselves represent generally beneficial areas of life.`, ja: `The Kendras, or Angular Houses—namely the 1st, 4th, 7th, and 10th houses—are also considered favourable houses. Planets positioned within them gain strength, and the houses themselves represent generally beneficial areas of life.` } },
      { type: "paragraph", text: { en: `A good house has two important effects. First, it strengthens planets placed within it and the matters associated with those planets. Second, its ruler carries a positive influence that benefits the house where it is placed.`, ja: `A good house has two important effects. First, it strengthens planets placed within it and the matters associated with those planets. Second, its ruler carries a positive influence that benefits the house where it is placed.` } },
      { type: "heading", level: 3, text: { en: `Dusthanas or Negative Houses`, ja: `Dusthanas or Negative Houses` } },
      { type: "paragraph", text: { en: `The 6th, 8th, and 12th houses, known as Dusthanas, are regarded as negative houses.`, ja: `The 6th, 8th, and 12th houses, known as Dusthanas, are regarded as negative houses.` } },
      { type: "paragraph", text: { en: `These houses do not represent anything inherently evil. They are classified as negative because they tend to weaken planets occupying them, reducing the ability of those planets to express their natural positive qualities.`, ja: `These houses do not represent anything inherently evil. They are classified as negative because they tend to weaken planets occupying them, reducing the ability of those planets to express their natural positive qualities.` } },
      { type: "paragraph", text: { en: `Furthermore, the houses ruled by planets placed in the 6th, 8th, or 12th are also weakened, causing difficulties in the affairs associated with those houses.`, ja: `Furthermore, the houses ruled by planets placed in the 6th, 8th, or 12th are also weakened, causing difficulties in the affairs associated with those houses.` } },
      { type: "paragraph", text: { en: `The rulers of the 6th, 8th, and 12th houses are likewise considered to carry a challenging energy. This influence can disturb the house they occupy, the planets they conjoin, and the houses or planets they aspect.`, ja: `The rulers of the 6th, 8th, and 12th houses are likewise considered to carry a challenging energy. This influence can disturb the house they occupy, the planets they conjoin, and the houses or planets they aspect.` } },
      { type: "paragraph", text: { en: `Among the three Dusthanas, the 8th house is generally regarded as the most difficult.`, ja: `Among the three Dusthanas, the 8th house is generally regarded as the most difficult.` } },
      { type: "paragraph", text: { en: `Even though these houses are considered negative, it is important to understand their deeper meaning. A strong 6th house helps us overcome enemies and competitors. A strong 8th house can indicate longevity and vitality. A strong 12th house suggests limited losses and expenditures, while also supporting spiritual growth and progress toward enlightenment.`, ja: `Even though these houses are considered negative, it is important to understand their deeper meaning. A strong 6th house helps us overcome enemies and competitors. A strong 8th house can indicate longevity and vitality. A strong 12th house suggests limited losses and expenditures, while also supporting spiritual growth and progress toward enlightenment.` } },
      { type: "heading", level: 3, text: { en: `Upachaya or Growing Houses`, ja: `Upachaya or Growing Houses` } },
      { type: "paragraph", text: { en: `The 3rd, 6th, 10th, and 11th houses are classified as Upachaya houses, often translated as "growing houses."`, ja: `The 3rd, 6th, 10th, and 11th houses are classified as Upachaya houses, often translated as "growing houses."` } },
      { type: "paragraph", text: { en: `Any difficulties indicated by these houses tend to improve with time, and malefic planets placed within them frequently produce beneficial results as life progresses.`, ja: `Any difficulties indicated by these houses tend to improve with time, and malefic planets placed within them frequently produce beneficial results as life progresses.` } },
      { type: "paragraph", text: { en: `For this reason, malefic planets are often considered well placed when occupying either their Own Signs, Exalted Signs, or Upachaya houses.`, ja: `For this reason, malefic planets are often considered well placed when occupying either their Own Signs, Exalted Signs, or Upachaya houses.` } },
      { type: "heading", level: 3, text: { en: `Footnotes`, ja: `Footnotes` } },
      { type: "paragraph", text: { en: `[1] The Ascendant is the zodiac sign that appears to be rising on the eastern horizon at the moment of birth. For example, if the eastern horizon was at 20 degrees Capricorn at the time of birth, the individual would be said to have a Capricorn Ascendant. The Ascendant is marked on the chart by a diagonal line. Note that this refers to the Sidereal Zodiac used in Jyotish, rather than the Tropical Zodiac used in Western Astrology.`, ja: `[1] The Ascendant is the zodiac sign that appears to be rising on the eastern horizon at the moment of birth. For example, if the eastern horizon was at 20 degrees Capricorn at the time of birth, the individual would be said to have a Capricorn Ascendant. The Ascendant is marked on the chart by a diagonal line. Note that this refers to the Sidereal Zodiac used in Jyotish, rather than the Tropical Zodiac used in Western Astrology.` } },
      { type: "paragraph", text: { en: `[2] Highly skilled and experienced Vedic Astrologers can often work backwards from important life events to determine a person's correct birth time. This process is known as birth-time rectification.`, ja: `[2] Highly skilled and experienced Vedic Astrologers can often work backwards from important life events to determine a person's correct birth time. This process is known as birth-time rectification.` } },
    ],
  },
  {
    id: "natural-benefics-malefics",
    section: "planets",
    title: { en: `Natural Benefic and Malefic Planets`, ja: `Natural Benefic and Malefic Planets` },
    related: ["functional-benefics-malefics","planetary-strengths","planetary-aspects"],
    blocks: [
      { type: "heading", level: 2, text: { en: `Natural Benefic and Malefic Planets`, ja: `Natural Benefic and Malefic Planets` } },
      { type: "paragraph", text: { en: `Summary: An exploration of the natural benefic and malefic planets in Vedic Astrology, including the terminology used in Jyotish and the classification of all nine planets, including Rahu and Ketu.`, ja: `Summary: An exploration of the natural benefic and malefic planets in Vedic Astrology, including the terminology used in Jyotish and the classification of all nine planets, including Rahu and Ketu.` } },
      { type: "heading", level: 3, text: { en: `List of Natural Benefics and Malefics in Jyotish`, ja: `List of Natural Benefics and Malefics in Jyotish` } },
      { type: "paragraph", text: { en: `• Venus, Jupiter, and the waxing Moon are natural benefics.`, ja: `• Venus, Jupiter, and the waxing Moon are natural benefics.` } },
      { type: "paragraph", text: { en: `• Mars, Saturn, Rahu, and Ketu are natural malefics.`, ja: `• Mars, Saturn, Rahu, and Ketu are natural malefics.` } },
      { type: "paragraph", text: { en: `• Mercury's nature depends upon the planets it associates with.`, ja: `• Mercury's nature depends upon the planets it associates with.` } },
      { type: "paragraph", text: { en: `• The Sun is regarded as ‘Cruel’ rather than strictly ‘malefic’.`, ja: `• The Sun is regarded as ‘Cruel’ rather than strictly ‘malefic’.` } },
      { type: "paragraph", text: { en: `• The waning Moon is considered mildly malefic.`, ja: `• The waning Moon is considered mildly malefic.` } },
      { type: "heading", level: 3, text: { en: `Benefics and Malefics – Terminology Explained`, ja: `Benefics and Malefics – Terminology Explained` } },
      { type: "paragraph", text: { en: `From the viewpoint of higher states of consciousness, as described in Vedic literature and the philosophy of Vedanta, there is ultimately no division between ‘good’ and ‘bad’. Things simply exist as they are. The planets function as the ‘cosmic postman’, delivering the results of our past karmas at the appropriate time.`, ja: `From the viewpoint of higher states of consciousness, as described in Vedic literature and the philosophy of Vedanta, there is ultimately no division between ‘good’ and ‘bad’. Things simply exist as they are. The planets function as the ‘cosmic postman’, delivering the results of our past karmas at the appropriate time.` } },
      { type: "paragraph", text: { en: `For practical purposes, however, astrologers often describe planetary influences as ‘good’ when they bring happiness, enjoyment, fulfilment, and favourable outcomes, and as ‘bad’ when they result in disruption, obstacles, suffering, or significant life challenges.`, ja: `For practical purposes, however, astrologers often describe planetary influences as ‘good’ when they bring happiness, enjoyment, fulfilment, and favourable outcomes, and as ‘bad’ when they result in disruption, obstacles, suffering, or significant life challenges.` } },
      { type: "paragraph", text: { en: `In Jyotish, planets that generally produce favourable results are known as benefics, while those that tend to create difficulties are called malefics.`, ja: `In Jyotish, planets that generally produce favourable results are known as benefics, while those that tend to create difficulties are called malefics.` } },
      { type: "paragraph", text: { en: `The Sanskrit term for a natural benefic is ‘shubha’, meaning auspicious, while a natural malefic is called ‘papa’, meaning sinful.`, ja: `The Sanskrit term for a natural benefic is ‘shubha’, meaning auspicious, while a natural malefic is called ‘papa’, meaning sinful.` } },
      { type: "heading", level: 3, text: { en: `Nine ‘Planets’ Used by Jyotish`, ja: `Nine ‘Planets’ Used by Jyotish` } },
      { type: "paragraph", text: { en: `Before proceeding further, it is important to understand that Jyotish does not make use of the outer planets Neptune, Uranus, and Pluto, which are commonly employed in Western Astrology. Likewise, it does not rely on sub-planets or asteroids such as Chiron.`, ja: `Before proceeding further, it is important to understand that Jyotish does not make use of the outer planets Neptune, Uranus, and Pluto, which are commonly employed in Western Astrology. Likewise, it does not rely on sub-planets or asteroids such as Chiron.` } },
      { type: "paragraph", text: { en: `The reason is simple: Jyotish does not require them. Vedic Astrology works with a field of information rather than physical forces emitted by celestial bodies. All the information necessary for accurate karmic prediction is contained within the positions of the nine planetary influences, known collectively as the Navagraha, distributed through the twelve zodiac signs and twenty-seven Nakshatras of the sidereal zodiac.`, ja: `The reason is simple: Jyotish does not require them. Vedic Astrology works with a field of information rather than physical forces emitted by celestial bodies. All the information necessary for accurate karmic prediction is contained within the positions of the nine planetary influences, known collectively as the Navagraha, distributed through the twelve zodiac signs and twenty-seven Nakshatras of the sidereal zodiac.` } },
      { type: "paragraph", text: { en: `The nine ‘planets’ of Vedic Astrology consist of seven physical celestial bodies—the Sun, Moon, Mercury, Venus, Mars, Jupiter, and Saturn—along with two non-physical points. These are the lunar nodes associated with eclipses, representing the locations where the Moon’s orbit intersects the plane of the Earth’s orbit around the Sun.`, ja: `The nine ‘planets’ of Vedic Astrology consist of seven physical celestial bodies—the Sun, Moon, Mercury, Venus, Mars, Jupiter, and Saturn—along with two non-physical points. These are the lunar nodes associated with eclipses, representing the locations where the Moon’s orbit intersects the plane of the Earth’s orbit around the Sun.` } },
      { type: "paragraph", text: { en: `The North Node is known as Rahu, and the South Node is called Ketu.`, ja: `The North Node is known as Rahu, and the South Node is called Ketu.` } },
      { type: "heading", level: 3, text: { en: `Natural Benefic and Natural Malefic Planets`, ja: `Natural Benefic and Natural Malefic Planets` } },
      { type: "paragraph", text: { en: `The idea of a Natural Benefic or Natural Malefic is relatively straightforward.`, ja: `The idea of a Natural Benefic or Natural Malefic is relatively straightforward.` } },
      { type: "paragraph", text: { en: `Some planets are regarded as inherently positive and are generally associated with beneficial outcomes, while others are considered inherently challenging and tend to bring difficulties.`, ja: `Some planets are regarded as inherently positive and are generally associated with beneficial outcomes, while others are considered inherently challenging and tend to bring difficulties.` } },
      { type: "paragraph", text: { en: `In Vedic Astrology, Jupiter and Venus are two well-known examples of natural benefic planets.`, ja: `In Vedic Astrology, Jupiter and Venus are two well-known examples of natural benefic planets.` } },
      { type: "paragraph", text: { en: `Similarly, Mars and Saturn are considered natural malefics in Jyotish.`, ja: `Similarly, Mars and Saturn are considered natural malefics in Jyotish.` } },
      { type: "paragraph", text: { en: `These classifications are largely familiar to Western Astrologers. However, significant differences arise when considering the remaining planets and how they are interpreted in Jyotish compared with Western Astrology.`, ja: `These classifications are largely familiar to Western Astrologers. However, significant differences arise when considering the remaining planets and how they are interpreted in Jyotish compared with Western Astrology.` } },
      { type: "heading", level: 3, text: { en: `What About Mercury?`, ja: `What About Mercury?` } },
      { type: "paragraph", text: { en: `Mercury occupies a unique position. When Mercury is alone or associated with benefic planets—through conjunctions or benefic aspects—it behaves as a benefic. When it is associated with malefics, it tends to act as a malefic.`, ja: `Mercury occupies a unique position. When Mercury is alone or associated with benefic planets—through conjunctions or benefic aspects—it behaves as a benefic. When it is associated with malefics, it tends to act as a malefic.` } },
      { type: "paragraph", text: { en: `In other words, Mercury adopts either a benefic or malefic role depending upon the company it keeps.`, ja: `In other words, Mercury adopts either a benefic or malefic role depending upon the company it keeps.` } },
      { type: "heading", level: 3, text: { en: `What About the Sun, Moon, Rahu and Ketu?`, ja: `What About the Sun, Moon, Rahu and Ketu?` } },
      { type: "paragraph", text: { en: `The remaining planetary influences—Sun, Moon, Rahu, and Ketu—require separate consideration.`, ja: `The remaining planetary influences—Sun, Moon, Rahu, and Ketu—require separate consideration.` } },
      { type: "heading", level: 3, text: { en: `The Sun`, ja: `The Sun` } },
      { type: "paragraph", text: { en: `In Jyotish, the Sun is not classified as a natural benefic. This often surprises astrologers trained in the Western tradition.`, ja: `In Jyotish, the Sun is not classified as a natural benefic. This often surprises astrologers trained in the Western tradition.` } },
      { type: "paragraph", text: { en: `Because of its intense heat and powerful nature, the Sun is frequently described by Vedic Astrologers as ‘cruel’. In practical terms, planets situated very close to the Sun in a birth chart become combust or scorched.`, ja: `Because of its intense heat and powerful nature, the Sun is frequently described by Vedic Astrologers as ‘cruel’. In practical terms, planets situated very close to the Sun in a birth chart become combust or scorched.` } },
      { type: "paragraph", text: { en: `As a result, natural benefics such as Venus may be unable to deliver their usual positive effects when combust, while natural malefics such as Mars can sometimes become even more troublesome under combustion.`, ja: `As a result, natural benefics such as Venus may be unable to deliver their usual positive effects when combust, while natural malefics such as Mars can sometimes become even more troublesome under combustion.` } },
      { type: "heading", level: 3, text: { en: `The Moon`, ja: `The Moon` } },
      { type: "paragraph", text: { en: `The Moon’s benefic or malefic nature depends largely on whether it is increasing or decreasing in brightness.`, ja: `The Moon’s benefic or malefic nature depends largely on whether it is increasing or decreasing in brightness.` } },
      { type: "paragraph", text: { en: `A Full Moon is considered highly auspicious. A waxing Moon is regarded as a natural benefic and is generally associated with favourable results.`, ja: `A Full Moon is considered highly auspicious. A waxing Moon is regarded as a natural benefic and is generally associated with favourable results.` } },
      { type: "paragraph", text: { en: `A waning Moon, on the other hand, is viewed as malefic, although only mildly so. Many astrologers prefer to describe it as ‘ashubha’, meaning not auspicious, rather than fully malefic.`, ja: `A waning Moon, on the other hand, is viewed as malefic, although only mildly so. Many astrologers prefer to describe it as ‘ashubha’, meaning not auspicious, rather than fully malefic.` } },
      { type: "heading", level: 3, text: { en: `Rahu and Ketu`, ja: `Rahu and Ketu` } },
      { type: "paragraph", text: { en: `Jyotish places considerable emphasis on Rahu and Ketu, the lunar nodes.`, ja: `Jyotish places considerable emphasis on Rahu and Ketu, the lunar nodes.` } },
      { type: "paragraph", text: { en: `Although they have no physical existence and are simply calculated points where the Moon’s orbit intersects the ecliptic, they signify powerful and very real karmic influences.`, ja: `Although they have no physical existence and are simply calculated points where the Moon’s orbit intersects the ecliptic, they signify powerful and very real karmic influences.` } },
      { type: "paragraph", text: { en: `In Vedic Astrology, both Rahu and Ketu are classified as natural malefics.`, ja: `In Vedic Astrology, both Rahu and Ketu are classified as natural malefics.` } },
      { type: "heading", level: 3, text: { en: `Modifying Factors`, ja: `Modifying Factors` } },
      { type: "paragraph", text: { en: `People who are new to Jyotish often ask what kinds of benefits a natural benefic such as Venus can actually provide. The answer depends greatly on its placement within an individual's birth chart.`, ja: `People who are new to Jyotish often ask what kinds of benefits a natural benefic such as Venus can actually provide. The answer depends greatly on its placement within an individual's birth chart.` } },
      { type: "paragraph", text: { en: `The following general principles apply:`, ja: `The following general principles apply:` } },
      { type: "heading", level: 3, text: { en: `Planetary Strength Matters`, ja: `Planetary Strength Matters` } },
      { type: "paragraph", text: { en: `Strong planets are capable of producing stronger results than weak planets.`, ja: `Strong planets are capable of producing stronger results than weak planets.` } },
      { type: "paragraph", text: { en: `A powerful natural benefic can bring substantial benefits, whereas a weak benefic may struggle to produce positive outcomes.`, ja: `A powerful natural benefic can bring substantial benefits, whereas a weak benefic may struggle to produce positive outcomes.` } },
      { type: "paragraph", text: { en: `Planetary strength depends significantly on zodiacal placement. Each planet has a specific sign in which it becomes exceptionally strong, known as its exaltation. The sign directly opposite its exaltation is where the planet becomes greatly weakened and is said to be debilitated or fallen.`, ja: `Planetary strength depends significantly on zodiacal placement. Each planet has a specific sign in which it becomes exceptionally strong, known as its exaltation. The sign directly opposite its exaltation is where the planet becomes greatly weakened and is said to be debilitated or fallen.` } },
      { type: "paragraph", text: { en: `A natural benefic placed in its exaltation sign or its own sign is generally highly favourable for the native.`, ja: `A natural benefic placed in its exaltation sign or its own sign is generally highly favourable for the native.` } },
      { type: "paragraph", text: { en: `For a more detailed discussion, see: Planetary Strengths or Powers.`, ja: `For a more detailed discussion, see: Planetary Strengths or Powers.` } },
      { type: "heading", level: 3, text: { en: `Strong Malefics and Weak Malefics`, ja: `Strong Malefics and Weak Malefics` } },
      { type: "paragraph", text: { en: `A strong natural malefic—such as one placed in exaltation or its own sign—will often contribute positively to the affairs of the house it occupies. Strength tends to enhance the constructive qualities of a malefic planet.`, ja: `A strong natural malefic—such as one placed in exaltation or its own sign—will often contribute positively to the affairs of the house it occupies. Strength tends to enhance the constructive qualities of a malefic planet.` } },
      { type: "paragraph", text: { en: `Conversely, a weak malefic is more likely to create significant difficulties.`, ja: `Conversely, a weak malefic is more likely to create significant difficulties.` } },
      { type: "paragraph", text: { en: `For example, a strong Mars can provide courage, initiative, determination, and healthy motivation.`, ja: `For example, a strong Mars can provide courage, initiative, determination, and healthy motivation.` } },
      { type: "heading", level: 3, text: { en: `Saturn – A Special Case`, ja: `Saturn – A Special Case` } },
      { type: "paragraph", text: { en: `The above principle is generally applicable, but Saturn deserves special mention.`, ja: `The above principle is generally applicable, but Saturn deserves special mention.` } },
      { type: "paragraph", text: { en: `A strong Saturn can bestow qualities such as humility, patience, discipline, and integrity. At the same time, during its period of operation (Mahadasha), it may also bring greater adversity, responsibility, or sorrow.`, ja: `A strong Saturn can bestow qualities such as humility, patience, discipline, and integrity. At the same time, during its period of operation (Mahadasha), it may also bring greater adversity, responsibility, or sorrow.` } },
      { type: "heading", level: 3, text: { en: `Further Study`, ja: `Further Study` } },
      { type: "paragraph", text: { en: `The planetary indicators (Karakas) connected with various physiological, psychological, and sociological aspects of an individual are discussed separately in another article.`, ja: `The planetary indicators (Karakas) connected with various physiological, psychological, and sociological aspects of an individual are discussed separately in another article.` } },
    ],
  },
  {
    id: "functional-benefics-malefics",
    section: "planets",
    title: { en: `Functional Benefics and Malefics for All Ascendants`, ja: `Functional Benefics and Malefics for All Ascendants` },
    related: ["natural-benefics-malefics","gemstones","twelve-houses"],
    blocks: [
      { type: "heading", level: 2, text: { en: `Functional Benefics and Malefics for All Ascendants`, ja: `Functional Benefics and Malefics for All Ascendants` } },
      { type: "paragraph", text: { en: `Summary: A list of the functional benefic and functional malefic planets for each of the twelve ascendants in the Sidereal Zodiac used by Vedic Astrology. This is essential information for chart interpretation and the application of remedial measures.`, ja: `Summary: A list of the functional benefic and functional malefic planets for each of the twelve ascendants in the Sidereal Zodiac used by Vedic Astrology. This is essential information for chart interpretation and the application of remedial measures.` } },
      { type: "paragraph", text: { en: `List of Functional Benefics and Malefics for all Ascendants`, ja: `List of Functional Benefics and Malefics for all Ascendants` } },
      { type: "paragraph", text: { en: `This information is absolutely fundamental to Jyotish and forms an important part of chart interpretation.`, ja: `This information is absolutely fundamental to Jyotish and forms an important part of chart interpretation.` } },
      { type: "paragraph", text: { en: `It is also crucial when prescribing suitable remedial measures to balance planetary energies for a particular ascendant. As a general rule, functional benefic planets may be strengthened through appropriate gemstones. Functional malefics, however, should generally not be strengthened in this way, and alternative remedies such as planetary mantras are often preferred.`, ja: `It is also crucial when prescribing suitable remedial measures to balance planetary energies for a particular ascendant. As a general rule, functional benefic planets may be strengthened through appropriate gemstones. Functional malefics, however, should generally not be strengthened in this way, and alternative remedies such as planetary mantras are often preferred.` } },
      { type: "paragraph", text: { en: `This guide to functional benefics and malefics for all twelve ascendants is intended for students of Jyotish who already possess a basic understanding of the subject. Please note the following:`, ja: `This guide to functional benefics and malefics for all twelve ascendants is intended for students of Jyotish who already possess a basic understanding of the subject. Please note the following:` } },
      { type: "paragraph", text: { en: `• The numbers shown in brackets, for example (9 & 12), refer to the houses ruled or owned by the planet relative to the specific ascendant in the Sidereal Zodiac.`, ja: `• The numbers shown in brackets, for example (9 & 12), refer to the houses ruled or owned by the planet relative to the specific ascendant in the Sidereal Zodiac.` } },
      { type: "paragraph", text: { en: `• Rahu and Ketu do not own any houses and are therefore not classified as functional benefics or malefics. They remain natural malefics.`, ja: `• Rahu and Ketu do not own any houses and are therefore not classified as functional benefics or malefics. They remain natural malefics.` } },
      { type: "paragraph", text: { en: `• The notes provided below are derived mainly from the teachings of Parashara.`, ja: `• The notes provided below are derived mainly from the teachings of Parashara.` } },
      { type: "paragraph", text: { en: `• Where available, the degree of positivity or negativity is indicated using a grading scale from 1 to 5.[1]`, ja: `• Where available, the degree of positivity or negativity is indicated using a grading scale from 1 to 5.[1]` } },
      { type: "paragraph", text: { en: `• A Grade 5 benefic is exceptionally auspicious and considerably more favourable than a Grade 1 benefic.`, ja: `• A Grade 5 benefic is exceptionally auspicious and considerably more favourable than a Grade 1 benefic.` } },
      { type: "paragraph", text: { en: `• A Grade 5 malefic is highly problematic and far more difficult than a Grade 1 malefic.`, ja: `• A Grade 5 malefic is highly problematic and far more difficult than a Grade 1 malefic.` } },
      { type: "paragraph", text: { en: `• The ruler of the Ascendant never harms the native.`, ja: `• The ruler of the Ascendant never harms the native.` } },
      { type: "paragraph", text: { en: `• Not all Jyotish astrologers will agree completely on every point listed below. Jyotish contains many layers, subtleties, and exceptions, but the following serves as a useful general guide.`, ja: `• Not all Jyotish astrologers will agree completely on every point listed below. Jyotish contains many layers, subtleties, and exceptions, but the following serves as a useful general guide.` } },
      { type: "heading", level: 3, text: { en: `Aries Ascendant`, ja: `Aries Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(9 & 12)`, ja: `(9 & 12)` }, { en: `Very auspicious – Grade 4`, ja: `Very auspicious – Grade 4` }],
        [{ en: `Sun`, ja: `Sun` }, { en: `(5)`, ja: `(5)` }, { en: `Auspicious – Grade 2`, ja: `Auspicious – Grade 2` }],
        [{ en: `Mars`, ja: `Mars` }, { en: `(1 & 8)`, ja: `(1 & 8)` }, { en: `Helpful to auspicious planets`, ja: `Helpful to auspicious planets` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(10 & 11)`, ja: `(10 & 11)` }, { en: `Inauspicious – Grade 3`, ja: `Inauspicious – Grade 3` }],
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(3 & 6)`, ja: `(3 & 6)` }, { en: `Inauspicious – Grade 3`, ja: `Inauspicious – Grade 3` }],
        [{ en: `Venus`, ja: `Venus` }, { en: `(2 & 7)`, ja: `(2 & 7)` }, { en: `Inauspicious – Grade 1`, ja: `Inauspicious – Grade 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Mars has its Moolatrikona sign in Aries (1) and is therefore predominantly favourable.`, ja: `• Mars has its Moolatrikona sign in Aries (1) and is therefore predominantly favourable.` } },
      { type: "paragraph", text: { en: `• Mars assists the Sun and Jupiter. Some astrologers also include the Moon in this category.`, ja: `• Mars assists the Sun and Jupiter. Some astrologers also include the Moon in this category.` } },
      { type: "paragraph", text: { en: `• Saturn associated with Venus is generally unfavourable.`, ja: `• Saturn associated with Venus is generally unfavourable.` } },
      { type: "paragraph", text: { en: `• Associations between Jupiter–Sun, Jupiter–Mars, and Mars–Sun are considered beneficial.`, ja: `• Associations between Jupiter–Sun, Jupiter–Mars, and Mars–Sun are considered beneficial.` } },
      { type: "paragraph", text: { en: `• A conjunction between Saturn and Jupiter does not usually produce auspicious results.`, ja: `• A conjunction between Saturn and Jupiter does not usually produce auspicious results.` } },
      { type: "paragraph", text: { en: `• Jupiter operating under the influence of a malefic can produce inauspicious outcomes.`, ja: `• Jupiter operating under the influence of a malefic can produce inauspicious outcomes.` } },
      { type: "heading", level: 3, text: { en: `Taurus Ascendant`, ja: `Taurus Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(9 & 10)`, ja: `(9 & 10)` }, { en: `Very auspicious (Yogakaraka)`, ja: `Very auspicious (Yogakaraka)` }],
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(2 & 5)`, ja: `(2 & 5)` }, { en: `Auspicious`, ja: `Auspicious` }],
        [{ en: `Sun`, ja: `Sun` }, { en: `(4)`, ja: `(4)` }, { en: `Beneficial`, ja: `Beneficial` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(8 & 11)`, ja: `(8 & 11)` }, { en: `Very adverse indeed`, ja: `Very adverse indeed` }],
        [{ en: `Mars`, ja: `Mars` }, { en: `(7 & 12)`, ja: `(7 & 12)` }, { en: `Maraka`, ja: `Maraka` }],
        [{ en: `Moon`, ja: `Moon` }, { en: `(3)`, ja: `(3)` }, { en: `Inauspicious`, ja: `Inauspicious` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• The Moon, as ruler of the 3rd house, is not particularly auspicious, though not excessively harmful. The 3rd house is considered less troublesome than the 6th, which itself is generally less difficult than the 11th.`, ja: `• The Moon, as ruler of the 3rd house, is not particularly auspicious, though not excessively harmful. The 3rd house is considered less troublesome than the 6th, which itself is generally less difficult than the 11th.` } },
      { type: "paragraph", text: { en: `• Parashara classifies Venus as a malefic despite ruling the Ascendant. This is presumably because Libra, Venus' Moolatrikona sign, falls in the 6th house from Taurus.`, ja: `• Parashara classifies Venus as a malefic despite ruling the Ascendant. This is presumably because Libra, Venus' Moolatrikona sign, falls in the 6th house from Taurus.` } },
      { type: "paragraph", text: { en: `• Other astrologers maintain that Venus remains benefic for Taurus Lagna because it rules the Ascendant, which functions as both a Trine and a Kendra. They argue that the Ascendant lord is always beneficial.`, ja: `• Other astrologers maintain that Venus remains benefic for Taurus Lagna because it rules the Ascendant, which functions as both a Trine and a Kendra. They argue that the Ascendant lord is always beneficial.` } },
      { type: "paragraph", text: { en: `• Mercury acts more effectively when associated with Saturn or the Sun.`, ja: `• Mercury acts more effectively when associated with Saturn or the Sun.` } },
      { type: "heading", level: 3, text: { en: `Gemini Ascendant`, ja: `Gemini Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Venus`, ja: `Venus` }, { en: `(5 & 12)`, ja: `(5 & 12)` }, { en: `Auspicious – Grade 2`, ja: `Auspicious – Grade 2` }],
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(8 & 9)`, ja: `(8 & 9)` }, { en: `Auspicious – see notes`, ja: `Auspicious – see notes` }],
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(1 & 4)`, ja: `(1 & 4)` }, { en: `Auspicious`, ja: `Auspicious` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mars`, ja: `Mars` }, { en: `(6 & 11)`, ja: `(6 & 11)` }, { en: `Very adverse indeed – Grade 5`, ja: `Very adverse indeed – Grade 5` }],
        [{ en: `Sun`, ja: `Sun` }, { en: `(3)`, ja: `(3)` }, { en: `Inauspicious – Grade 1`, ja: `Inauspicious – Grade 1` }],
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(7 & 10)`, ja: `(7 & 10)` }, { en: `Inauspicious`, ja: `Inauspicious` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Venus is highly favourable because the 5th house (Libra) is its Moolatrikona sign.`, ja: `• Venus is highly favourable because the 5th house (Libra) is its Moolatrikona sign.` } },
      { type: "paragraph", text: { en: `• Saturn's role as ruler of the 8th and 9th houses is not specifically discussed by Parashara. Since Aquarius, Saturn's Moolatrikona sign, is the 9th house, Saturn is generally considered favourable, though the overall chart should always be examined.`, ja: `• Saturn's role as ruler of the 8th and 9th houses is not specifically discussed by Parashara. Since Aquarius, Saturn's Moolatrikona sign, is the 9th house, Saturn is generally considered favourable, though the overall chart should always be examined.` } },
      { type: "paragraph", text: { en: `• The Sun's rulership of the 3rd house is not especially beneficial.`, ja: `• The Sun's rulership of the 3rd house is not especially beneficial.` } },
      { type: "heading", level: 3, text: { en: `Cancer Ascendant`, ja: `Cancer Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mars`, ja: `Mars` }, { en: `(5 & 10)`, ja: `(5 & 10)` }, { en: `Auspicious – Grade 2 (Yogakaraka)`, ja: `Auspicious – Grade 2 (Yogakaraka)` }],
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(6 & 9)`, ja: `(6 & 9)` }, { en: `Auspicious – Grade 2`, ja: `Auspicious – Grade 2` }],
        [{ en: `Moon`, ja: `Moon` }, { en: `(1)`, ja: `(1)` }, { en: `Beneficial`, ja: `Beneficial` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Venus`, ja: `Venus` }, { en: `(4 & 11)`, ja: `(4 & 11)` }, { en: `Inauspicious – Grade 3`, ja: `Inauspicious – Grade 3` }],
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(3 & 12)`, ja: `(3 & 12)` }, { en: `Inauspicious – Grade 3`, ja: `Inauspicious – Grade 3` }],
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(7 & 8)`, ja: `(7 & 8)` }, { en: `Strong Maraka`, ja: `Strong Maraka` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Mars associated with the Sun, Moon, or Jupiter is considered highly favourable.`, ja: `• Mars associated with the Sun, Moon, or Jupiter is considered highly favourable.` } },
      { type: "heading", level: 3, text: { en: `Leo Ascendant`, ja: `Leo Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mars`, ja: `Mars` }, { en: `(4 & 9)`, ja: `(4 & 9)` }, { en: `Extremely auspicious – Grade 5 (Yogakaraka)`, ja: `Extremely auspicious – Grade 5 (Yogakaraka)` }],
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(5 & 8)`, ja: `(5 & 8)` }, { en: `Auspicious – Grade 2`, ja: `Auspicious – Grade 2` }],
        [{ en: `Sun`, ja: `Sun` }, { en: `(1)`, ja: `(1)` }, { en: `Beneficial`, ja: `Beneficial` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(2 & 11)`, ja: `(2 & 11)` }, { en: `Very inauspicious – Grade 4`, ja: `Very inauspicious – Grade 4` }],
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(6 & 7)`, ja: `(6 & 7)` }, { en: `Inauspicious – Grade 2`, ja: `Inauspicious – Grade 2` }],
        [{ en: `Venus`, ja: `Venus` }, { en: `(3 & 10)`, ja: `(3 & 10)` }, { en: `Inauspicious – Grade 1`, ja: `Inauspicious – Grade 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Many astrologers regard Venus as somewhat unreliable for Leo Ascendant.`, ja: `• Many astrologers regard Venus as somewhat unreliable for Leo Ascendant.` } },
      { type: "paragraph", text: { en: `• A conjunction of Jupiter and Venus generally does not produce auspicious results.`, ja: `• A conjunction of Jupiter and Venus generally does not produce auspicious results.` } },
      { type: "heading", level: 3, text: { en: `Virgo Ascendant`, ja: `Virgo Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Venus`, ja: `Venus` }, { en: `(2 & 9)`, ja: `(2 & 9)` }, { en: `Very auspicious (Yogakaraka)`, ja: `Very auspicious (Yogakaraka)` }],
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(1 & 10)`, ja: `(1 & 10)` }, { en: `Auspicious`, ja: `Auspicious` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mars`, ja: `Mars` }, { en: `(3 & 8)`, ja: `(3 & 8)` }, { en: `Very inauspicious – Grade 4`, ja: `Very inauspicious – Grade 4` }],
        [{ en: `Moon`, ja: `Moon` }, { en: `(11)`, ja: `(11)` }, { en: `Inauspicious – Grade 3`, ja: `Inauspicious – Grade 3` }],
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(4 & 7)`, ja: `(4 & 7)` }, { en: `Inauspicious – Grade 1`, ja: `Inauspicious – Grade 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• The Sun's role as ruler of the 12th depends heavily upon its associations and is generally acceptable when joined with benefic planets in favourable houses.`, ja: `• The Sun's role as ruler of the 12th depends heavily upon its associations and is generally acceptable when joined with benefic planets in favourable houses.` } },
      { type: "paragraph", text: { en: `• Saturn (5th and 6th lord) is not specifically mentioned by Parashara. It is generally favourable due to its rulership of the 5th and relationship with Mercury, although some doshas arise because of its 6th house ownership.`, ja: `• Saturn (5th and 6th lord) is not specifically mentioned by Parashara. It is generally favourable due to its rulership of the 5th and relationship with Mercury, although some doshas arise because of its 6th house ownership.` } },
      { type: "paragraph", text: { en: `• Jupiter, ruling the 4th and 7th houses, becomes a Maraka.`, ja: `• Jupiter, ruling the 4th and 7th houses, becomes a Maraka.` } },
      { type: "heading", level: 3, text: { en: `Libra Ascendant`, ja: `Libra Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(9 & 12)`, ja: `(9 & 12)` }, { en: `Very auspicious – Grade 4`, ja: `Very auspicious – Grade 4` }],
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(4 & 5)`, ja: `(4 & 5)` }, { en: `Auspicious – Grade 3 (Yogakaraka)`, ja: `Auspicious – Grade 3 (Yogakaraka)` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(3 & 6)`, ja: `(3 & 6)` }, { en: `Inauspicious – Grade 3`, ja: `Inauspicious – Grade 3` }],
        [{ en: `Sun`, ja: `Sun` }, { en: `(11)`, ja: `(11)` }, { en: `Inauspicious – Grade 3`, ja: `Inauspicious – Grade 3` }],
        [{ en: `Mars`, ja: `Mars` }, { en: `(2 & 7)`, ja: `(2 & 7)` }, { en: `Inauspicious – Grade 1`, ja: `Inauspicious – Grade 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Venus rules the 1st and 8th houses. Parashara describes Venus as neutral. However, many astrologers argue that Venus should be regarded as auspicious because it rules the Lagna. An interesting debate.`, ja: `• Venus rules the 1st and 8th houses. Parashara describes Venus as neutral. However, many astrologers argue that Venus should be regarded as auspicious because it rules the Lagna. An interesting debate.` } },
      { type: "paragraph", text: { en: `• The Moon (10th lord) associated with Mercury (9th and 12th lord) can create Rajayoga.`, ja: `• The Moon (10th lord) associated with Mercury (9th and 12th lord) can create Rajayoga.` } },
      { type: "paragraph", text: { en: `• Mars functions as a Maraka.`, ja: `• Mars functions as a Maraka.` } },
      { type: "heading", level: 3, text: { en: `Scorpio Ascendant`, ja: `Scorpio Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Moon`, ja: `Moon` }, { en: `(9)`, ja: `(9)` }, { en: `Very auspicious – Grade 4`, ja: `Very auspicious – Grade 4` }],
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(2 & 5)`, ja: `(2 & 5)` }, { en: `Auspicious – Grade 2`, ja: `Auspicious – Grade 2` }],
        [{ en: `Sun`, ja: `Sun` }, { en: `(10)`, ja: `(10)` }, { en: `Auspicious – Grade 1`, ja: `Auspicious – Grade 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(8 & 11)`, ja: `(8 & 11)` }, { en: `Very adverse indeed – Grade 5`, ja: `Very adverse indeed – Grade 5` }],
        [{ en: `Venus`, ja: `Venus` }, { en: `(7 & 12)`, ja: `(7 & 12)` }, { en: `Inauspicious – Grade 2`, ja: `Inauspicious – Grade 2` }],
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(3 & 4)`, ja: `(3 & 4)` }, { en: `Inauspicious – Grade 1`, ja: `Inauspicious – Grade 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Mars (1 & 6) is classified as neutral. However, many astrologers would regard Mars as auspicious because it rules the Lagna.`, ja: `• Mars (1 & 6) is classified as neutral. However, many astrologers would regard Mars as auspicious because it rules the Lagna.` } },
      { type: "paragraph", text: { en: `• Venus functions as a Maraka.`, ja: `• Venus functions as a Maraka.` } },
      { type: "paragraph", text: { en: `• The Sun and Moon together can produce Yogakaraka effects.`, ja: `• The Sun and Moon together can produce Yogakaraka effects.` } },
      { type: "heading", level: 3, text: { en: `Sagittarius Ascendant`, ja: `Sagittarius Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Sun`, ja: `Sun` }, { en: `(9)`, ja: `(9)` }, { en: `Very auspicious – Grade 4`, ja: `Very auspicious – Grade 4` }],
        [{ en: `Mars`, ja: `Mars` }, { en: `(5 & 12)`, ja: `(5 & 12)` }, { en: `Auspicious – Grade 2`, ja: `Auspicious – Grade 2` }],
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(7 & 10)`, ja: `(7 & 10)` }, { en: `Auspicious`, ja: `Auspicious` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Venus`, ja: `Venus` }, { en: `(6 & 11)`, ja: `(6 & 11)` }, { en: `Very adverse indeed – Grade 5`, ja: `Very adverse indeed – Grade 5` }],
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(2 & 3)`, ja: `(2 & 3)` }, { en: `Inauspicious – Grade 2`, ja: `Inauspicious – Grade 2` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• The Moon, as ruler of the 8th house, is not specifically listed as inauspicious. It is generally considered favourable when associated with Mercury, the Sun, or Mars.`, ja: `• The Moon, as ruler of the 8th house, is not specifically listed as inauspicious. It is generally considered favourable when associated with Mercury, the Sun, or Mars.` } },
      { type: "paragraph", text: { en: `• Mercury is auspicious because its Moolatrikona sign governs the 10th house.`, ja: `• Mercury is auspicious because its Moolatrikona sign governs the 10th house.` } },
      { type: "paragraph", text: { en: `• A mutual association between the Sun and Mercury creates Yoga.`, ja: `• A mutual association between the Sun and Mercury creates Yoga.` } },
      { type: "paragraph", text: { en: `• An association between the Moon and Jupiter forms a favourable Yoga.`, ja: `• An association between the Moon and Jupiter forms a favourable Yoga.` } },
      { type: "paragraph", text: { en: `• Jupiter is regarded as neutral.`, ja: `• Jupiter is regarded as neutral.` } },
      { type: "heading", level: 3, text: { en: `Capricorn Ascendant`, ja: `Capricorn Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Venus`, ja: `Venus` }, { en: `(5 & 10)`, ja: `(5 & 10)` }, { en: `Very auspicious (Yogakaraka)`, ja: `Very auspicious (Yogakaraka)` }],
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(6 & 9)`, ja: `(6 & 9)` }, { en: `Auspicious`, ja: `Auspicious` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mars`, ja: `Mars` }, { en: `(4 & 11)`, ja: `(4 & 11)` }, { en: `Inauspicious – Grade 3`, ja: `Inauspicious – Grade 3` }],
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(3 & 12)`, ja: `(3 & 12)` }, { en: `Inauspicious`, ja: `Inauspicious` }],
        [{ en: `Moon`, ja: `Moon` }, { en: `(7)`, ja: `(7)` }, { en: `See notes`, ja: `See notes` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Saturn (1 & 2) is classified as neutral. However, many astrologers regard Saturn as auspicious because it rules the Ascendant.`, ja: `• Saturn (1 & 2) is classified as neutral. However, many astrologers regard Saturn as auspicious because it rules the Ascendant.` } },
      { type: "paragraph", text: { en: `• The Sun (8th lord) is generally considered neutral.`, ja: `• The Sun (8th lord) is generally considered neutral.` } },
      { type: "paragraph", text: { en: `• The Moon functions as a Maraka.`, ja: `• The Moon functions as a Maraka.` } },
      { type: "heading", level: 3, text: { en: `Aquarius Ascendant`, ja: `Aquarius Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Venus`, ja: `Venus` }, { en: `(4 & 9)`, ja: `(4 & 9)` }, { en: `Extremely auspicious – Grade 5 (Yogakaraka)`, ja: `Extremely auspicious – Grade 5 (Yogakaraka)` }],
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(1 & 12)`, ja: `(1 & 12)` }, { en: `Auspicious`, ja: `Auspicious` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(2 & 11)`, ja: `(2 & 11)` }, { en: `Very adverse indeed – Grade 5`, ja: `Very adverse indeed – Grade 5` }],
        [{ en: `Moon`, ja: `Moon` }, { en: `(6)`, ja: `(6)` }, { en: `Inauspicious – Grade 2`, ja: `Inauspicious – Grade 2` }],
        [{ en: `Mars`, ja: `Mars` }, { en: `(3 & 10)`, ja: `(3 & 10)` }, { en: `Inauspicious – Grade 1`, ja: `Inauspicious – Grade 1` }],
        [{ en: `Sun`, ja: `Sun` }, { en: `(7)`, ja: `(7)` }, { en: `Maraka tendencies`, ja: `Maraka tendencies` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Venus produces Rajayoga.`, ja: `• Venus produces Rajayoga.` } },
      { type: "paragraph", text: { en: `• Saturn is considered auspicious because Aquarius is its Moolatrikona sign.`, ja: `• Saturn is considered auspicious because Aquarius is its Moolatrikona sign.` } },
      { type: "paragraph", text: { en: `• Mercury (5 & 8) should generally be favourable but can produce mixed results depending upon its associations.`, ja: `• Mercury (5 & 8) should generally be favourable but can produce mixed results depending upon its associations.` } },
      { type: "heading", level: 3, text: { en: `Pisces Ascendant`, ja: `Pisces Ascendant` } },
      { type: "heading", level: 3, text: { en: `Functional Benefics`, ja: `Functional Benefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Mars`, ja: `Mars` }, { en: `(2 & 9)`, ja: `(2 & 9)` }, { en: `Very auspicious – Grade 4`, ja: `Very auspicious – Grade 4` }],
        [{ en: `Moon`, ja: `Moon` }, { en: `(5)`, ja: `(5)` }, { en: `Auspicious – Grade 2`, ja: `Auspicious – Grade 2` }],
        [{ en: `Jupiter`, ja: `Jupiter` }, { en: `(1 & 10)`, ja: `(1 & 10)` }, { en: `Auspicious – Grade 1`, ja: `Auspicious – Grade 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Functional Malefics`, ja: `Functional Malefics` } },
      { type: "table", headers: [{ en: `Planet`, ja: `Planet` }, { en: `Houses Ruled`, ja: `Houses Ruled` }, { en: `Notes`, ja: `Notes` }], rows: [
        [{ en: `Saturn`, ja: `Saturn` }, { en: `(11 & 12)`, ja: `(11 & 12)` }, { en: `Very adverse indeed – Grade 5`, ja: `Very adverse indeed – Grade 5` }],
        [{ en: `Venus`, ja: `Venus` }, { en: `(3 & 8)`, ja: `(3 & 8)` }, { en: `Very inauspicious – Grade 4`, ja: `Very inauspicious – Grade 4` }],
        [{ en: `Sun`, ja: `Sun` }, { en: `(6)`, ja: `(6)` }, { en: `Inauspicious – Grade 2`, ja: `Inauspicious – Grade 2` }],
        [{ en: `Mercury`, ja: `Mercury` }, { en: `(4 & 7)`, ja: `(4 & 7)` }, { en: `Inauspicious – Grade 1`, ja: `Inauspicious – Grade 1` }],
      ] },
      { type: "heading", level: 3, text: { en: `Notes`, ja: `Notes` } },
      { type: "paragraph", text: { en: `• Pandit Ojha states that a Sambandha between Mars and Jupiter creates Rajayoga.`, ja: `• Pandit Ojha states that a Sambandha between Mars and Jupiter creates Rajayoga.` } },
    ],
  },
  {
    id: "planetary-aspects",
    section: "aspects",
    title: { en: `Planetary Aspects`, ja: `Planetary Aspects` },
    related: ["planetary-strengths","natural-benefics-malefics","twelve-houses"],
    blocks: [
      { type: "heading", level: 2, text: { en: `Planetary Aspects`, ja: `Planetary Aspects` } },
      { type: "paragraph", text: { en: `Summary: Explaining the concept of Planetary Aspects in Jyotish and examining the rules required to apply these principles. Also highlighting the major differences between aspects in Vedic Astrology and Western Astrology.`, ja: `Summary: Explaining the concept of Planetary Aspects in Jyotish and examining the rules required to apply these principles. Also highlighting the major differences between aspects in Vedic Astrology and Western Astrology.` } },
      { type: "paragraph", text: { en: `Planetary aspects are an important part of chart interpretation, and the rules used in Jyotish differ significantly from those employed in Western Astrology.`, ja: `Planetary aspects are an important part of chart interpretation, and the rules used in Jyotish differ significantly from those employed in Western Astrology.` } },
      { type: "paragraph", text: { en: `Planets occupying a house project their field of influence across the birth chart and affect, either positively or negatively, other houses and any planets positioned within them. This influence is known as an aspect.`, ja: `Planets occupying a house project their field of influence across the birth chart and affect, either positively or negatively, other houses and any planets positioned within them. This influence is known as an aspect.` } },
      { type: "paragraph", text: { en: `• In Jyotish, aspects are directed from one house to another house (unlike Western Astrology).`, ja: `• In Jyotish, aspects are directed from one house to another house (unlike Western Astrology).` } },
      { type: "paragraph", text: { en: `• Aspects are therefore not based upon one planet's "orb of influence" (for example, a 10-degree sector) interacting with another planet's orb of influence.`, ja: `• Aspects are therefore not based upon one planet's "orb of influence" (for example, a 10-degree sector) interacting with another planet's orb of influence.` } },
      { type: "paragraph", text: { en: `• Consequently, a planetary aspect can affect a house even when that house contains no planets. This is a very important distinction.`, ja: `• Consequently, a planetary aspect can affect a house even when that house contains no planets. This is a very important distinction.` } },
      { type: "paragraph", text: { en: `• Both occupied and empty houses can receive planetary influences through aspects cast from elsewhere in the birth chart.`, ja: `• Both occupied and empty houses can receive planetary influences through aspects cast from elsewhere in the birth chart.` } },
      { type: "paragraph", text: { en: `• Aspects occur from planets located anywhere within one house (for example, the Sun at 2 degrees in the 1st house) and can influence planets located anywhere within the aspected house (for example, Saturn at 29 degrees in the 7th house).`, ja: `• Aspects occur from planets located anywhere within one house (for example, the Sun at 2 degrees in the 1st house) and can influence planets located anywhere within the aspected house (for example, Saturn at 29 degrees in the 7th house).` } },
      { type: "heading", level: 3, text: { en: `A Simple Example of an Aspect`, ja: `A Simple Example of an Aspect` } },
      { type: "paragraph", text: { en: `In the example diagram, the Sun projects its field of influence onto the 7th house counted clockwise from its position. In this particular chart, that house corresponds with the sign of Libra.`, ja: `In the example diagram, the Sun projects its field of influence onto the 7th house counted clockwise from its position. In this particular chart, that house corresponds with the sign of Libra.` } },
      { type: "paragraph", text: { en: `What effect does this have? The answer depends upon several interconnected factors involved in chart interpretation.`, ja: `What effect does this have? The answer depends upon several interconnected factors involved in chart interpretation.` } },
      { type: "paragraph", text: { en: `The first step is to determine the Ascendant. This establishes whether the Sun functions as a benefic or malefic influence within the chart. We must then examine the house occupied by the Sun in order to assess its strength and condition. Once this is done, we can identify which house corresponds with Libra.`, ja: `The first step is to determine the Ascendant. This establishes whether the Sun functions as a benefic or malefic influence within the chart. We must then examine the house occupied by the Sun in order to assess its strength and condition. Once this is done, we can identify which house corresponds with Libra.` } },
      { type: "paragraph", text: { en: `Suppose the chart has a Sagittarius Ascendant. In that case, the Sun becomes the ruler of the auspicious 9th house (Leo in this chart) and is placed in its sign of exaltation, Aries. The Sun would then cast a highly positive influence through its aspect into Libra. Since Libra corresponds with the 11th house in this example, we would expect the affairs of the 11th house to be strengthened and enhanced.`, ja: `Suppose the chart has a Sagittarius Ascendant. In that case, the Sun becomes the ruler of the auspicious 9th house (Leo in this chart) and is placed in its sign of exaltation, Aries. The Sun would then cast a highly positive influence through its aspect into Libra. Since Libra corresponds with the 11th house in this example, we would expect the affairs of the 11th house to be strengthened and enhanced.` } },
      { type: "paragraph", text: { en: `As a result, matters relating to gains, profits, opportunities, and the fulfilment of desires would likely benefit from this aspect.`, ja: `As a result, matters relating to gains, profits, opportunities, and the fulfilment of desires would likely benefit from this aspect.` } },
      { type: "heading", level: 3, text: { en: `Aspect Principle in Jyotish Astrology`, ja: `Aspect Principle in Jyotish Astrology` } },
      { type: "heading", level: 3, text: { en: `Sun Aspects Only the 7th House`, ja: `Sun Aspects Only the 7th House` } },
      { type: "heading", level: 3, text: { en: `Aspect Rules`, ja: `Aspect Rules` } },
      { type: "paragraph", text: { en: `• Rahu and Ketu do not cast any aspects, but all the other planets do.`, ja: `• Rahu and Ketu do not cast any aspects, but all the other planets do.` } },
      { type: "paragraph", text: { en: `• All planets aspect the 7th house from their position.`, ja: `• All planets aspect the 7th house from their position.` } },
      { type: "paragraph", text: { en: `• Mars additionally aspects the 4th and 8th houses from itself.`, ja: `• Mars additionally aspects the 4th and 8th houses from itself.` } },
      { type: "paragraph", text: { en: `• Saturn additionally aspects the 3rd and 10th houses from itself.`, ja: `• Saturn additionally aspects the 3rd and 10th houses from itself.` } },
      { type: "paragraph", text: { en: `• Jupiter additionally aspects the 5th and 9th houses from itself.`, ja: `• Jupiter additionally aspects the 5th and 9th houses from itself.` } },
      { type: "paragraph", text: { en: `When interpreting planetary aspects, both the natural characteristics and the functional characteristics of the aspecting planet must be taken into consideration.`, ja: `When interpreting planetary aspects, both the natural characteristics and the functional characteristics of the aspecting planet must be taken into consideration.` } },
      { type: "heading", level: 3, text: { en: `Aspect Diagram for Mars`, ja: `Aspect Diagram for Mars` } },
      { type: "heading", level: 3, text: { en: `Mars Aspects the 4th, 7th and 8th Houses in Jyotish`, ja: `Mars Aspects the 4th, 7th and 8th Houses in Jyotish` } },
      { type: "paragraph", text: { en: `Mars casts aspects onto the 4th, 7th, and 8th houses counted from its own position in the birth chart.`, ja: `Mars casts aspects onto the 4th, 7th, and 8th houses counted from its own position in the birth chart.` } },
      { type: "heading", level: 3, text: { en: `Aspect Diagram for Jupiter`, ja: `Aspect Diagram for Jupiter` } },
      { type: "heading", level: 3, text: { en: `Jupiter Aspects the 5th, 7th and 9th Houses in Jyotish`, ja: `Jupiter Aspects the 5th, 7th and 9th Houses in Jyotish` } },
      { type: "paragraph", text: { en: `Jupiter casts aspects onto the 5th, 7th, and 9th houses counted from itself.`, ja: `Jupiter casts aspects onto the 5th, 7th, and 9th houses counted from itself.` } },
      { type: "heading", level: 3, text: { en: `Aspect Diagram for Saturn`, ja: `Aspect Diagram for Saturn` } },
      { type: "heading", level: 3, text: { en: `Saturn Aspects the 3rd, 7th and 10th Houses in Jyotish`, ja: `Saturn Aspects the 3rd, 7th and 10th Houses in Jyotish` } },
      { type: "paragraph", text: { en: `Saturn casts aspects onto the 3rd, 7th, and 10th houses counted from its own position.`, ja: `Saturn casts aspects onto the 3rd, 7th, and 10th houses counted from its own position.` } },
      { type: "heading", level: 3, text: { en: `Conjunction and Combustion`, ja: `Conjunction and Combustion` } },
      { type: "paragraph", text: { en: `In Vedic Astrology, the term conjunction is used when two or more planets occupy the same sign or house, even if they are located near opposite ends of that house.`, ja: `In Vedic Astrology, the term conjunction is used when two or more planets occupy the same sign or house, even if they are located near opposite ends of that house.` } },
      { type: "paragraph", text: { en: `For example, if the Sun is positioned at 1 degree Taurus and Saturn at 28 degrees Taurus, they would still be considered conjunct in Jyotish.`, ja: `For example, if the Sun is positioned at 1 degree Taurus and Saturn at 28 degrees Taurus, they would still be considered conjunct in Jyotish.` } },
      { type: "paragraph", text: { en: `Unlike Western Astrology, Jyotish does not place the same emphasis on distinctions such as oppositions, trines, sextiles, and similar aspect patterns.`, ja: `Unlike Western Astrology, Jyotish does not place the same emphasis on distinctions such as oppositions, trines, sextiles, and similar aspect patterns.` } },
      { type: "paragraph", text: { en: `When planets move too close to the Sun, they become weakened and are said to be combust. The exact distance required for combustion varies according to the planet involved.`, ja: `When planets move too close to the Sun, they become weakened and are said to be combust. The exact distance required for combustion varies according to the planet involved.` } },
      { type: "paragraph", text: { en: `As a general guideline, if a planet lies within 10 degrees of the Sun, the possibility of combustion should be considered and the exact combustion limits for that particular planet researched.`, ja: `As a general guideline, if a planet lies within 10 degrees of the Sun, the possibility of combustion should be considered and the exact combustion limits for that particular planet researched.` } },
      { type: "paragraph", text: { en: `Combustion can create a variety of difficulties, including weakening the planet itself, reducing the strength of its natural significations, and negatively affecting the houses it rules.`, ja: `Combustion can create a variety of difficulties, including weakening the planet itself, reducing the strength of its natural significations, and negatively affecting the houses it rules.` } },
      { type: "paragraph", text: { en: `The principle of combustion does not apply to Rahu or Ketu.`, ja: `The principle of combustion does not apply to Rahu or Ketu.` } },
    ],
  }
];
